nsbno/spor

.changeset/shiny-planes-whisper.md
package-lock.json
packages/spor-react/README.md
packages/spor-react/package.json

In order to optimize for flexibility, the `spor-react` package loses a few direct dependencies, and adds them as peer dependencies.
This is a **breaking change**. To upgrade, please run:
```bash
$ npm install @chakra-ui/react @emotion/styled @emotion/react framer-motion
```
Note that this change is for the 0.1.0 release. Since we're still pre-1.0.0, we're introducing breaking changes as minor version bumps. This will change once we get to 1.0.0, hopefully sometime the next couple of weeks.

specify peer deps

---

.changeset/quick-chairs-deny.md
packages/spor-theme-react/src/components/button.ts

This is a weird bug for sure. When you overlay one box shadow with another one, a sub-pixel of the overlaid box shadow will show up. The bug shows up less if you add another box shadow on top

Add a double box shadow to some button states to alleviate a rendering bug

---

.changeset/brown-scissors-hear.md
apps/docs/app/features/routes/index/ActionLinks.tsx
package-lock.json
packages/config/eslint-preset.js
packages/spor-card-react/README.md
packages/spor-card-react/package.json
packages/spor-card-react/src/Card.tsx
packages/spor-card-react/src/index.tsx
packages/spor-card-react/tsconfig.json
packages/spor-react/package.json
packages/spor-react/src/index.tsx
packages/spor-theme-react/src/components/card.ts
packages/spor-theme-react/src/components/index.ts

- Run the add-package script for adding spor-card-react
- Update README with a few details
- Add initial implementation of cards with three variants
- Add initial version of Card component
- Set the initial border as transparent
- Expose the spor-card-react exports through spor-react
- Update package-lock
- Use Card component in our docs
- Make sure you pass in a color scheme when the variant is filled
- Add some basic documentation to card components

Add Card component

---

.changeset/angry-pens-yawn.md
packages/spor-icon-react/bin/generate.ts

Typically, you want icons to be the same size as the text they're next to. That's what `icon: true` does in the svgr tool.
However, we have specified sizes for all our icons, so that doesn't really make sense in our context. Thanks to @annalytic for pointing this out.
You might want to check over all your icons, so that they are the expected size.

Make icons their original size by default

---

apps/docs/app/features/routes/ressurser/design-tokens/SpacingTokens.tsx
apps/docs/app/features/routes/ressurser/design-tokens/TypographyTokens.tsx
apps/docs/app/features/tokens/useTokenFormatter.tsx

- Make the token formatter handle css variables better
- Simplify the spacing tokens implementation
- Simplify the typography tokens

quick fixes in the docs

---

.changeset/fifty-ads-allow.md
.changeset/light-tomatoes-return.md
apps/docs/app/features/component-docs/ComponentDocs.tsx
apps/docs/app/features/component-playground/ComponentPlayground.tsx
apps/docs/app/features/content-menu/SearchInput.tsx
apps/docs/app/features/content-menu/menuStructure.ts
apps/docs/app/features/interactive-code/InteractiveCode.tsx
apps/docs/app/features/interactive-code/LiveEditor.tsx
apps/docs/app/features/interactive-code/LiveError.tsx
apps/docs/app/features/interactive-code/LivePreview.tsx
apps/docs/app/features/interactive-code/LiveProvider.tsx
apps/docs/app/routes/komponenter/knapper.tsx
apps/docs/app/routes/komponenter/tekstfelt.tsx
packages/spor-input-react/src/Input.tsx
packages/spor-input-react/src/PasswordInput.tsx
packages/spor-input-react/src/Select.tsx
packages/spor-theme-react/src/components/form.ts
packages/spor-theme-react/src/components/input.ts
packages/spor-theme-react/src/components/select.ts

Lots of "oh crap I'll just fix that tiny bug" stuff in this PR. I'll try to add context in the comments.
Basically, this PR fixes a lot of issues with the input implementation, and documents it in the process.
- Fix lots of edge cases with input and select rendering
- Add leftIcon and rightIcon props
- Refactor and improve the password input
- Create a more reusable code example component
- Upgrade the component playground to use the new reusable code example components
- Make the intro text slightly larger
- Simplify search field implementation
- Remove now unnecessary prop
- Add basic documentation for input fields

input field docs

---

.changeset/long-owls-sip.md
package-lock.json
packages/spor-input-react/src/Input.tsx

This fixes a bug where - if you didn't wrap your `<Input />` component in a `<FormControl />` component, and didn't provide your own ID - you couldn't click the overlaying label to focus the input.

Make input fields easier to focus even without FormControl wrapping

---

.gitignore
apps/docs/package.json

* Added .idea folder to gitignore (automatically created by intelliJ)
* Made the build work on windows. This is a known issue on remix: https://github.com/remix-run/remix/issues/914

Make build work on windows and ignore .idea folder

---

.changeset/dirty-foxes-draw.md
packages/spor-theme-react/src/components/link.ts

- Separated and changed order of focus and focus-reset to make focus work in Safari and Firefox
- Bugfix for primary variant hover color from pineTeal to darkTeal
- Moved link underline 2px down for when line-height changes from 1.5 (current) to 1.33

Styling corrections to Link component

---

apps/docs/app/features/content-menu/ContentMenu.tsx
apps/docs/app/features/content-menu/MenuItem.tsx
apps/docs/app/features/content-menu/SearchResults.tsx
apps/docs/app/features/content-menu/menuStructure.ts

As we're getting ready to launch the site, we want users to know what parts are implemented and what isn't. This PR disables any menu items that aren't explicitly marked as available in the menu structure.
As we move toward getting all of our content from Sanity, we can delete this code at a later point (if we want to), but it makes sense as of now.

Make unavailable menu items disabled

---

.changeset/khaki-pillows-cry.md
packages/spor-theme-react/src/components/link.ts

This is a suggestion on how to fix multiline links. It does not look exacly the same. The underline is thinner, but going with 2px gets to thick. So feel free to propose how to change it.
Tested with the following code:
```
<Box width="150px">
<Link
children="Her er en lenke med litt lengre tekst"
href="https://w/komponenter/lenker"
variant="primary"
fontSize="16px"
/>
</Box>
```
Before:
After this fix:

Fix underline on multiline links

---

apps/docs/app/features/component-playground/EditableProp.tsx

This pull request changes out choice chips for switches in the component playground

Use a switch instead of choice chips for boolean choices

---

.changeset/hip-hornets-roll.md
packages/spor-design-tokens/.gitignore
packages/spor-design-tokens/config.json
packages/spor-design-tokens/package.json
packages/spor-design-tokens/scripts/build.ts
packages/spor-design-tokens/scripts/formatters/typescript/rn-typings.ts

To use tokens in React Native, use `import * as tokens from "@vygruppen/design-tokens/react-native";`

Add react native design tokens support

---

apps/docs/app/features/layouts/docs-layout/left-sidebar/LeftSidebar.tsx
apps/docs/app/features/site-header/SiteHeader.tsx

This PR fixes a bug where the mobile navigation didn't close when you clicked a link

Close the mobile menu when you click something

---

apps/docs/app/features/code-block/CodeBlock.tsx
apps/docs/package-lock.json
package-lock.json

This pull request fixes a focus trap on our component pages. React Live doesn't give us a way to override its default tab behavior, so we roll our own instead.
To get out of an editor, use the escape (or shift-escape) keys.
- Fix a focus trap by adding escape and shift-escape support
- Update package-lock files

fix focus traps

---

apps/docs/app/features/content-menu/SearchInput.tsx

This pull request adds support for typing cmd+k or ctrl+k to focus the search box.
When you're in the search box, and you have focused something previously, you can press escape to return focus

Add shortcut for focusing the search box

---

.changeset/green-tables-tickle.md
packages/spor-theme-react/src/components/tabs.ts

This pull request fixes a bug where the default tabs variant was unrecognized. 😬 My bad!

Fix a bug with the default tabs variant

---

.changeset/swift-forks-design.md
packages/spor-theme-react/src/components/card.ts

Liten endring på default state av Elevated cards, den skal være synlig på alle bakgrunner:
Color: white- #FFFFFF
Stroke: silver, 1px
Effects: Elevation 2

Add default element of elevated cards

---

.changeset/clever-bags-raise.md
packages/spor-link-react/src/TextLink.tsx
packages/spor-link-react/src/index.tsx

This PR will rename the Link component in favor of TextLink. This makes it a bit easier to use with React Router's Link or Next's Link.

Rename Link component to TextLink

---

.changeset/rare-cups-invent.md
apps/docs/app/features/content-menu/SearchableContentMenu.tsx
apps/docs/package-lock.json
package-lock.json
packages/spor-theme-react/src/components/link.ts

- Make the active and hover link styles work as expected
The reason this didn't work from the outset, was because of the ordering of properties, as well as the `:focus:not(:focus-visible)` selector overriding active styles.
I'm looking forward to Safari's newest version becomes more mainstream, so we can skip these safari related workarounds.

tweak link design

---

.changeset/witty-cooks-sip.md
packages/spor-typography-react/src/Badge.tsx

This pull request adds an `icon` prop to the Badge React component.
Previously, if you wanted an icon in your Badge component, you passed it in as children. This worked well, but required the user to specify the spacing between then icon and the text themselves. 
There were no technical guidelines to help you out on placing the icon either. You should always be placing the icon to the left.
Although you technically can misuse the API to misplace icons, it's now much easier to do the right thing by default.

Add icon prop to badge

---

apps/docs/app/features/table-of-contents/useHeadings.ts

Turns out, we look for changes a bit too early. We fix this by just delaying the table of content updating its content by a frame (16 ms)

Yahoo fix this side menu lagging issue

---

.changeset/tall-shirts-drum.md
package-lock.json
packages/spor-react/package.json

This pull request makes spor-react include its own dependencies, instead of having them as peer dependencies.

Make spor-react include its own batteries

---

.changeset/thick-colts-care.md
packages/spor-theme-react/src/components/choice-chip.ts

Ref to issue https://github.com/nsbno/spor/issues/232 for description
It's kinda weird Chakra adds focus-visible to checkbox even though the checkbox is not checked. This results in the 2px focus border still being visible after unselecting..

Issue 232 Fix choice chips states styling

---

.changeset/two-forks-double.md
packages/spor-theme-react/src/components/choice-chip.ts

Dette PRet fikser en bug der hover-state på choice chips ikke fungerer som det skal.

Fix an issue where the hover state would be applied at the wrong time

---

.changeset/perfect-pandas-poke.md
packages/spor-button-react/src/Button.tsx

Denne PRen "fikser" en bug der loading-indikatoren på små knapper ville overflowe og stikke utenfor selve knappen, om teksten var lang nok.
Det er ikke den beste fiksen jeg har laget - men det fikser problemet i alle fall.

Fix loader overflow

---

.changeset/forty-wolves-happen.md
packages/spor-provider-react/src/SporProvider.tsx

This sets the default text color to `darkGrey` across the site.

Set the default text color to darkGrey

---

package.json

Denne endringen gjør at `npm run dev` kun starter web-stacken (sanity + remix + watching av pakker), istedenfor å dra opp react native også.

La npm run dev starte webstacken

---

.changeset/modern-phones-hide.md
packages/spor-loader-react-native/package.json
packages/spor-loader-react-native/src/ContentLoader.tsx

Denne endringen fikser et problem med ContentLoader-komponenten i React Native. 
Det manglet noen avhengigheter, og jeg tweaket litt på designet i samme slengen.

Fiks en bug i React Native content loaders

---

.changeset/five-fireants-ring.md
apps/rn-demo/ios/Podfile.lock
apps/rn-demo/package-lock.json
packages/spor-icon-react-native/bin/generate.ts
packages/spor-icon/package.json

Dette pull requesten fikser et issues hvor ikoner av en eller annen grunn ble lyseblå. 
Man legger også til støtte for å definere denne fargen selv, via en ny `color`-prop.

Fiks React Native ikoner og farger!

---

.changeset/polite-needles-visit.md
.changeset/serious-ties-work.md
packages/spor-accordion-react/README.md
packages/spor-accordion-react/src/Accordion.tsx
packages/spor-accordion-react/src/AccordionContext.tsx
packages/spor-accordion-react/src/Expandable.tsx
packages/spor-icon-react/bin/componentTemplate.ts

Denne endringen gjør det mye lettere å bruke ikoner med Expandable, ved at man kan kunne spesifisere ikonet med den nye `leftIcon` propen!
```tsx
<Expandable
leftIcon={<InformationOutline30Icon />}
title="Informasjon"
>
Her er litt info
</Expandable>
```

Legg til støtte for `leftIcon` prop på Expandable og ExpandableIcon komponentene

---

.changeset/hot-toys-fix.md
packages/spor-button-react/src/Button.tsx

Dette pull requestet fikser en bug der det ikke gikk an å sette en spesifikk bredde på Button-komponenten.

Fiks bug der width ikke blir lagt til buttons

---

.changeset/olive-buckets-teach.md
apps/rn-demo/app/App.tsx
packages/spor-loader-react-native/src/ContentLoader.tsx
packages/spor-theme-react-native/src/components/text.tsx

Oppdatert text sin theme til å ha tekstfarge `darkGrey` som default. La til variant for `<Text>` komponenten til ContentLoader for å få tekststørrelse i samsvar med Figma.
|Før|Etter|
|--|--|
|![Simulator Screen Shot - iPhone 13 - 2022-07-13 at 10 18 21](https://user-images.githubusercontent.com/100707649/178691880-06e4cd4d-509e-46a8-8b44-4b6f293b859a.png)|![Simulator Screen Shot - iPhone 13 - 2022-07-13 at 10 18 54](https://user-images.githubusercontent.com/100707649/178691958-d2fcd890-ccdd-4b44-be90-e32be0f21d61.png)|

Text variant required

---

packages/spor-button-react-native/src/Button.tsx
packages/spor-theme-react-native/src/components/button.tsx

**Endre paddingen i knappen slik at innholdet blir midtstilt i alle tilfeller**
1. leftIcon + tekst
2. leftIcon uten tekst
3. rightIcon + tekst
4. rightIcon uten tekst.
**ghost buttons har ikke lenger formen til en knapp med margin, og wrapper nå tett rundt innhold.**
Jeg endret fra margin til padding slik at ikon + tekst er perfekt midtstilt. Legg gjerne inn en kommentar hvis det ikke var ønskelig. 
_Original sentrering_
_Ny sentrering_

Små tweaks på Button

---

.changeset/many-mugs-repeat.md
packages/spor-react-native/package.json

Lintingen feiler ved bruk av nyere version av spor enn 0.3.1. Denne endringen ble innført mellom 0.3.1 og 0.3.2 tester derfor å reverte denne slik at nyere version av spor kan tas i bruk. 
- Endre tilbake til index

revert endring av filpath for type i react-native-package.json

---

.changeset/tender-dragons-grin.md
packages/spor-card-react-native/src/Card.tsx

Jeg har flyttet kallet på `card` sin `onPress` funksjon fra `onPressOut` til `OnPress`
Dette fikset bugen som gjorde at man utførte `onPress` når man egentlig bare ønsket å scrolle

Fikse bug med card i scroll-view

---

.changeset/gold-moose-bathe.md
packages/spor-accordion-react/src/Expandable.tsx
packages/spor-theme-react/src/components/accordion.ts

Denne PRen fikser et problem med accordion item titles som går over flere linjer. 
Fixes #331

Multiline accordion item titles

---

.changeset/rare-bulldogs-march.md
packages/spor-accordion-react/src/Accordion.tsx

Denne endringen fikser en bug (i Chakra tror jeg) der allowMultiple ikke fungerer når man har spesifisert en defaultIndex.
Fixes #346

Fiks allowMultiple bug for accordion

---

.changeset/shy-swans-allow.md
packages/spor-theme-react-native/src/components/card.tsx

I følge typografi, stiler og effekter i Figma skal border rundt card komponenten ha coral Green farge. 
Endrer farger på border for Card komponenten 
Starten av videoen viser den nye fargen, senere i videon vises den gamle fargen. 
https://user-images.githubusercontent.com/24417944/182635492-02fd68a0-9d1a-4e0b-9f9a-d6f8d999fee6.mp4

💄Endre farge på onPress border for Card komponenten

---

.changeset/fair-icons-exist.md
packages/spor-icon-react/bin/generate.ts
packages/spor-provider-react/src/SporProvider.tsx

Chakra UI antar at SVGene på hele siden skal være `display: block`, men det stemmer ikke alltid.
Denne endringen setter SVG display tilbake til browser-defaulten. Unntaket er ikoner, som beholder block-standarden sin.
Fixes #357

Fjern `display: block;` fra alle SVGer

---

.changeset/spicy-crabs-admire.md

Det ble innført et changset "Spicy crabs" hvilket gjør at bygget failer. 
Fjerner rn-demo link og config fila.

fjerne config och rn-demo link fra changset som gjør at bygget failer

---

apps/docs/app/features/code-block/CodeBlock.tsx
apps/docs/app/features/code-block/codeTheme.ts
apps/docs/app/features/portable-text/PortableText.tsx
apps/studio/schemas/objects/codeExample.tsx

Denne endringen lar oss legge til kodeeksempler for React Native og Elm også. Slik ser det ut i Sanity:
Dessverre er det ikke noen gode muligheter per i dag for å ha live komponent-previews for Elm eller React Native, så enn så lenge viser vi kun kodeeksemplene her.
Her er et eksempel fra Elm-kodehighlightingen:

Legg til støtte for RN og Elm kodeeksempler

---

.changeset/tidy-pandas-join.md
apps/rn-demo/app/App.tsx
package-lock.json
packages/spor-card-react-native/src/Card.tsx

**Bakgrunn** 
Success ikonet skal ikke havne i mitten i salgsappen
**Løsning**
- fjerne at ikonet skal være sentrert 
- sende med en props som sier at iconet skal være sentrert

Fjerne center av successIconet som default

---

.changeset/friendly-carrots-change.md
packages/spor-button-react-native/src/Button.tsx

Legger til style-prop, så man for eksempel kan sette align-self for å gjøre komponent "inline", og demerd slipper å wrappe den i et view.

✨ Legger til style-prop på Button i React Native

---

apps/docs/app/features/portable-text/PortableText.tsx
apps/studio/schemas/objects/props.tsx

Denne endringen legger til støtte for å legge til React Native-spesifikke props på komponenter på dokumentasjonssiden. Samme for Elm. 
Man kan velge mellom React, React Native, Elm, eller "React & React Native".

Legg til støtte for å dokumentere React Native- og Elm props

---

.changeset/lucky-roses-design.md
packages/spor-message-box-react-native/src/MessageBox.tsx

Denne endringen aligner ikoner og knapper til toppen i MessageBox, og gjør `actionType`-propen optional om man ikke skal ha noen knapp til høyre.
Venter fortsatt på en beslutning på om knapper skal være venstre- eller center aligned, så ikke merge før dette er bekreftet av @perweum :)

Alignment og actionTypes

---

.changeset/unlucky-walls-wonder.md
packages/spor-datepicker-react/src/DateField.tsx
packages/spor-datepicker-react/src/DatePicker.tsx

Denne endringen gjør det mulig å bruke datepickers som en del av native forms.
Du kan også spesifisere navnet på input-elementet ved å sende inn en `name` prop.
Fixes #415

La datepickere fungere som native inputs.

---

packages/spor-design-tokens/scripts/formatters/elm/module.ts

When we generate Elm code, we can end up with punctiation in the function names. This is not valid in Elm.
We can instead replace the punctuation with underscore (the closest thing that could resemble a punctuation?), which is valid. If there are any other suggestions, they are welcome.

Replace invalid character in Elm function name

---

packages/spor-elm/src/Spor/LineTag/LineIcon.elm
packages/spor-elm/src/Spor/LineTag/TravelTag.elm
packages/spor-elm/src/Spor/LineTag/Types.elm

We want to indicate in the travel tags if there are any deviations on the line. There are four types of them: `info`, `minor`, `major` and `critical`.
Implement the styling of the different deviation levels for the travel tag.
| Info      | Minor | Major |  Critical |
| ----------- | ----------- |  ----------- |----------- |
|  ![Skjermbilde 2022-09-16 kl  15 29 41](https://user-images.githubusercontent.com/15145686/190658058-4a831cc9-433b-4660-a541-7975bcd6ddd3.png)      | ![Skjermbilde 2022-09-16 kl  15 38 20](https://user-images.githubusercontent.com/15145686/190658073-ad3a5f6f-b942-4d02-8afa-034f918a9d30.png)        |   ![Skjermbilde 2022-09-16 kl  15 34 09](https://user-images.githubusercontent.com/15145686/190658071-c7075d04-21b1-4f6d-9d6f-e814c4e1bb0d.png)   |  ![Skjermbilde …

Add deviation variants for Elm line tags

---

apps/studio/config/deskStructure.ts
apps/studio/schemas/documents/illustration.tsx
apps/studio/schemas/documents/index.tsx

Denne endringen legger til en ny dokumenttype for illustrasjoner i Sanity. Den ser slik ut:
Er det noe mer vi trenger?

Legg til ny dokumenttype for illustrasjoner

---

.changeset/cold-gorillas-reply.md
package-lock.json
packages/spor-icon-react-native/bin/generate.ts
packages/spor-icon-react-native/bin/typeDefinitionTemplate.ts
packages/spor-icon-react-native/package.json
packages/spor-icon-react-native/tsconfig.json

Denne endringen gjør at man nå kan spesifisere såkalte `Box`-props på React Native-ikoner – akkurat som i React. Det vil si at man kan gjøre følgende:
```tsx
<AddFill18Icon color="brightRed" marginRight={2} />
```
Implementasjonen er litt hacky, men når man skal bruke svgr til å generere React Native-komponenter, har man ikke kontroll over templaten på samme måte som i React. Resultatet blir at man må bruke `String.prototype.replace` for å endre den genererte koden.

Legg til støtte for å bruke fargenavn, marginer etc på ikoner i React Native

---

.changeset/flat-books-warn.md
package.json

Denne fiksen endrer slik at react-native pakker nå blir bygd! Det har visst ikke fungert på en stund - men siden vi bare har én pakke som er react native spesifikk så merket vi det ikke før nå.

Fiks React Native release-bug

---

apps/studio/schemas/documents/illustration.tsx

Denne endringer legger til tre nye felter i Sanity-modellen for illustrasjoner - nemlig beskrivelse av bildet på norsk (bokmål), svensk og engelsk.
Disse tekstene skal brukes som default alt-tekster, om man ikke kan skrive en mer beskrivende en selv gitt utifra konteksten de brukes i.

Legg til beskrivelsesfelter for illustrasjoner i Sanity

---

apps/studio/schemas/documents/illustration.tsx

Etter å ha sett litt mer på hvordan vi ønsker å utforme illustrasjonssiden, trenger vi å endre måten den strukureres på.
Vi har ikke lenger i18n-tekster, da man alltid enten burde droppe alt-tekster på illustrasjoner, eller gi dem en mer kontekstuell beskrivelse.
Vi legger også til muligheten for å laste opp både en lys og en mørk versjon av illustrasjonene.

Endre illustrasjonsmodellen i Sanity

---

.changeset/heavy-spies-roll.md
packages/spor-layout-react/src/Stack.tsx
packages/spor-layout-react/src/index.tsx

Før måtte man bruke direction til å spesifisere retningen. Det kan man fortsatt gjøre, men det anbefales nå å heller bruke flexDirection, for å bruke samme APIet som React Native.

Legg til støtte for å spesifisere retningen av en Stack med flexDirection

---

.changeset/light-rocks-sin.md
packages/spor-icon-react-native/bin/generate.ts

Denne endringen fikser en bug som gjorde at ikoner ikke kunne være hvilken som helst størrelse på React Native.
Grunnen var at `width` og `height` ble satt direkte på den omkringliggende boksen, og ikke SVGen i seg selv.
Denne løsningen gjør det slik at man kan sette størrelser slik:
```tsx
<SomeFill18Icon /> // 99 % av tilfeller
<SomeFill30Icon width={64} height={64} /> // via props
<SomeFill30Icon style={{ width: 64, height: 64 }} /> // via style-prop
```

Gjør ikoner resizable

---

.changeset/pink-mayflies-remember.md
packages/spor-button-react/src/IconButton.tsx

Denne endringen gjør at alle `IconButton` komponenter automatisk får en title-attributt lagt på seg. 
- Om man ikke spesifiserer `title` spesifikt, vil den defaulte til hva enn du sender inn som `aria-label` (som er påkrevd)
- Om du spesifiserer `title` som en tom streng, vil man ikke sette noen title.
- Om du spesifiserer `title` som en ikke-tom streng, vil den overstyre `aria-label`.
```tsx
<IconButton icon={<SomeIcon />} aria-label="Something" /> // title === "Something"
<IconButton icon={<SomeIcon />} aria-label="Something" title="" /> // title === ""
<IconButton icon={<SomeIcon />} aria-label="Something" title="Something else" /> // title === "Something else"
```

Legg til automatisk title-tag for IconButton

---

.changeset/warm-buckets-walk.md
package-lock.json
packages/spor-theme-react/src/components/link.ts
packages/spor-theme-react/src/utils/box-shadow-utils.ts

Denne endringen fikser en bug der lenker så litt feil ut i noen tilstander.
Buggen dukket nok opp da jeg skrev om alle box shadows til å bruke denne nye funksjonen vår "getBoxShadowString" – denne skulle nok i utgangspunktet ikke brukt denne 😅 Men med et nytt flagg som lar oss overstyre om en box shadow skal være inset eller ei, gikk det greit.

Fiks en lenkebug

---

apps/docs/app/features/Images-with-caption/ImageWithCaption.tsx
apps/docs/app/features/portable-text/PortableText.tsx
apps/studio/schemas/objects/imageWithCaption.tsx

Denne endringen legger til støtte for å velge en alignment på bilder.
Det er ikke alltid bilder kan, eller skal, bli alignet, så dette kan kun ses på som en anbefaling

Legg til støtte for å kunne aligne bilder

---

.changeset/rich-timers-carry.md
packages/spor-icon-react/bin/generate.ts

Denne endringen setter `role="img"` på alle ikon-komponenter. Det gjøres for å forbedre brukeropplevelsen for skjermleser-brukere, og for å holde oss til [anbefalingene fra MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/img_role#svg_and_roleimg).
Fixes #507

Add role img to all icons

---

apps/docs/app/features/table-of-contents/useHeadings.ts
apps/docs/app/routes/__base.tsx
apps/docs/app/routes/__base/$category/$slug/index.tsx
apps/docs/app/routes/__base/komponenter/oversikt.tsx
apps/docs/app/routes/__base/ressurser/ikoner/index.tsx
apps/docs/app/routes/__base/ressurser/illustrasjonsbibliotek/alle.tsx
apps/docs/app/routes/__base/ressurser/illustrasjonsbibliotek/index.tsx
apps/docs/app/routes/lekegrind.tsx
apps/docs/app/routes/studio.tsx

Denne endringen er en teknisk oppgradering, som gjør det litt kulere å skrive Remix-kode
- Rewrite all loaders and actions to use LoaderArgs
- Use regular useEffect instead of useLayoutEffect

use loader args instead of loader function

---

.changeset/great-walls-play.md
packages/spor-input-react/src/SearchInput.tsx
packages/spor-linjetag-react/src/InfoTag.tsx
packages/spor-link-react/package.json
packages/spor-link-react/src/TextLink.tsx
packages/spor-logo-react/src/VyLogo.tsx

1.1.1 Ikke-tekstlig innhold (Nivå A)
Hvis det ikke-tekstlige innholdet er ren dekorasjon, skal det implementeres på en slik måte at det kan ignoreres av kompenserende teknologi.
Er det flere steder i Spor-komponentene vi kun bruker dekorative elementer som bør skjules?

Hide decorative element for screen reader

---

.changeset/quiet-fans-peel.md
packages/spor-datepicker-react/src/DatePicker.tsx

Når du trykker på datepicker-ikonet på en disabled datepicker dukker ikke kalenderen opp.

Rmove popover on disabled datepicker

---

.changeset/clean-bags-remain.md
apps/docs/app/features/interactive-code/LivePreview.tsx
apps/docs/app/features/portable-text/PortableText.tsx
apps/docs/app/root.tsx
packages/spor-input-react/src/Switch.tsx
packages/spor-theme-react/src/components/switch.ts
packages/spor-theme-react/src/utils/box-shadow-utils.ts
packages/spor-theme-react/src/utils/focus-utils.ts

Denne endringen introduserer tre ting:
- Dark mode støtte for switches
- Deprekering av outline-varianten for switches
- Støtte for å toggle dark mode i kode-eksemplene.
I tillegg fikset jeg et par bugs som har gjort at focus states har vært litt buggy.

Dark mode støtte for switches, pluss fjerning av variants

---

packages/spor-elm/src/Spor/Internal/TextStyle.elm
packages/spor-elm/src/Spor/LineTag/LineText.elm
packages/spor-elm/src/Spor/TextStyle.elm

We are launching new line tags. The font is a bit fuzzy on web, due to using `VySans` with `fontWeight` `bold`. 
We should rather use `VySans bold` for this (which did not exist here yet).
| --- | ----------- |
| ![Skjermbilde 2022-12-07 kl  15 16 39](https://user-images.githubusercontent.com/15145686/206203557-d334b0fa-c268-42b6-baec-1edb85283a92.png) | ![Skjermbilde 2022-12-07 kl  15 16 50](https://user-images.githubusercontent.com/15145686/206203560-5e5d183b-91a6-44b9-8043-3e26d1f4b7c4.png) |

Add bold VySans for Elm

---

.changeset/perfect-tomatoes-agree.md
packages/spor-theme-react/src/components/choice-chip.ts

@perweum påpekte at choice chips har feil bakgrunnsfarge når de er valgt. Denne PRen endrer det.

Oppdater bakgrunnsfarge på valgte choice chips

---

.changeset/hot-gifts-mate.md
packages/spor-datepicker-react/src/TimeField.tsx
packages/spor-datepicker-react/src/TimePicker.tsx
packages/spor-datepicker-react/src/utils.ts

Dette fikser en bug for når man fjerner alle verdiene i en timepicker (backspacer vekk alle tallene, for eksempel). 
Takk til @FluidSense for å ha oppdaget buggen!

Fiks bug for tom timepicker input

---

.changeset/sour-impalas-juggle.md
apps/docs/app/features/root-providers/RootProviders.tsx
apps/docs/package.json
package-lock.json
packages/spor-datepicker-react/package.json
packages/spor-datepicker-react/src/DateTimeSegment.tsx
packages/spor-datepicker-react/src/TimeField.tsx

Denne fikser en bug der Datepicker ikke fungerte lenger fordi, wait for it, jeg hadde importert to hooks fra to forskjellige pakker.
TIL at `useDateSegment` må være importert fra samme pakke i både `TimeField` og `DateField`. Og ikke `react-aria` det ene stedet, og `@react-aria/datepicker` det andre. Utrolig irriterende at det overhodet går an.
Det var den arbeidsdagen 😅

Fiks en følgefeil i Datepicker

---

.changeset/gold-eggs-cheat.md
packages/spor-theme-react/src/components/travel-tag.ts

Denne PRen fikser en bug der fargene hadde forsvunnet fra noen travel tag devlation icons.

Fiks en fargebug med deviation icons på travel tags

---

.changeset/good-coins-marry.md
package-lock.json
packages/spor-input-react/package.json
packages/spor-input-react/src/CardSelect.tsx
packages/spor-input-react/src/InfoSelect.tsx
packages/spor-input-react/src/ListBox.tsx
packages/spor-input-react/src/Popover.tsx
packages/spor-input-react/src/index.tsx
packages/spor-theme-react/src/components/card-select.ts
packages/spor-theme-react/src/components/index.ts
packages/spor-theme-react/src/utils/box-shadow-utils.ts

Denne pull requesten legger til støtte for en ny type "select" - nemlig en "Card Select"!
Card Selects er i bunn og grunn bare en spesialdesignet trigger-knapp, som viser frem et flytende popover-kort når man trykker på den.
Slik ser det ut:
Det er basert på React Aria, så det burde funke godt med skjermleser også

Ny komponent: CardSelect

---

.changeset/swift-hairs-enjoy.md
packages/spor-theme-react/src/components/button.ts

Denne endringen tillater flere linjer med tekst i en knapp. Det vil gjøre opplevelsen for folk som bruker mye zoom (spesielt på mobil) mye bedre.

Legg til støtte for flere linjer med tekst i knapper

---

.changeset/dull-phones-kiss.md
packages/spor-theme-react/src/components/badge.ts
packages/spor-typography-react/src/Badge.tsx

Denne endringen legger til to nye farger "dark-green" og "dark-blue" til Badge-komponenten sin `colorScheme` prop.
Den renamer også `green` til `light-green` og `blue` til `dark-blue`, for å gjøre det litt enklere å forstå. De gamle navnene `blue` og `green` er nå deprecated, og du vil få en advarsel under utvikling om du bruker dem. De vil bli fjernet til neste major-release.

Legg til nye farger på badges

---

.changeset/perfect-dodos-wave.md
package-lock.json
packages/spor-button-react/package.json
packages/spor-button-react/src/Button.tsx
packages/spor-button-react/src/CloseButton.tsx
packages/spor-button-react/src/index.tsx
packages/spor-input-react/src/SearchInput.tsx
packages/spor-theme-react/src/components/button.ts

Denne endringen legger til et par endringer:
- Ny variant: `<Button variant="floating" />`. som finnes for React Native
- Ny komponent `<CloseButton />`
- Bedret støtte for `<ButtonGroup />` props

Legg til floating button, close button

---

.changeset/thin-pillows-wink.md
packages/spor-theme-react/src/components/badge.ts
packages/spor-typography-react/src/Badge.tsx

Denne endringen deprekerer `size` propen på Badge-komponenten. Badges skal ikke ha forskjellige størrelser, men skal ha litt forskjellig størrelse basert på skjermstørrelser.
Denne endringen fikser også et issue der Badges fikk feil padding når man sender inn et ikon

Deprecate size og fiks padding på ikoner på badges

---

.changeset/olive-roses-repair.md
packages/spor-linjetag-react/src/TravelTag.tsx
packages/spor-theme-react/src/components/travel-tag.ts

Denne endringen bruker litt større ikoner på de store travel tagsa.
Addresses #520

Bruk store avviksikoner på store travel tags

---

.changeset/thin-pans-dress.md
packages/spor-datepicker-react/src/CalendarCell.tsx
packages/spor-datepicker-react/src/utils.ts

Denne PRen fikser en bug der man fikk feil dag på toppen av kalenderen. Dette kommer ifra at vi defaultet til den amerikanske måten å skrive datoer på, som starter uken på søndag istedenfor mandag.
Her spesifiserer vi at vi ønsker den britiske måten å skrive datoer på, som inkluderer dd/mm/yyyy, og at uker starter på mandager.
Fixes #601

Datepicker: Fiks feil dag til feil dato

---

.changeset/seven-turtles-sparkle.md
packages/spor-datepicker-react/src/DatePicker.tsx
packages/spor-datepicker-react/src/DateRangePicker.tsx
packages/spor-theme-react/src/components/datepicker.ts

Denne endringen gjør det mulig å sette en `minHeight` på DatePicker. By default er den 64px, men du kan sette den til f.eks. 54 px for å stemme mer overens med inputfelter f.eks.
```tsx
<DatePicker minHeight={54} />
```
Det brukes `minHeight` istedenfor `height` så man lar boksen vokse med tekststørrelser, for eksempel. Jeg velger å ikke endre default-høyden siden det er slik den er designet, men det kan vi sikkert ta en diskusjon på.
Fixes #534

Gjør datepicker høyden redigerbar

---

.changeset/serious-kings-obey.md
packages/spor-loader-react/package.json
packages/spor-loader-react/src/ProgressBar.tsx
packages/spor-loader-react/src/ProgressLoader.tsx
packages/spor-loader-react/src/index.tsx
packages/spor-loader-react/src/useRotatingLabel.tsx

Denne PRen legger til to nye komponenter – ProgressLoader og ProgressBar.
ProgressBar er en tynn strek du kan spesifisere bredden til med `value`– en verdi mellom 0 og 100 (i prosent). 
ProgressLoader er en illustrasjon du kan spesifisere lengden til med `value` - samme som over.
Om du ikke vet hvor langt i prosessen man har kommet, kan man også droppe å sende inn `value` til disse komponentene, og da ser det slik ut:
| ProgressBar | ProgressLoader |
| --- | --- | 
| ![2023-02-07 22 51 26](https://user-images.githubusercontent.com/1307267/217375659-e23de001-ab16-4148-9f58-274c55fe69c3.gif) | ![2023-02-07 22 50 59](https://user-images.githubusercontent.com/1307267/217375690-69c35205-f7fb-4b70-8293-366b0baf3d54.gif) |
Du kan også sende inn en `label`, som vises under, for å beskrive hva man …

Nye komponenter: ProgressLoader og ProgressBar

---

.changeset/chilled-turkeys-invent.md
.changeset/olive-numbers-know.md
.changeset/perfect-actors-share.md
packages/spor-datepicker-react/src/DateField.tsx
packages/spor-datepicker-react/src/DatePicker.tsx
packages/spor-datepicker-react/src/DateRangePicker.tsx
packages/spor-datepicker-react/src/DateTimeSegment.tsx

Denne pull requesten fikser bugsa som blir meldt inn i #629 . 
- Man kan nå bruke datovelgerne inni komponenter som har `overflow:hidden;`
- Man har en minimumsbredde på felt som gjør at datovelgeren ikke blir større og mindre alt ettersom hvilken dato det er
- Man har nå mulighet til å bruke `FormControl`-komponenten til å sende ned om feltet er ugyldig eller ikke.

Vis datovelgern litt kjærleik

---

.changeset/clever-candles-act.md
packages/spor-datepicker-react/src/Calendar.tsx
packages/spor-datepicker-react/src/CalendarHeader.tsx
packages/spor-datepicker-react/src/CalendarNavigationButton.tsx
packages/spor-datepicker-react/src/DatePicker.tsx
packages/spor-datepicker-react/src/RangeCalendar.tsx

Denne PRen legger til støtte for å kunne endre år i UIen til DatePicker-komponenten.
Før måtte man trykke veldig mange ganger på bakover- eller fremover-knappene, eller skrive inn for hånd. Nå kan man sette `showYearPicker`-propen, og kunne hoppe mellom år i kalenderen.
Si gjerne hva dere synes om navnet `showYearPicker` - om det funker eller om vi burde velge noe annet. 
Merk at det ikke er støtte for å gjøre det samme i `DateRangePicker` per i dag. Det går nok an, men var litt mer tricky enn jeg orket å utforske i dag.
Fixes #535

Legg til støtte for å endre årstall i DatePicker

---

apps/docs/app/features/layouts/footer/Footer.tsx

Denne PRen fikser en bug der jeg ikke hadde lagt til en `key` prop på en liste med rendrede lenker i footeren på siden. Ingen big deal i dette usecaset, men det er jo frustrerende å få en warning i consolen hele tiden.

Add key to list of links in footer

---

.changeset/short-cats-swim.md
packages/spor-typography-react/src/Heading.tsx
packages/spor-typography-react/src/Text.tsx

Denne PRen renamer `textStyle`-propen til `Text` og `Heading` til `variant`. `textStyle` blir deprekert, og fjernes i neste major.

Rename textStyle tilvariant for Text og Heading

---

.changeset/hot-mirrors-enjoy.md
packages/spor-theme-react/src/components/stepper.ts

Denne PRen endrer fargene for steppers i `colorScheme="green"`.
Fixes #643

Endre Stepper-farger for colorScheme="green"

---

.changeset/real-bats-eat.md
packages/spor-loader-react/src/ProgressBar.tsx
packages/spor-loader-react/src/ProgressLoader.tsx

Denne PRen legger til støtte for å kunne bruke box props på ProgressLoader og ProgressBar. 
Det gjør det mulig å legge til margin og padding og maks-bredde osv.

Tillat box props på ProgressLoader og ProgressBar

---

.changeset/quiet-wasps-walk.md
packages/spor-datepicker-react/src/DatePicker.tsx

Koden antok at man hadde wrappet DatePicker-komponenten i en FormControl. Det skal man ikke trenge. 
Fikset dette med å legge til et spørsmålstegn på riktig plass :)

Fiks at DatePicker kræsjer om den ikke er wrappet i en FormControl

---

apps/docs/app/routes/__base/ressurser/illustrasjonsbibliotek/index.tsx
apps/studio/schemas/documents/illustration.tsx

Illustrasjonene vi har i Spor er ment for å brukes på forskjellige flater. Noen skal være store, andre kan nedskaleres endel, og noen skal bare være litt store ikoner.
Denne endringen gjør at man kan definere hvilken størrelse en illustrasjon er ment for, og filtrere ut basert på den størrelsen på nettsiden.

Legg til støtte for å gi illustrasjoner størrelser

---

.changeset/nice-moose-pay.md
packages/spor-datepicker-react/src/TimePicker.tsx

Det gikk an å tabbe seg inn til "bakover" og "fremover" knappene i et disabled Timepicker felt.
Sett isDisabled-propen på disse knappene. Overstyr bakgrunnsfargen til disse knappene, så de ikke får den grå bakgrunnsfargen man får med ghost-knapper.

Disable timepicker-knapper når feltet er disablet

---

.changeset/nine-colts-hear.md
packages/spor-theme-react/src/components/badge.ts

Det var implementert feil tekstfarge i light-blue varianten av badges.
Endre til riktig farge (darkBlue).
Fixes #653

Change the text color of light blue badges

---

.changeset/flat-frogs-jog.md
packages/spor-theme-react/src/components/link.ts

Se #651 
Legg til `box-decoration-break: clone`-propen, som gjør lenkene mye penere når de brekker over flere linjer.
Fixes #651

Improve how multiline links are rendered

---

.changeset/thirty-rules-doubt.md
packages/spor-datepicker-react/src/DateTimeSegment.tsx

Før skrev vi bare 9:11 eller 4:20. Det gjorde at størrelsen på date- og timepickerne endret seg når man kom seg opp i tosifra tidspunkt og datoer.
Legg til en 0 før alle datoer og tidspunkt på ett siffer.
Fixes #661

Pad timepicker and datepicker dates and times with a leading zero

---

apps/docs/terraform/prod/.envrc
apps/docs/terraform/template/main.tf

Kristofer har skikkelig, skikkelig lyst på spor.vy.no
Opprettet assosiasjonen fra App Runner tjenesten til spor.vy.no.
Manuelt opprettet tilhørende oppføringer i DNS-tjenesten for vy.no.

Set up spor.vy.no domain name

---

.changeset/violet-kids-doubt.md
README.md
apps/docs/app/features/linkable-heading/LinkableHeading.tsx
apps/studio/README.md
apps/studio/sanity.config.ts
packages/spor-button-react/src/Button.tsx
packages/spor-datepicker-react/src/TimePicker.tsx
packages/spor-icon-react-native/README.md
packages/spor-icon-react/README.md
packages/spor-input-react/src/CardSelect.tsx
packages/spor-input-react/src/FormErrorMessage.tsx
packages/spor-input-react/src/InfoSelect.tsx
packages/spor-linjetag-react/src/InfoTag.tsx
packages/spor-linjetag-react/src/LineIcon.tsx
packages/spor-linjetag-react/src/TravelTag.tsx
packages/spor-media-controller-react/README.md
packages/spor-react/README.md
packages/spor-tab-react/README.md

Jeg har endelig klart å overtale @jholtan til å kroke meg opp med spor.vy.no. 
Endre alle referanser fra spor.cloud.vy.no til spor.vy.no

Bytt ut spor.cloud.vy.no med spor.vy.no

---

.changeset/eight-starfishes-boil.md
packages/spor-react/src/datepicker/DateRangePicker.tsx

Vi bruker stort sett uncontrolled forms, og da trenger vi navn på input-feltene for at verdier skal kunne valideres og sendes riktig.
Lagt til to props for å sende inn navn til de to datofeltene i `DateRangePicker`. Hadde egentlig håpt å kunne få litt hjelp av react-aria her, men så ikke umiddelbart noen enklere måte å gjøre det på. :thinking:

Add name props to DateRangePicker

---

.changeset/hot-toys-admire.md
packages/spor-react/src/datepicker/DateTimeSegment.tsx
packages/spor-react/src/datepicker/TimePicker.tsx
packages/spor-react/src/theme/components/datepicker.ts
packages/spor-react/src/theme/components/info-select.ts
packages/spor-react/src/theme/components/select.ts

InfoSelect, NativeSelect, Datepicker og TimePicker hadde 16px i tekststørrelse. Det riktige var 18px.
Sett den til 18px.
I tillegg har alle inputfelter nå en høyde på 54px, slik designet tilsier.
Fixes #690

Samme tekststørrelse i alle inputfelt

---

.changeset/sharp-books-end.md
apps/docs/app/features/portable-text/interactive-code/LivePreview.tsx
package-lock.json
package.json
packages/spor-react/src/input/AttachedInputs.tsx
packages/spor-react/src/input/CardSelect.tsx
packages/spor-react/src/input/CountryCodeSelect.tsx
packages/spor-react/src/input/FormErrorMessage.tsx
packages/spor-react/src/input/InfoSelect.tsx
packages/spor-react/src/input/Input.tsx
packages/spor-react/src/input/NativeSelect.tsx
packages/spor-react/src/input/PasswordInput.tsx
packages/spor-react/src/input/PhoneNumberInput.tsx
packages/spor-react/src/input/SearchInput.tsx
packages/spor-react/src/input/index.tsx
packages/spor-react/src/theme/components/info-select.ts
packages/spor-react/src/theme/components/input.ts
packages/spor-react/src/theme/utils/sr-utils.ts

Under omskrivningen av profilsiden trengte vi en måte å hente inn og vise telefonnummere. Det hadde vi ikke, så da var det på tide å lage det!
Lag en ny komponent, `PhoneNumberInput`, som henter inn landkode og telefonnummer.
Den ser slik ut:
Den bruker `awesome-phonenumber` biblioteket som gir oss alle landkodene i verden. Det veier endel, men blir code-splittet ut, og hentet inn asynkront i bakgrunnen. Ganske kult!
APIet er ganske greit:
```tsx
<PhoneNumberInput name="telefonnummer" />
```
Du kan også kontrollere den med `onChange` og `value`:
```tsx
const [state, setState] = useState({ countryCode: '+47', phoneNumber: '' });
<PhoneNumberInput
value={state}
onChange={setState}
/>
```
Den fungerer også veldig bra med `<FormControl>`-komponenten!
```tsx
<FormControl …
```

Ny komponent: PhoneNumberInput

---

.changeset/lovely-keys-pay.md
packages/spor-react/src/input/CountryCodeSelect.tsx
packages/spor-react/src/input/PhoneNumberInput.tsx

Etter å ha tatt den nye PhoneNumberInput i bruk på et faktisk produkt fikk vi litt tilbakemeldinger.
Endre objektet man får tilbake fra å være `{ countryCode: string; phoneNumber: string }` til `{ countryCode: string; nationalNumber: string }`.
Og legg til `+45 (danmark)` og `+46 (sverige)` på toppen av lista av nummere

Addresser litt PhoneNumberInput tilbakemeldinger

---

.changeset/warm-trees-talk.md
packages/spor-design-tokens/tokens/depth/shadow.json

Mengden blur på den minste skyggestørrelsen vår var litt for høy i design-tokenene.
Endre mengden blur til å være det samme som i Figma.
Fixes #682

Endre mengden blur på den minste skyggen

---

.changeset/odd-badgers-end.md
package-lock.json
packages/spor-react/src/input/PhoneNumberInput.tsx

Man kan i teorien skrive inn hva man vil i PhoneNumberInput, noe som kanskje ikke gir så mye mening. Man vil jo bare kunne skrive inn tall, kanskje et mellomrom eller to eller en bindestrek. Men gir man folk muligheten, så skriver folk inn mye tull, som igjen kan føre til dårligere datakvalitet.
Bare inkluder tall, bindestreker og mellomrom i godkjent input.
Om man limer inn noe med bokstaver i seg, fjernes bokstavene (men lovlige tegn blir igjen).
Om man skriver inn en bokstav, så ignoreres den.
Om man skrive inn tall (som man tross alt burde) funker det som det skal.
I tillegg la jeg til type="tel" på input-feltet, som får den til å fungere mye bedre på mobile flater.

Forbedre PhoneNumberInput

---

apps/docs/remix.config.js

Ny oppdatering i Remix krevde et nytt flagg for at bygget ikke brekker
Legg til nevnte flagg.

Specify the cjs server module format

---

.changeset/long-turkeys-thank.md
package-lock.json
packages/spor-react/src/input/Counter.tsx
packages/spor-react/src/input/index.tsx

Vi trenger en counter komponent i det nye reisesøket. Vi har ikke implementert dette fra før av.
Implementer en Counter, med minus og pluss knapper.
Åpen for å snakke om navnet på det, samt staten der man kan trykke på teksten og endre den.
Siden jeg bruker `<input type="number" />` så kan man også bruke piltastene. Gøyalt å bruke plattformen innimellom!

Ny komponent: Counter

---

.changeset/big-queens-ring.md
packages/spor-react/src/datepicker/CalendarGrid.tsx
packages/spor-react/src/datepicker/DatePicker.tsx
packages/spor-react/src/datepicker/DateRangePicker.tsx
packages/spor-react/src/datepicker/DateTimeSegment.tsx
packages/spor-react/src/theme/components/button.ts
packages/spor-react/src/theme/components/datepicker.ts

For å kunne ta i bruk Spor i interne brukerflater, trenger vi støtte for darkMode. Derfor planlegger vi å legge til darkMode i Spor-komponentene etterhvert som vi trenger dem.
Jeg har lagt til mørke farger i datovelgeren. Jeg har prøvd å gjøre det så likt som mulig de komponentene som allerede har støtte for darkMode, men jeg har ikke gjort dette før, så tar gjerne imot innspill hvis dere vil ha noe annerledes 😊

Legge til støtte for darkmode i DatePicker

---

.changeset/new-eels-beg.md
packages/spor-react/src/input/NumericStepper.tsx
packages/spor-react/src/input/index.tsx

Counter var ikke et godt navn på denne komponenten.
Rename til NumericStepper.
Dette er egentlig en breaking change, men siden ingen har tatt den i bruk enda, blir den releaset som en patch.

Rename Counter to NumericStepper

---

.changeset/lemon-snakes-call.md
packages/spor-react/src/input/NumericStepper.tsx

Om man har valgt 0 ting, burde man ikke vise tallet. Og så burde tallet leses opp dersom man endrer verdien med knapper.
Implementer dette ved å bruke `visibility`, så den fortsetter å ta opp plass.
Also, legg til `aria-live="assertive"` og `aria-label`, slik at skjermlesere leser opp den nye verdien når man trykker på knapper.

NumericStepper – skjule verdien dersom verdien er null + forbedret UU

---

.changeset/angry-dingos-cry.md
package-lock.json
packages/spor-react/package.json
packages/spor-react/src/i18n/index.tsx
packages/spor-react/src/input/NumericStepper.tsx
packages/spor-react/src/provider/SporProvider.tsx

Lobo-t er et søtt lite bibliotek, men det vedlikeholdes ikke lenger, og det den gjør er enkelt å gjøre selv.
Implementer en egen løsning for oversettelser, slik at vi eier all denne koden selv. Løsningen er en enkel løsning som er enkel å bruke på forskjellige vis.
En bonus-feature er at man nå kan nøste språkobjekter – så det blir litt enklere å holde orden på tekstene i komponenter som har mange av dem.
En litt mer gjennomgående forklaring av koden og approachen man følger kan man [lese i dette blogginnlegget](https://blogg.bekk.no/lag-ditt-eget-typesikre-oversettelsesbibliotek-54f066348540).

Reimplementer oversettelsesfunksjonalitet

---

.changeset/orange-mirrors-glow.md
packages/spor-react/src/input/Autosuggest.tsx
packages/spor-react/src/input/Combobox.tsx
packages/spor-react/src/input/ListBox.tsx
packages/tsconfig/react-library.json

Da vi skulle ta i bruk Autosuggest-komponenten, så vi at vi hadde et større behov for tilpasning enn det komponenten i utgangspunktet støttet.
Legg til en rekke props for å overstyre margin, padding, ikoner og lytte til fokus.

Legg til noen props til Autosuggest og Combobox komponentene

---

.changeset/witty-insects-tease.md
packages/spor-react/src/input/Autosuggest.tsx

Per i dag så returnerer vi bare key-en til hvilket objekt som ble valgt i en Autosuggest. Det er litt upraktisk, siden Autosuggest ikke eksponerer lista den henter – så vi får ikke hentet den riktige informasjonen.
Når man kaller `onSelectionChange`, returner hele objektet.

Returner hele objektet som blir valgt

---

.changeset/silent-dolphins-fetch.md
packages/spor-react/src/datepicker/TimePicker.tsx

TimePicker sin onChange ga TypeScript feilmelding om man sendte inn en handler på formen `(value: TimeValue) => void` selv om dette var spesifisert i props. Årsaken er at `onChange` også ble dratt med fra BoxProps.
Omitter onChange fra BoxProps

BUGFIX: Omits onChange in TimePickerProps

---

.changeset/wild-goats-warn.md
packages/spor-react/src/input/Combobox.tsx
packages/spor-react/src/input/ListBox.tsx

Før kunne en listbox (resultatlisten til en combobox) bli større enn input-feltet det tilhørte.
Nå vil den oppta bredden til input-feltet, og ikke noe mer.

Combobox-bug: Listboxes tilpasses container

---

.changeset/lemon-eggs-promise.md
packages/spor-react/src/theme/components/listbox.ts

Før var det feil musepeker når man hovret noe i en listbox
Nå bruker man cursor: pointer;

Bruk riktig listbox item musepeker

---

.changeset/selfish-roses-turn.md
packages/spor-react/src/input/AttachedInputs.tsx
packages/spor-react/src/input/CountryCodeSelect.tsx
packages/spor-react/src/input/InfoSelect.tsx
packages/spor-react/src/input/ListBox.tsx
packages/spor-react/src/input/PhoneNumberInput.tsx

Det er en ny major på trappene, og da kan det være greit å fjerne eventuelle deprekerte features.
Fjern SelectItem, SelectItemLabel og SelectItemDescription til fordel for sine navnesøstre Item, ItemLabel og ItemDescription

Fjern deprekerte komponenter

---

.changeset/heavy-pigs-pump.md
packages/spor-react/src/datepicker/DateField.tsx
packages/spor-react/src/datepicker/DatePicker.tsx

Man ønsker å kunne tilpasse bredden på DatePicker-komponenten til å være litt bredere enn den er by default. Ikke fullbredde akkurat, men om man vil at komponenten skal passe inn i et grid for eksempel, kan det være fint å dra ut bredden noen piksler.
La konsumenten overstyre bredden. Typisk vil man kunne sette `width="100%"`, for å få den inn i et grid, eller ha det fullbredde på små flater. Du kan, som med andre box props, sende inn responsive verdier som et array.

La bruker overstyre bredden på Datepicker ved behov.

---

.changeset/healthy-buttons-marry.md
packages/spor-react/src/typography/Heading.tsx

HeadingProps-definisjonen ble ikke brukt, som førte til at man ikke fikk de feilmeldingene man håpet på med v3.
Bruk propsa!

Use heading props

---

.changeset/strong-carrots-guess.md
packages/spor-react/src/input/Combobox.tsx
packages/spor-react/src/input/NumericStepper.tsx

Når verdien i en NumericStepper er 0, fungerer ikke labels. 
Når verdien i en NumericStepper er 0, vil et klikk på labelen legge til 1.

NumericStepper: Forbedre label-oppførsel når verdien er 0

---

.changeset/stupid-rabbits-complain.md
packages/spor-react/src/theme/components/input.ts

Når man flytter musepekeren over labelen i et ikke-utfylt inputfelt, får man "vanlig" pil-musepeker, mens når man hovrer over resten av inputfeltet får man en tekst-musepeker. Dette ser litt rart ut.
Vis tekst-musepekeren uansett.

Display text cursor for form labels inside of inputs

---

.changeset/chatty-trees-kneel.md
.changeset/wild-tigers-boil.md
packages/spor-react/src/datepicker/TimeField.tsx
packages/spor-react/src/input/Combobox.tsx
packages/spor-react/src/input/Popover.tsx
packages/spor-react/src/theme/components/datepicker.ts

Mens vi utvikler nytt reisesøk ser vi et par forbedringsområder vi kan tweake på når det kommer til input-felt
- Vise riktig musepeker på div inputfelt
- La konsument definere høyre-padding for loading-spinneren
- Comboboxes burde ikke flippe, siden de er designet til å kun gå nedover.

Et par input-tweaks

---

.changeset/ninety-kiwis-deny.md
packages/spor-react/src/datepicker/DateField.tsx
packages/spor-react/src/datepicker/DatePicker.tsx
packages/spor-react/src/datepicker/DateTimeSegment.tsx

I forbindelse med nytt reisesøk har vi behov for å fokusere et datofelt. Det var ikke mulig, siden Datepicker ikke godtar refs.
Legg til støtte for å sende inn ref. Den ref-en måtte sendes ned helt ned til hvert date-segment for å faktisk kunne fokusere riktig element.

Datepickers: Gjør dem fokuserbare

---

.changeset/neat-pugs-rush.md
package-lock.json
packages/spor-react/src/input/Combobox.tsx
packages/spor-react/src/input/Popover.tsx

Det er ikke alltid man vil at comboboxer skal stoppe all annen interaksjon på siden.
Fjern backdroppet som rendres av Popover, slik at man kan interagere med andre komponenter (som å fokusere dem, for eksempel).

Remove popover backdrop for comboboxes

---

.changeset/small-nails-smile.md
packages/spor-react/src/input/Textarea.tsx
packages/spor-react/src/theme/components/textarea.ts

Dette er bare et forslag basert på noe jeg kom over. 
I Team Personell trenger vi en `TextArea` med en floating label, slik som `Input`. I tillegg tenkte jeg det er fint at det er litt konsekvent mellom komponentene som er ganske like 😊 
Formen vi trenger det for ser slik ut:
Dersom vi bruker `TextArea` slik den er nå vil det se slik ut: 
Ved siden av hverandre:
Lagt til mulighet for å velge `variant="floating" på en `TextArea`. Legger til variants i theming og i komponenten selv siden den interne strukturen endres med varianten.

Adds floating label variant on TextArea

---

packages/spor-icon-elm/elm.json

#756 la til et nytt API for elm-ikonene. Dessverre så jeg ikke at den krevde nyeste versjon av elm-css, mens alle prosjekter som bruker pakken har én major-versjon under.
Nedgraderer til forrige major-versjon

:arrow_down: Nedgrader elm-css i spor-icon-elm for bedre støtte

---

packages/spor-icon-elm/generate.js

Jeg brukte em istedenfor rem med et uhell. Så dersom noe tekst var større så ble ikonene større enn tenkt.
Bruker rem.

:wheelchair: Ikonstørrelse bør ikke skalere på lokal tekststørrelse

---

.changeset/few-cycles-know.md
packages/spor-react/src/input/Combobox.tsx

When clicking inside the input field, if you do not hit the label, the listbox with suggestions will close. This seems to be due to the `useOutsideClick` (When hitting the label, it does not seem that the useOutsideClick has enough time to trigger, because we click via the label first). The popover already seems to have an outsideClick functionality, and with `useOutsideClick`, the functionality is duplicated and cancels each other out. 
It is also not possible to double click inside the input field while the listbox is open, this should be possible to be able to copy written input. 
Illustrated in the first part of this recording.
https://github.com/nsbno/spor/assets/15145686/8e5687a6-8c05-4f5a-b9a6-20ad0241e4b0
Remove the `useOutsideClick` hook. 
Add the `isNonModal` prop to the popover …

Fix closing issues with combobox

---

package-lock.json
packages/spor-elm/elm.json
packages/spor-elm/src/Spor/LineTag/LineIcon.elm
packages/spor-elm/src/Spor/LineTag/TravelTag.elm

Need to bump the version of `spor-icon-elm` in `travel-costumize`, but this has a dependency on `spor-elm `which uses the old version.
Bumped to newer version. Changed the files that needed to be altered.

Bump version of spor-icon-elm in spor-elm

---

.changeset/cuddly-shirts-sing.md
packages/spor-react/src/accordion/Expandable.tsx

`AccordionProps` og `AccordionItemProps` drar med seg det native HTML-attributtet `title`, og det blir ikke korrekt overskrevet av `title`-propen i Spor.
Omitter `title` fra `AccordionProps` og `AccordionItemProps`, slik at det er vår `title`-prop som blir brukt.

fix: Expandable title prop

---

packages/spor-react/src/datepicker/TimePicker.tsx

https://github.com/nsbno/spor/issues/752
| Before    | After |
| -------- | ------- |
| <img width="303" alt="Skjermbilde 2023-08-18 kl  13 10 17" src="https://github.com/nsbno/spor/assets/15145686/de16a09b-787d-4353-8893-d2075703deef"> | <img width="297" alt="Skjermbilde 2023-08-18 kl  13 10 33" src="https://github.com/nsbno/spor/assets/15145686/e64e1713-3010-4add-a937-3d12b528e51c">   |

Use smaller left and right icons in Timepicker

---

.changeset/bright-panthers-march.md
packages/spor-react/src/datepicker/DateField.tsx
packages/spor-react/src/datepicker/DateTimeSegment.tsx
packages/spor-react/src/datepicker/TimeField.tsx

The paddings for the label and the input in the TimePicker and the DatePicker were a bit off. The color of the punctuation and colon was also dimGrey when it should be darkGrey. 
Fix paddings and text color.
| Before    | After |
| -------- | ------- |
| <img width="374" alt="Skjermbilde 2023-08-21 kl  07 23 57" src="https://github.com/nsbno/spor/assets/15145686/5ba0b9e6-9bd7-452f-b07c-c326b90a16ea">  | <img width="404" alt="Skjermbilde 2023-08-20 kl  21 24 39" src="https://github.com/nsbno/spor/assets/15145686/738c2aa7-d8f1-4952-9161-a6903d640e62">    |
| <img width="339" alt="Skjermbilde 2023-08-21 kl  07 24 21" src="https://github.com/nsbno/spor/assets/15145686/7b415950-7ec0-49c1-bfdc-b70450411c18"> | <img width="335" alt="Skjermbilde 2023-08-20 kl  21 16 42" …

Fix paddings and text color in DatePicker and TimePicker

---

.changeset/soft-terms-ring.md
packages/spor-react/src/typography/Heading.tsx

`2xl` varianten til heading funket ikke i TypeScript, selv om den funka.
Spesifiser typen basert på riktig objekt.
Fixes #779

Fiks heading variants

---

.changeset/dull-shirts-share.md
packages/spor-react/src/accordion/Accordion.tsx
packages/spor-react/src/accordion/Expandable.tsx
packages/spor-react/src/theme/components/accordion.ts

Det var endel småfeil med implementasjonen til Accordion.
Endre endel småting med hvordan accordions ser ut, inkludert
- Mindre avstand mellom ikon og tittel
- Fet tekst i tittel
- Mindre bottom padding i accordion panelet
- Bruke lang-form padding-props
- Fjerne outline på active-staten til list-accordions.

Accordion design tweaks

---

.changeset/nasty-avocados-grab.md
packages/spor-react/src/datepicker/DateTimeSegment.tsx

We want the font size of the TimePicker and DateTime to adapt depending on whether you are on a desktop or mobile.

Make font size in DateTime dynamic

---

packages/spor-react/src/input/NumericStepper.tsx

When using the Numeric Stepper, having the `withInput` prop set to false, the space becomes too small when the number becomes greater than 19. This causes the numbers to overlap each other.
For now, we just increase the width one notch. Screenshot from Playground:

Add more space for larger numbers in Numeric Stepper

---

.changeset/sweet-plants-live.md
packages/spor-react/src/datepicker/CalendarCell.tsx
packages/spor-react/src/input/ListBox.tsx

We experience issues with click throughs in the DatePicker's calendar and in the ComboBox's list box on mobile devices. This was also noticed in React Aria's own examples.
The issue was reported to react-spectrum, and they already linked to other related issues that had been reported before. In one of these, a workaround was suggested. 
The workaround is now tested locally in Spor, and seems to work great (and one can still scroll inside the list box). I believe we can release a new version and test this out in our app (otherwise I would have to copy the components to the app and test them there, which is a bit of a hassle, but not impossible, of course).

Add workaround for click throughs on mobile devices in CalendarCell and ListBox

---

.changeset/perfect-ravens-report.md
packages/spor-react/src/theme/components/accordion.ts

Teksten i tittel og innhold i Accordion-komponenten skulle være responsiv, og ikke alltid i "desktop"-størrelse.
Sett riktig tekststørrelse på riktig breakpoint.

Make accordion text responsive

---

.changeset/afraid-beers-sin.md
packages/spor-react/src/input/Combobox.tsx
packages/spor-react/src/input/InfoSelect.tsx
packages/spor-react/src/input/Popover.tsx

A negative margin was added to the popover due to that the ComboBox popover was displaced some pixels to the right in the app it was used after removing the overlay. The popover will in fact _always_ be displaced to the right relative to the input field when there is less than 12 px padding to the left in the container. This is because the [default minimum container padding is 12 px](https://github.com/adobe/react-spectrum/discussions/5009).
By adding a negative margin, it worked against its purpose for InfoSelect and ComboBox when there is enough left padding, causing the popover to be displaced the opposite way.
We can override the minimum padding by passing `containerPadding: 0` to `usePopover`.

Override minimum left padding in ComboBox and InfoSelect popovers

---

.changeset/loud-pants-taste.md
packages/spor-react/src/theme/components/card.ts

See #806
Remove outline for non-interactive cards, and make the white and light grey versions equal.

Update the design for non-interactive cards

---

.changeset/angry-months-film.md
packages/spor-react/src/theme/components/card.ts

For klikkbare kort så måtte man spesifisere display-propen til block eller flex eksplisitt for at den ikke skulle kræsje
Sett default-verdien til display: block.

Fix bug where display prop was required to not break clickable cards

---

.changeset/perfect-tools-end.md
packages/spor-react/src/theme/components/card.ts

White cards should be white, not light grey, like the last PR made them
Talk to our designer and make the correct design tweaks. In this case, just changing the background color of white cards back to be white.

Fix a color bug with cards

---

.changeset/new-penguins-wait.md
packages/spor-react/src/theme/components/card.ts

Card outlines were inset, meaning they would disappear behind any images. That looked a bit wonky.
Set all outlines as outset instead of inset through the `isInset: false` flag.

Make card outlines work as intended

---

.changeset/little-poets-matter.md
packages/spor-react/src/input/Input.tsx

We didn't get a hover effect when hovering the icon in an input
Add pointer-events: none to the input-element container.

Fix hover effect on icons in input fields

---

.changeset/tall-onions-occur.md
packages/spor-react/src/button/FloatingActionButton.tsx

The floating action buttons didn't work on the server side
Assume that the scroll height is 0 on the server.

Make floating action buttons work on the server

---

.changeset/sixty-carpets-shake.md
packages/spor-icon-react/bin/generate.ts
packages/spor-react/src/alert/BaseAlert.tsx
packages/spor-react/src/alert/ExpandableAlert.tsx
packages/spor-react/src/theme/foundations/lineHeights.ts

There was a bug where the expandable alert component got a double padding.
In addition, there was another bug with icon generation, due to the last upgrade PR.
Fix all the issues.
Turns out, when you specify the `sx` prop, it overrides any regular styling props you pass in. By using the `__css` prop, you avoid this.

Fix expandable alert padding

---

.changeset/hip-flies-change.md
packages/spor-react/src/layout/Divider.tsx
packages/spor-react/src/theme/components/divider.ts
packages/spor-react/src/theme/components/index.ts

The Divider component didn't have any variants or sizes
Re-implement the Divider component and add sizes and variants and support for orientation.

Add divider

---

apps/docs/app/routes/_base.ressurser.design-tokens/ColorTokens.tsx
apps/docs/app/routes/_base.ressurser.ikoner/SearchResults.tsx

After removing the outline from cards, white cards look invisible on white backgrounds. We've been using white cards on white backgrounds a few places in our docs site, and will have to change those usecases.
Change to using the grey version of cards for icons and color tokens.

Make icon and color boxes light grey

---

.changeset/nice-teachers-complain.md
packages/spor-react/src/theme/components/breadcrumb.ts

The textStyle for the breadcrumbs is not set, so the text does not scale according to screen sizes as defined by Spor.
Set the textStyle in the baseStyleLink to be "xs", which was decided by the design for the new web-platform.

Set textstyle for baseStyleLink

---

.changeset/tender-sheep-fix.md
packages/spor-react/src/datepicker/DateTimeSegment.tsx

We used a wider version of our font to ensure things weren't jumping back and forth when using the spinbuttons in the time and date pickers. We'd rater have the correct font.
Solve the jumping around in a slightly different manner, while using the regular font. The downside to this approach is that the placeholders might seem a bit weirdly distributed.
Here is how it looks now:

Use regular instead of tabular font in date and time pickers

---

.changeset/dirty-boxes-kiss.md
packages/spor-react/src/index.tsx
packages/spor-react/src/list/index.tsx

We're using lists and list items today, but not the correct way
Re-export UnorderedList, OrderedList and ListItem components from Chakra

Add list and list items to Spor

---

.changeset/plenty-pumas-taste.md
packages/spor-react/src/theme/foundations/fonts.ts

We didn't have any fallback fonts specified
Add sans-serif as a fallback for heading and body text, and monospace for code.

Add fallback fonts

---

.changeset/five-teachers-collect.md
packages/spor-react/src/provider/SporProvider.tsx
packages/spor-react/src/theme/foundations/index.ts
packages/spor-react/src/theme/foundations/styles.ts

- Global `color` var satt til darkGrey i **spor-react** provideren. Ettersom flere og flere komponenter skal støtte både light og dark colorMode, bør også global styling gjøre det samme. Color må derfor settes basert på hvilken colorMode som er aktiv. 
- Har satt global color til å være **lightGrey** ved dark mode, og beholdt **darkGrey** ved light mode. Det er fargene vi bruker i våre løsninger, siden hvit og svart ofte kan oppleves litt harde, men tar gjerne innspill på hva dere ønsker her👍 
- I samme slengen fjernet jeg den ene `<Global/>` komponenten i SporProvider som satt color + en liten SVG style globalt, og flyttet dette til en egen styles.ts fil under theme/fundamentals i stedet. Dette skal fungere fordi Chakra oppretter global styling basert på det som settes der, ved hjelp av …

Global color støtter både light og dark ColorMode

---

.changeset/olive-ligers-jog.md
packages/spor-react/src/theme/components/button.ts

Closes #852
Adjusts `active` color on Ghost-button. Otherwise, it looks like most was done earlier.
Went through and added dark mode to `Floating`-button.

Correct one alpha color, and add dark mode to floating-button

---

.changeset/old-readers-flow.md
packages/spor-react/src/input/ChoiceChip.tsx
packages/spor-react/src/theme/components/choice-chip.ts

Adds DarkMode support for ChoiceChips, and adds slight color tweaks to align with new design vision.
https://github.com/nsbno/spor/assets/3692249/89347bda-9d32-478d-8bca-5baa1e5ffb5f

Add dark mode to choice chips

---

.changeset/eighty-dodos-relate.md
packages/spor-react/src/theme/components/accordion.ts

Accordions are slightly thinner than they should be according to the [component library.](https://www.figma.com/file/Tmr2URVX2vNkyRLqKhNRQA/Vy_komponentbibliotek?node-id=12402%3A185861&mode=dev)
| size |  height before | height in Figma |
|--|--|--|
| sm | 33 (mobile), 36 | 36|
|md |  36 (mobile), 39 | 42 |
| lg | 48 (mobile), 51 | 54 |
Added a `minHeight` to ensure that they are as tall as they should be as I couldn't get the math to work to use padding.

Add minHeight to Accordions

---

.changeset/gorgeous-kiwis-accept.md
packages/spor-react/src/theme/components/accordion.ts

Partly closes #863 ? 
Added dark mode support for Accordion.
- I did not tackle the floating support for Accordion that we should either inherit background color from parent, or be transparent. I think that's best done in a followup. I'd like advice on how to archive / do this best with css (or a prop)
- I did not change the variant-names; but willing to do changes to support "new" names.
https://github.com/nsbno/spor/assets/3692249/1cd1d65f-5773-4ccb-8679-e2b252b48ad8

Add dark mode to accordions

---

.changeset/happy-otters-explain.md
packages/spor-react/src/button/Button.tsx
packages/spor-react/src/theme/components/button.ts

Support dark mode
Added dark mode to existing button types.
Added `@deprecated` to `tertiary`-variant.
Touched up on current styles to light mode.
https://github.com/nsbno/spor/assets/3692249/79e05d59-4134-4c90-8483-6d48b46a4bda

Dark mode support for Buttons

---

.changeset/thick-insects-poke.md
packages/spor-react/src/button/FloatingActionButton.tsx

We needed our FloatingActionButton to be a link, but the type definition didn't allow that.
Use the correct type definitions for FloatingActionButtons and add forwardRef functionality, so that its API and usage patterns is closer to "regular" buttons.

Add link support for floating action buttons

---

.changeset/calm-ligers-jog.md
packages/spor-react/src/theme/components/breadcrumb.ts

Breadcrumbs looked a bit wonky on smaller screens, since the last item in the list (the current page) didn't get any padding.
Add both padding and rounding to all items in the list.
Also, fix a weird typo.

Fix padding issue with breadcrumbs

---

.changeset/sharp-spiders-do.md
packages/spor-react/src/tab/Tabs.tsx
packages/spor-react/src/theme/components/tabs.ts

need to change variants and design for tabs
Dark -> accent
Green -> accent
Grey -> default
Light -> default
dark and grey are still the same, but adviced to use default and accent instead. previously green and light and changed into accent and default

Update variants and design for tabs

---

.changeset/rare-parrots-float.md
packages/spor-react/src/input/NumericStepper.tsx

Dette er ett slags forslag/feature-request.
Ser at det hadde vært nice med mulighet for større steg (+3, +5, osv.) noen steder vi bruker NumericStepper i Drops Dashboard. Prøvde først å hacke det inn via onChange metoden, men aria-labels blir fort misvisende. Det bør nok tas en runde på om det er riktig å utvide komponenten eller lage en egen. Det hadde jo vært nice om +/- knappene kunne vise hvor mye de endrer med for eksempel. Kunne også vært nice å støtte flere stepsizes samtidig.
* Har lagt til `stepSize`-variabelen, den defaulter til 1. 
* Har oppdatert change metoden til å respektere `stepSize` og tatt høyde for `maxValue` og `minValue`

Add stepSize to NumericStepper

---

.changeset/kind-taxis-cough.md
.changeset/neat-swans-shave.md
.changeset/nice-panthers-smoke.md
.changeset/rare-parrots-float.md
.changeset/sharp-spiders-do.md
.changeset/silver-items-train.md
.changeset/tame-terms-admire.md
.changeset/tasty-feet-decide.md
.changeset/twenty-bulldogs-compare.md
.changeset/wise-worms-complain.md
packages/spor-design-tokens/CHANGELOG.md
packages/spor-design-tokens/package.json
packages/spor-react/CHANGELOG.md
packages/spor-react/package.json
packages/spor-react/src/button/Button.tsx
packages/spor-react/src/datepicker/Calendar.tsx
packages/spor-react/src/datepicker/CalendarCell.tsx
packages/spor-react/src/datepicker/CalendarGrid.tsx
packages/spor-react/src/datepicker/CalendarTriggerButton.tsx
packages/spor-react/src/datepicker/DatePicker.tsx
packages/spor-react/src/datepicker/DateRangePicker.tsx
packages/spor-react/src/datepicker/DateTimeSegment.tsx
packages/spor-react/src/datepicker/RangeCalendar.tsx
packages/spor-react/src/datepicker/StyledField.tsx
packages/spor-react/src/datepicker/TimePicker.tsx
packages/spor-react/src/input/NumericStepper.tsx
packages/spor-react/src/theme/components/button.ts
packages/spor-react/src/theme/components/datepicker.ts
packages/spor-react/src/theme/components/line-icon.ts
packages/spor-react/src/theme/components/travel-tag.ts

We need to implement darkmode version of the time/date/calendar. We also need to add the new variants of calendar and make some minor adjustement to the design of both light and darkmode version
1. Change the position of the calendar button from right side to left side of the datepicker.
2. Changed the design of the calendar-button. It is now the same as the arrow-buttons in timepicker.
3. changed the spacing between the date numbers in the datepicker
4. Calendar button is now a Ghost-button
5. Changed focusorder
6. Added Base, Ghost and floating version of Calendar to both light and dark mode.
7. Added the darkmode versions for the new variants components

Darkmode datepicker

---

.changeset/blue-walls-refuse.md
packages/spor-react/src/theme/components/close-button.ts

this close button used in other components as modal and popover did not have dark mode support
add dark mode support for close_btn. added ghost for it

Dark mode close_btn

---

.changeset/tall-months-dream.md
package-lock.json
packages/spor-react/package.json

There is a bug for the Vy.no header where if you triple-click the Vy header, the `Collapse` component doesn't update properly. Similar to [this](https://github.com/chakra-ui/chakra-ui/issues/7775) issue.
The issue above says that it works on framer-motion v9, so we have to downgrade it. We don't use any of the v10 features so should not be problem, just annoying to not be up to date 😒

Downgrade fraomer-motion because of race condition bug

---

.changeset/fifty-crabs-act.md
packages/spor-react/src/theme/components/card.ts

We want to make radio button cards
Add support for adding `as="label"` for adding clickable styles. Also add support for adding clickable styles with the `.is-clickable` class.

Make label cards a thing

---

.changeset/chatty-taxis-crash.md
packages/spor-react/src/theme/components/popover.ts

popover did not have dark mode support
the colors for light mode did not correspond with close buttons light mode colors
added dark mode support for popover
changed close button to have forced dark mode values for both popovers light mode and dark mode

Darkmode popovers

---

.changeset/healthy-garlics-think.md
.changeset/wicked-chefs-stare.md
apps/docs/app/routes/_base.$category.$slug/route.tsx
apps/studio/schemas/objects/buttonLink.tsx
packages/spor-react/src/button/Button.tsx
packages/spor-react/src/button/ButtonGroup.tsx
packages/spor-react/src/button/FloatingActionButton.tsx
packages/spor-react/src/button/IconButton.tsx
packages/spor-react/src/datepicker/DatePicker.tsx
packages/spor-react/src/datepicker/DateRangePicker.tsx
packages/spor-react/src/link/TextLink.tsx
packages/spor-react/src/tab/Tabs.tsx
packages/spor-react/src/theme/components/button.ts
packages/spor-react/src/theme/components/link.ts
packages/spor-react/src/util/externals.tsx

Turns out we snuck in a breaking change in a previous minor change. Therefore we're dropping the newest major now, so we can make the upgrade path simpler (and adhere to semantic versioning).
In addition to the breaking DatePicker and DateRangePicker changes, this major also removes all deprecated props. And it adds a portal!

Drop new major

---

.changeset/odd-roses-crash.md
packages/spor-react/src/theme/components/info-select.ts
packages/spor-react/src/theme/components/listbox.ts
packages/spor-react/src/theme/utils/background-utils.ts
packages/spor-react/src/theme/utils/border-utils.ts

Closes #873 
I've added a proposal on how we can be more consistant with our theming by providing a set of utility-functions.
For now, I've used them just in InfoSelect, but if this is accepted, these should be widely adopted. Otherwise, there's no point.
I'd like your feedback on the matter @ithen15  and @selbekk .
Otherwise, here's screenshot and video of interactivity. @perweum Maybe you could take a lot on those?
https://github.com/nsbno/spor/assets/3692249/7e0c3f21-220e-4c88-a0e8-3124e3b71368

InfoSelect: added dark mode

---

.changeset/poor-bobcats-bow.md
packages/spor-react/src/input/PasswordInput.tsx
packages/spor-react/src/theme/components/input.ts
packages/spor-react/src/theme/components/select.ts

.. and tweak disabled styling to match Figma sketches (in both light and dark mode).
This closes issue #900 and #903 
1) There were some missing darkMode colors in the Input base styling, specifically for `:disabled` and `:invalid`.
2) The disabled styling deviated from the original Figma sketches. After consulting with @perweum, he confirmed that the sketches were correct and that the spor-react implementation was a bit of. 
1) Added the remaining darkMode colors for `:disabled` and `:invalid`.
2) Changed the styling to match the sketches, and added "not-allowed" disabled cursor as discussed with Per Øyvind.
Some examples. 
| `:Disabled` Before      | `:Disabled` After |
| ----------- | ----------- |
| ![Screenshot 2023-11-01 at 5 07 45 …

Darkmode colors for all Input pseudo classes..

---

apps/studio/desk/structure.ts
apps/studio/sanity.config.ts

We wanted to be able to structure our content in the Studio a bit clearer, with separate folders for each category of articles.
Create a custom structure resolver! Recreated the original structure with their icons and added a filter for categories so that you get unique lists per category for articles. Much easier to navigate like this!

Create custom structure to add filters

---

.changeset/four-seals-divide.md
packages/spor-react/src/datepicker/TimePicker.tsx

Some users don't want a default value at all to the TimePicker component.
Make it possible to pass defaultValue={null} to disable the default value.

Make it possible to pass defaultValue={null}

---

.changeset/selfish-wolves-end.md
packages/spor-react/src/loader/DarkSpinner.tsx

dark spinner was not visible in darkmode
program now swaps between lightspinner and darkspinner if it is in dark mode or light mode

lagt til darkmode for spinner

---

.changeset/selfish-wolves-end.md
.changeset/warm-schools-attack.md
packages/spor-react/src/loader/DarkSpinner.tsx
packages/spor-react/src/stepper/Stepper.tsx
packages/spor-react/src/stepper/StepperContext.tsx
packages/spor-react/src/stepper/StepperStep.tsx
packages/spor-react/src/theme/components/stepper.ts

stepper did not have dark mode support and miss used variation
changed variation to be used the correct way, made the component more universal by using buttons, and added dark mode support

Darkmode stepper

---

.changeset/late-insects-lie.md
packages/spor-react/src/input/PhoneNumberInput.tsx

We want to be able to use `Phone number*` as the label.
Add label as prop. Based on customizable label in TimePicker.

Add customizable label for PhoneNumberInput

---

.changeset/tasty-pianos-hear.md
packages/spor-react/src/button/Button.tsx
packages/spor-react/src/button/IconButton.tsx

The loading state on buttons was a bit borked. It grew in height when you used icons, and the wrong spinner was used.
There were a few things wrong.
- All props were forwarded to the underlying button component, instead of removing the correct ones
- The icon button loading spinner was misaligned.
Fixes #945

Fix some issues with loading states on buttons and icon buttons

---

.changeset/smart-mice-laugh.md
packages/spor-react/src/datepicker/TimeField.tsx
packages/spor-react/src/datepicker/TimePicker.tsx

We want to be able to used a controlled time picker with the ability to unset the time.
`react-stately` appears to already support `null` as value in `useTimeField`. We therefore only make the value type of `TimePicker` match `useTimeField`.

Make value in TimePicker nullable

---

.changeset/polite-eyes-laugh.md
packages/spor-react/src/datepicker/DateField.tsx

When passing in `value={null}` or `defaultValue={null}` to a DatePicker component, a warning was printed to the console about the input going from uncontrolled to controlled.
The issue came from the hidden input field changing from undefined to a value. This was fixed by falling back to an empty value if the value passed was null.
Fixes #950.

Make DatePicker handle null values correctly

---

.changeset/hungry-fishes-swim.md
packages/spor-react/src/input/NumericStepper.tsx

The changes to buttons made the + and - symbols in NumericStepper unreadable in dark mode:
Fixed it by removing the color override:
light mode still works as normal:

Fix the + and - icon in NumericStepper on dark mode

---

.github/workflows/release.yml
apps/docs/Dockerfile
package.json

We were using Node v16, which was deprecated and no longer supported. The newest version of Remix also breaks with node 16.
Bump everything to node 20.

Bump node version to v20

---

.changeset/swift-pots-brush.md
packages/spor-react/src/datepicker/DateRangePicker.tsx

Turns out not only the inner `start` and `end` fields in the `onChange` handler of `DateRangePicker` are nullable, but the wrapping object itself is also in practice null sometimes.
Add null as a possible type to the input value of `DateRangePicker`'s `onChange` function signature.

Make full onChange value nullable for DateRangePicker

---

.changeset/curvy-feet-allow.md
packages/spor-react/src/progress-indicator/ProgressIndicator.tsx
packages/spor-react/src/progress-indicator/index.tsx

With #932, we exported a component that's only used internally.
Remove the export. It's in theory a breaking change, but the previous version hasn't been published yet.

Remove ProgressDot export

---

.changeset/spicy-rabbits-sort.md
package-lock.json
packages/spor-react/package.json
packages/spor-react/src/provider/SporProvider.tsx

When we added support for adding brand overrides, all of our colors were overridden.
Use the `deepmerge` npm dependency to merge the themes. We could've implemented deepmerge ourselves, but the [npm package](https://www.npmjs.com/package/deepmerge) is used by around 20 million people and is tiny and typesafe, so I opted for that instead.

Fix bug with colors being overridden

---

.changeset/tidy-lobsters-fail.md
packages/spor-react/src/input/CardSelect.tsx
packages/spor-react/src/theme/components/card-select.ts
packages/spor-react/src/theme/utils/background-utils.ts

background for card popover was transparent and didnt work on every surface
component lacked som dark mode updates
gave the component a less transparent background as default and props for the developer to chose between a solid dark background or green background.
updated dark mode support for the component

Darkmode card select

---

.changeset/large-eels-eat.md
packages/spor-react/src/button/Button.tsx
packages/spor-react/src/button/IconButton.tsx
packages/spor-react/src/theme/components/button.ts

The buttons have gotten a new design!
There were several tweaks done here. 
- sm and xs buttons get normal font weight
- focus styles are only applied when you use the keyboard to navigate, not when you focus something by clicking it
- when we have a right icon, we left-align the "left icon and/or text" part
- we also re-implement the button using our own implementation instead of Chakra's approach
- we deprecate the "control" button variant

Re-implement buttons

---

.changeset/calm-tips-scream.md
packages/spor-react/src/linjetag/InfoTag.tsx
packages/spor-react/src/linjetag/LineIcon.tsx
packages/spor-react/src/linjetag/TravelTag.tsx
packages/spor-react/src/linjetag/types.d.ts
packages/spor-react/src/theme/components/line-icon.ts
packages/spor-react/src/theme/components/travel-tag.ts

Team Reise needs to override the colors on certain line tags and travel tags, since they support a plethora of sources, not only our own.
Add a new variant="custom" for the LineTag, TravelTag and LineIcon components, which requires custom colors to be set, both for the foreground and background.
It will look like this:
```tsx
<LineIcon
variant="custom"
customIconVariant="ferry"
foregroundColor="#b4da55"
backgroundColor="#c0ffee"
/>
```
The foregroundColor, backgroundColor and customIconVariant props are required when the variant is `"custom"`

Add custom variant to line tags

---

.changeset/real-years-mix.md

We forgot to add `@vygruppen/spor-icon-react` and `@vygruppen/spor-icon-react-native` to the changeset file when adding the Play icon in a previous PR.
Add a changelog file for the icons to be released properly.

Add changeset to release the icons packages

---

.changeset/warm-bikes-begin.md
packages/spor-react/src/datepicker/DateField.tsx
packages/spor-react/src/input/NumericStepper.tsx
packages/spor-react/src/theme/components/card.ts

There were a few bugs that needed addressing:
- Clickable cards got the focus visible state when clicked.
- Numeric stepper buttons got the same issue
- Datepickers didn't allow the user to keep typing in a date (typing 22071987 would not automatically fill out a day, month and a year – just reiterate on the first day field).
Fix em!

Three bugfixes in one

---

.changeset/orange-hotels-shake.md
packages/spor-react/src/button/Button.tsx
packages/spor-react/src/theme/components/button.ts

After the reimplementation of buttons, a bug had appeared that made the buttons look silly and broken when they were rendered as anchors (links – ´<Button as="a" />` for instance).
The bug came from anchors defaulting to being inline, while buttons default to be inline-block.
This fix sets them all to be "display: flex", which looked like it worked the best.

Fix bug with buttons that were broken when links

---

.changeset/three-waves-roll.md
packages/spor-react/src/stepper/Stepper.tsx
packages/spor-react/src/stepper/StepperStep.tsx
packages/spor-react/src/theme/components/stepper.ts

The stepper broke from its more compact display to its more wide-screeny look too early.
Change the breakpoints so that the Stepper component switches over first on small desktops.

Change the way the stepper breaks

---

.changeset/tricky-suns-camp.md
packages/spor-react/src/button/Button.tsx

icons that were not .*24Icon was not aligned verticallly.
Added alignItems to inner flex

fix: make sure icon is vertically aligned in button

---

.changeset/selfish-humans-battle.md
packages/spor-react/src/typography/Heading.tsx
packages/spor-react/src/util/index.tsx
packages/spor-react/src/util/slugify.tsx

We need auto-generated IDs for headings every once in a while. Having a custom slugify function everywhere just gets messy very quickly.
This solution introduces two new features:
- Create and export a `slugify` function. This can be useful in several contexts outside of ID generation (like slugs etc).
- The Heading component now has an `autoId` boolean prop that uses this `slugify` function to generate an id based on the children of the heading. If it's too long, it's shortened to 50 characters. If it's not a string (or array of strings) it won't generate an ID.

Add autoId prop to Heading

---

.changeset/silly-months-sneeze.md
packages/spor-react/src/stepper/Stepper.tsx

To give users of the Stepper more freedom to handle onBackButtonClick we want to send back the number of the step clicked, in stead of checking (and returning) `isFirstStep`
Make onBackButtonClick return the step to go to instead of `isFirstStep`.

Change input to onBackButtonClick

---

.changeset/calm-ligers-cover.md
packages/spor-react/src/input/FormErrorMessage.tsx

The form error messages had a too high zindex set.
Lower it, so that it hides behind modals etc.

Lower the z index issue for form error messages

---

.changeset/smart-coins-yawn.md
packages/spor-react/src/theme/components/link.ts
packages/spor-react/src/theme/utils/text-utils.ts

Updated TextLink colors to be aligned with Figma.
Closes issue: #924 
Review video below for how it is in practise. Verbal ack from @perweum 
https://github.com/nsbno/spor/assets/3692249/6c8611d6-1875-44f7-bd54-dd34987290ac

fix: Update TextLink colors for primary and secondary

---

.changeset/forty-melons-think.md
packages/spor-react/src/input/Combobox.tsx
packages/spor-react/src/theme/components/listbox.ts

The focus styles for listbox items were not like they used to.
Fix them like this:

Fix listbox focus styles

---

.changeset/real-wasps-deliver.md
packages/spor-react/src/accordion/Expandable.tsx

The Expandable component – or the single item accordion – was not as simple as it could have been.
Add isOpen, defaultOpen and onChange props, so that developers can deal with this in a simpler manner than earlier APIs.

Make Expandable easier to use

---

.changeset/sour-ads-drive.md
packages/spor-react/src/theme/components/card.ts

White cards didn't get the correct outline colors in dark mode.
Use the correct variant utils to apply the correct outline colors.

Fix wrong outline colors on dark mode white cards

---

apps/docs/app/root.tsx

The dark mode didn't persist across client side navigations for some reason
Turns out [this was a bug with Chakra IU](https://github.com/chakra-ui/chakra-ui/issues/6622). I added the suggested fix, and checked that it worked.

Resolve weird dark mode flicker

---

.changeset/late-buckets-travel.md
apps/docs/app/root.tsx
apps/docs/app/root/layout/SiteHeader.tsx
apps/docs/app/root/layout/SiteNavigation.tsx
package-lock.json
packages/spor-design-tokens/tokens/color/cargonet.json
packages/spor-react/src/theme/index.ts

We need to support the CargoNet brand.
This PR adds support for specifying the CargoNet brand to the SporProvider, and get yellow components – even in dark mode!
To test it out, you can set ?brand=cargonet in the URL, and the page will be rendered with the CargoNet brand. 🤯

Add cargonet brand

---

.changeset/poor-wombats-impress.md
apps/docs/app/features/portable-text/PortableText.tsx
apps/docs/app/features/portable-text/code-block/CodeBlock.tsx
apps/docs/app/root/layout/SiteNavigation.tsx
apps/docs/app/root/layout/SiteSettings.tsx
apps/docs/app/root/layout/SkipToContent.tsx
apps/docs/app/routes/_base.components.overview/route.tsx
apps/docs/app/routes/_base.resources.design-tokens/RoundingTokens.tsx
apps/docs/app/routes/_base.resources.design-tokens/SpacingTokens.tsx
packages/spor-react/src/input/CardSelect.tsx

Now that we have a bunch of semantic tokens, we can use those!
Use semantic tokens instead of actual colors, so that the page works better as a multibrand site.
Also, add a `fontWeight` prop to the CardSelect.

Only use semantic tokens in the documentation website

---

apps/docs/app/utils/brand-cookie.server.ts

When testing the new dark mode and multi brand support in different browsers, we came across an issue where the brand cookie wasn't set correctly in Safari for some reason.
Removing a few restrictions on the cookie seemed to help!

Make the brand switcher work in Safari

---

packages/spor-design-tokens/tokens/depth/shadow.json

New values for elevation. For app and web.
Changed the values in the json. Here is the test for Andoroid/iOS:

Update elevation tokens

---

apps/docs/app/utils/icons.server.ts

When upgrading Remix to use Vite, we ended up moving to using esmodules, instead of commonjs modules. This broke our download icons code, because esmodules doesn't expose the __dirname global variable.
Figure out the __dirname variable another way – [courtesy of StackOverflow](https://stackoverflow.com/questions/72456535/referenceerror-dirname-is-not-defined-in-es-module-scope).

Redefine __dirname, since it needs to be defined differently when using esmodules

---

apps/docs/app/root/layout/RootLayout.tsx

A weird bug happened where the header would not take the entire width of the screen.
Added an overflow auto and it seemed to sort itself out.
Before at 1025px: 
Now at 1025px:

💄 Removed weird layout bug at around 1000px width

---

.changeset/fluffy-months-melt.md
apps/docs/app/routes/_base.resources.illustration-library.all/route.tsx
packages/spor-react/src/alert/AlertIcon.tsx
packages/spor-react/src/card/StaticCard.tsx
packages/spor-react/src/card/index.tsx
packages/spor-react/src/theme/components/index.ts
packages/spor-react/src/theme/components/static-card.ts

I Figma finnes en variant av card som er static, som er “flat” (ingen skygger, osv. som gir elevation). Denne finnes ikke i Spor p.t.
Ikke ha egne “hacks” som komponenter når de burde finnes i Spor
La til static card i spor

Add static card to spor

---

.changeset/twelve-pigs-act.md
packages/spor-react/src/input/Combobox.tsx

Despite the Combo-box using the Input, a left icon wasn't supported.
Removed undefined props so that the icon would set properly and the input styling for icons would kick in.

Left icon support on combobox

---

.changeset/afraid-avocados-clean.md
packages/spor-design-tokens/tokens/color/palette.json

Changed 3 hex values for design tokens did not match the designsystem in Figma (values 400, 500, 600).

Change color tokens for orange

---

packages/spor-design-tokens/config.ts

The size of elements was rendered in px and this was preventing to apply effect of using zoom settings in browser.
By changing the rendering size unit of elements from px to rem, all sizes are connected to the settings of the browser and adapt to user choice

Change render sizes in frontend to rem

---

apps/docs/vite.config.mts

Currently with Vite and Remix there was a bug that happened, which caused the HMR to crash whenever you did any changes to the components - which ended up in you having to restart the server. Every. Single. Time.
It tried to access chunks in the spor-react/dist and had no luck in finding these, which made the HMR crash.
What I did was setting CachedChecks to false.
When the CachedChecks is set to true (which also is the default behaviour) Vite caches the result of file system checks. This means that Vite will remember whether files have changed since the last check, improving the performance by avoiding file system operations. But it's less accurate and might miss or not locate files that already exists.
When its set to False: Vite will not cache the file system checks. This means Vite …

Fix for HMR crashing issue by disabling CachedChecks.

---

.changeset/fluffy-carpets-thank.md
packages/spor-react/src/theme/components/datepicker.ts

There was no background on the datepicker, which made it impossible to see.
Added floating BG to border and background on the popover of the datepicker.
Before: 
After:

Added floating to bg and border

---

.changeset/calm-wolves-invite.md
apps/docs/package.json
packages/spor-react/src/card/PressableCard.tsx
packages/spor-react/src/card/index.tsx
packages/spor-react/src/theme/components/index.ts
packages/spor-react/src/theme/components/pressable-card.ts
packages/spor-react/src/theme/components/static-card.ts

I Figma finnes en variant av card som er pressable. Denne finnes ikke i Spor p.t.
La til pressable card i spor

Add pressable card to Spor

---

.circleci/config.yml

To ensure a failing deploy is not cached as a layer, we need to temporarily disable cache when building the docker image
add --no-cache to circleCi config

Temporarily disable docker build cache

---

.circleci/config.yml

In the previous PR we disabled the cache to be able to ensure we weren't reusing any layers from a broken build
So here we enable caching again, for faster docker builds 🚀

Enable docker build cache

---

.changeset/healthy-needles-help.md
apps/docs/package.json
packages/spor-react/src/card/PressableCard.tsx
packages/spor-react/src/card/index.tsx
packages/spor-react/src/theme/components/index.ts
packages/spor-react/src/theme/components/pressable-card.ts
packages/spor-react/src/theme/components/static-card.ts

We are adding Pressable Card back to spor after reverting it based on spor breaking after deploying it last time. 
We concluded that this is related to versioning, and not the component code. Therefore deploying the same component code again. This time as a patch instead of minor change.

Add pressable card again

---

.changeset/large-bobcats-kick.md
packages/spor-react/src/table/Table.tsx
packages/spor-react/src/theme/components/table.ts

We had issues with layout of tables with lot of columns and content, especially when mobile breakpoints matches. 
By setting a minimum width to the table and a minimum width to table cells it is possible to control when the horizontal scroll display and a vertical align has been also added to cells to preserve readability of the table rows

Improve layout of content for responsive when content overflow

---

.changeset/plenty-gorillas-collect.md
packages/spor-react/src/card/Card.tsx

A recent change (9.0.1) changed the Card component to use `sx`-prop to set the default styling, instead of `_css`.
Since `sx` has the highest precedence it will override any style props passed to the Card (Card accepts props that extends `HTMLChakraProps<"div">`)
example:
`<Card display="flex">` will not actually result in an element with `display: flex` as long as `Card` is implemented with `sx={styles}` and styles includes (among other default styling): `display: block`. 
Revert the implementation of Card back to being styled with `__css` which as a lower precedence than style props

Stop Card from overriding style props

---

apps/docs/package.json

We need to bump package version in order to use Pressable Card in spor
Bump the package version.

Bump package version

---

.changeset/brave-poets-roll.md
packages/spor-icon-react-native/package.json

The three newest React Native icon versions are currently broken because Metro cant find the index-file.
Changing the path to a .mjs file ending similarly to the other packages, which is the file-ending that metro is looking for.

🐛 Fix bug where metro cant find index-file.

---

.changeset/three-cheetahs-provide.md
packages/spor-react/src/theme/components/static-card.ts

Added some missing dark colors to Static card as described in figma. 
Added dark colors for blue, yellow and green. 
Figma: 
https://www.figma.com/file/Tmr2URVX2vNkyRLqKhNRQA/Vy_komponentbibliotek?type=design&node-id=22583-12506&mode=design&t=5FgQV05lY5rMX2nS-0

Add dark colors to static card

---

.changeset/spicy-students-explode.md
package-lock.json
packages/spor-react/src/theme/components/table.ts

Tables outside Sanity is affected negatively by a static value from Tables.
Removed static value "top" from vertical-align. It is possible to add this manually to any of the tags coming from Table.

Edit table UI

---

.changeset/lovely-sloths-jog.md
apps/docs/package.json
packages/spor-react/src/theme/components/table.ts

Some values make table static. These should be added to the frontend of apps that use Spor and not to Spor directly.

Remove static values from table

---

.changeset/hot-buttons-juggle.md
apps/docs/package.json
package-lock.json
packages/spor-react/src/layout/PressableCard.tsx
packages/spor-react/src/layout/StaticCard.tsx
packages/spor-react/src/theme/components/pressable-card.ts
packages/spor-react/src/theme/utils/floating-utils.ts

- Made variant optional, as it caused errors when defining "to" and "as" attributes
- Fixed background on darkmode
- Transition

Fix pressable card

---

apps/docs/app/root/layout/RootLayout.tsx
apps/docs/app/root/layout/SiteSettings.tsx
apps/docs/package.json

It seemed the background didn't always render the correct color.
The fault is hard to produce locally. I have added a client-side render to fix this issue. Shouldn't affect the performance much.
Solves https://github.com/nsbno/spor/issues/1078
No changesets as it doesn't concern any packages.

Background on darkmode

---

.changeset/slimy-news-knock.md
apps/docs/package.json
packages/spor-design-tokens/tokens/color/cargonet.json
packages/spor-design-tokens/tokens/color/vy-digital.json

Some color-tokens needed to be updated. 
Based on this list:
| Token | Color |
| --- | --- |
| bg-tertiary | bisque | x
| text-default | darkGrey |x
| text-secondary | dimGrey | x
| text-tertiary | osloGrey | x
| text-highlight | wood | x
| icon-highlight | wood | x
| outline-focus | pumpkin | x
| surface-secondary | champagne | x
| base-surface:active | bisque | x
| brand-surface:default | saffron | x
| brand-surface:hover | pumpkin | x
| brand-surface:active | rajah | x
| brand-text:default | black 100% | x
| brand-icon:default | black 100% | x
| floating-surface:active | bisque | x
| ghost-surface:hover | champagne | x
| ghost-surface:active | bisque | x
| Token | Color |
| --- | --- |
| bg-default | black 100% | x
| bg-secondary | black 100% | x
| bg-tertiary | darkGrey | x
| …

Update color-tokens for CargoNet and Vy digital

---

.changeset/young-moles-arrive.md
packages/spor-react/src/modal/FullScreenDrawer.tsx
packages/spor-react/src/modal/SimpleDrawer.tsx

Chakra, for drawer, sets `aria-describedby` default value for chakra-modal to be the id of the drawer body. This creates some voiceover issues on iphone (in browser) as any child components in the drawer body that doesn't have `aria-describedby` set instead uses the `aria-describedby` default value set for the entire modal.
Add a prop to FullScreenDrawer and SimpleDrawer that contains props for drawer body. This will enable the user to set a specific id for drawer body that doesn't match the default `aria-describedby`.

FullScreeenDrawer and SimpleDrawer: add props for drawer body

---

.changeset/strong-insects-hammer.md
apps/docs/package.json
package-lock.json
packages/spor-react/src/modal/FullScreenDrawer.tsx

FullScreenDrawer needed a back button according to the designsystem in Figma. And for new designs for Cargonet.
Added back button and more spacing for the title.
Test by going to the Drawer page in documentation and open the FullScreenDrawer.
| Desktop | Mobile |
| <img width="1023" alt="image" src="https://github.com/nsbno/spor/assets/42611957/3238fc95-9c7b-434e-b967-029da4a6bd62"> | <img width="423" alt="image" src="https://github.com/nsbno/spor/assets/42611957/e30bb4f9-6835-4d28-ad9f-62c2521af337"> |

Add back button to FullScreenDrawer

---

.changeset/three-masks-yell.md
packages/spor-react/src/input/InfoSelect.tsx
packages/spor-react/src/theme/components/info-select.ts

PhoneNumberInput had top aligned country code.
Skip setting hieght and transform when `isLabelSrOnly` is true, to keep vertical center aligned value.
| ![bilde](https://github.com/nsbno/spor/assets/62022184/55ebb9de-7eae-4f5f-a529-c2c063e3d9d2)|![bilde](https://github.com/nsbno/spor/assets/62022184/fca9ffe6-4cff-440f-b8f8-890139835fca)|
|![bilde](https://github.com/nsbno/spor/assets/62022184/9cb470ac-5bfa-495c-b73d-5b9a6534ad89)|![bilde](https://github.com/nsbno/spor/assets/62022184/a2b6b736-a15c-4c0b-a917-5de07d09e1b8)|

InfoSelect center value when screen-reader only

---

.changeset/friendly-knives-buy.md
apps/docs/package.json
package-lock.json
packages/spor-react/src/input/Combobox.tsx
packages/spor-react/src/input/Input.tsx
packages/spor-react/src/input/ListBox.tsx
packages/spor-react/src/theme/components/listbox.ts

It was not possible to use the arrows to navigate through Combobox. Both Combobox and ListBox was lacking semantics and styling for focus and focusvisible. 
Added the semantics and styling
Go to /components/combobox and use the arrows to navigate. Enter button to make a selection.

Make Combobox & ListBox accessible

---

.changeset/poor-geese-fry.md
apps/docs/package.json
packages/spor-react/src/input/ChoiceChip.tsx

There was an error in console on props for ChoiceChip
- Moved props from variable to function parameters
- Added a condition to hasLabel
Go to components/choice-chip
No error in the console :)

ChoiceChip: Fix type error and style bug

---

.changeset/big-lobsters-cough.md
apps/docs/package.json
package-lock.json
packages/spor-react/src/datepicker/CalendarTriggerButton.tsx
packages/spor-react/src/datepicker/DateField.tsx
packages/spor-react/src/datepicker/DatePicker.tsx
packages/spor-react/src/datepicker/DateTimeSegment.tsx
packages/spor-react/src/datepicker/StyledField.tsx
packages/spor-react/src/theme/components/datepicker.ts

DatePicker had a typerror on isDisabled. Also noticed made some accessibility improvements.
Go to /components/datepicker
There should be no warnings in the console and VoiceOver should work as expected with labels.

DatePicker: Fix typerror and accessibility

---

.changeset/heavy-jokes-juggle.md
packages/spor-react/src/input/Input.tsx

Some confusion with aria-labels on Input.
- Added new id for label. Set id to label. Change aria-label on input to label id.

Input: Rearrange accessibility labels

---

.changeset/dull-toes-kiss.md
packages/spor-react/src/linjetag/LineIcon.tsx
packages/spor-react/src/linjetag/TravelTag.tsx
packages/spor-react/src/linjetag/types.ts

Console was complaining of errors for props. I moved the props to the right type declarations and removed props-spreading from the icon container.

LineTag: Fix type error on props

---

.changeset/violet-pigs-allow.md
package-lock.json
packages/spor-react/src/input/ChoiceChip.tsx

isChecked was accidentally added to props. Is now removed.

ChoiceChip: Fix bug with isChecked

---

.changeset/gorgeous-eagles-hope.md
package-lock.json
packages/spor-react/src/input/Input.tsx
packages/spor-react/src/theme/components/input.ts

Floating variant for component input is made in the component library in Figma, but not yet implemented.
https://www.figma.com/design/Tmr2URVX2vNkyRLqKhNRQA/Vy_komponentbibliotek?node-id=607-0&t=4fQsGIk3cx9YZ6eG-0
Add functionality to set variant for input component, and add styling for variant _floating_.
| ![bilde](https://github.com/nsbno/spor/assets/155733601/57863218-b33b-4897-8268-7b40dc13ba2a)|![bilde](https://github.com/nsbno/spor/assets/155733601/59f0177b-869f-4321-8b04-3e27da341620)|

Added floating variant to input

---

.changeset/bright-walls-exist.md
package-lock.json
packages/spor-react/src/modal/ModalHeader.tsx

Accessibility says the title should be h1, not header tag.
Added header tag.
/components/modal

Add h1 tag to title

---

.changeset/chilled-rockets-accept.md
package-lock.json
packages/spor-react/src/input/NumericStepper.tsx

Using screen readers with today's solution reads out add 1 and subtract 1, but does not allow us to provide any context to what to add 1 of.
In addition, when navigation using only keyboard there was an issue with focus changes. When we press the minus button so that the value goes to zero, the button disapears, moving the focus to the top of the page.
Added a new input parameter and updated the aria-labels to allow us to provide a context in both singular and plural form.
Additionally, added functionality to move the focus to the plus-button when the minus button disapears.
Test the component in playground using screen reader.
Not including the new prop should yield no changes. E.g. …

Added context prop to nummeric stepper to improve voiceover support

---

.changeset/blue-adults-fetch.md
package-lock.json
packages/spor-react/src/theme/components/travel-tag.ts

There was a rather large difference in how the deviation icons for the line tags was styled in spor compared to figma.
Confering with designers, it was said that the icons in the App looked to be correct
Removed stroke from deviationIconStyle and removed golden color for minor and major for color from deviationIconColor, in order to use "default" svg color
This makes it more inline to how the icons are used in the travelTag in the App:
https://github.com/nsbno/salgsapp-react-native/blob/aed64cd14564d7ea3e7f6899ac8e8846b361e256/app/spor/linetag/TravelTag.tsx#L89
Paste this code in playground when running spor locally:
```
<Flex gap={1} flexWrap="wrap">
<TravelTag 
variant="local-train" …
```

Adjust deviation icons for line tags, to make them more inline with figma

---

.changeset/blue-adults-fetch.md
.changeset/silver-crabs-laugh.md
package-lock.json
packages/spor-react/src/theme/components/travel-tag.ts

The TravelTag deviation icons has a very high z-index, which causes the icons to float atop banners and such
Reduce the z-index for the TravelTag deviation icons
Before:

z-index adjustment for deviation icon

---

apps/docs/package.json
package-lock.json
packages/spor-react/src/input/Input.tsx

https://trello.com/c/DQAfaqop/6525-oppdatere-inputgroup-spor-komponent-for-react-til-%C3%A5-ha-overflowhidden
Long labels ran outside the input field.
Added `overflow="hidden"` to `ChakraInput`
Writing a long text in an inputField should be contained inside the input field

Added overflow=hidden to <Input/>

---

.circleci/config.yml

CircleCi announced that older remote image versions will receive a 24-hour brownout period on August 28th, pending EOL on September 30th.
Update version for remote docker in circleCi config, as specified in their support article

Update version for remote docker in circleCi config

---

.changeset/chilled-cheetahs-applaud.md
apps/docs/package.json
packages/spor-react/src/input/PhoneNumberInput.tsx

The phoneNumberInput at the Swedish payment page are optional for not-main travellers, but currently not visible for the user that it is
Add prop to be able to show that the field is optional
Technical change. No change on current inputs, but able to add the prop `isOptional={true}` to see the new text
|    <img width="862" alt="image" src="https://github.com/user-attachments/assets/cb0ff041-f542-4637-81c5-70e1955e5213">    |   <img width="881" alt="image" src="https://github.com/user-attachments/assets/7a39d85a-29b5-4100-af49-0840bd4f0268">    |
|          |     <img width="867" alt="image" src="https://github.com/user-attachments/assets/5a33b3ea-e009-4b02- …

Added the option to display optional phone number

---

apps/docs/tsconfig.json
apps/docs/types.d.ts
package-lock.json

There is a weird bug when you have moduleResolution set to bundler, causing modules that use a more direct import style to become unresolvable. The solution for this wasn’t obvious.
The reason turned out to be related to our spor-react library, where we use Chakra’s forwardRef. The definition is specified to be within some dist folder in Chakra.
I suppose there might be some tricks to work around this by importing it differently, but it has become too time-consuming to chase this any further, especially since we might switch to another component library later on.
The problem doesn’t occur if you set moduleResolution to node.
Describe the background for this task, why it emerged and why it must be solved.
Created a type declaration file that correct the reference.

Added type declaration for chakra

---

.changeset/ninety-snakes-kneel.md
packages/spor-icon/svg/feedback/realtime-cancelled-12x12.svg
packages/spor-icon/svg/feedback/realtime-delay-12x12.svg
packages/spor-icon/svg/feedback/realtime-delay-18x18.svg
packages/spor-icon/svg/feedback/realtime-not started-12x12.svg
packages/spor-icon/svg/feedback/realtime-on route-12x12.svg

https://trello.com/c/TewSXLVA
The contrast in the realtime icon has been too low, so it has been updated. It needs to be updated in Spor and in the spor library.
Update the icons
Open spor docs, navigate to http://localhost:3000/resources/icon-library select x18 size and search for it.
before:
after:

Updated realtime icons due to bad contrast

---

apps/docs/app/routes/_index/ActionLinks.tsx
apps/docs/package.json

A major change in the spor-icons package changed the same of Icons to Stars.
This is being used for icons on the frontpage.
Also removed unused code and fixed a type error in the same file.

Change Icons to Stars in docs

---

apps/docs/app/routes/_index/ActionLinks.tsx
apps/docs/package.json
package-lock.json

main will not build in CircleCI because of a mismatch with versions.
Updated package-lock with the right build

Run local build

---

.changeset/cuddly-yaks-beam.md
package-lock.json
packages/spor-icon-react/package.json

spor-icon-react did not update automatically with the new version of spor-icon

Fix icon bug

---

.changeset/tough-feet-give.md
packages/spor-react/src/theme/components/divider.ts

One could barely see that the dash was dashed. 
I've added new styling that allows for more spacing between the dashes.
Check the Divider component. 
| ![image](https://github.com/user-attachments/assets/c605538d-7c00-49b4-8a4f-e0840123514a) | ![image](https://github.com/user-attachments/assets/be2951b5-e4b1-473d-a334-a3e430d373b8) |

Divider: Update styling for dashed variant

---

.changeset/orange-walls-camp.md
packages/spor-react/src/loader/ProgressBar.tsx
packages/spor-react/src/theme/components/progress-bar.ts

For easy access to change the color, a isActive prop is added to the component.

ProgressBar: New isActive prop

---

.deployment/config.yaml

When migrating to the new account we used a branch filter to deploy the specified branch.
Update branch filter to deploy from main branch again

Update branch filter to main, after migrating to common services

---

apps/docs/app/utils/sanity/config.ts

We had propbaly a mini-dos attack, leading us to nearly use up our sanity quota. Due to not using cdn for sanity requests.
Use CDN for sanity requests

use cdn by default

---

apps/docs/app/routes/_index/ActionLinks.tsx

"as" wasn't defined for external link, so the "a" was defined as a div instead.
added as tag

use as="a" for external links in actionLink

---

apps/docs/app/root.tsx

CI is complaining that useConst is not defined. Causing the CI build to fail.
Also, seems like the docs in chakra has the same issue:
https://v2.chakra-ui.com/docs/hooks/use-const
Since we're only using this hook once, i've implemented a similar logic instead

implemented  useConst as the one from chakra caused problems

---

.changeset/large-rice-buy.md
packages/spor-react/src/i18n/index.tsx

Different methods using TranslationObjet is exposed and used by frontend, but they have to define their own version of TranslationObject.
Export the actual type used in spor to be able for frontend to use the correct type.

Export type TranslationObject

---

.changeset/fast-carrots-raise.md
packages/spor-react/src/theme/utils/input-utils.ts

When using the LastPass browser extension input labels are not styled correctly. This happens because LastPass injects HTML between the `<input>` and `<label>` elements causing this CSS selector to not fire: `input + label { ... }`.
Updated inputBaseStyle to ensure `input + label { ... }` styling is applied when using LastPass extension.
Check that inputs with autocomplete have correct styling when using the LastPass browser extension.
| ![Screenshot 2024-10-22 at 16 36 …

Fix input label style bug caused by LastPass extension

---

.changeset/lovely-tools-serve.md
packages/spor-react/src/input/PhoneNumberInput.tsx

The label logic was wrong. It always ignored externalLabel.
https://nsb-utvikling.slack.com/archives/CM9H2N39U/p1729836807225179
Wrapped the logic in parentheses.
N/A
Run locally. Go to `http://localhost:3000/components/phone-number-input`. Scroll down to the fourth and last example. See that the inputs has labels "Base" and "Variant" instead of the default values.

Buggy label logic in phone number input

---

.changeset/chilly-cows-whisper.md
packages/spor-react/src/theme/components/divider.ts

The dashed divider looked weird and not like in figma.
Updated the styling for the dashed divider to look like the divider in figma.
The rounded corners where not included this time.
Only visual changes.
Look at the dividers with `variant="dashed"`
|    <img width="863" alt="image" src="https://github.com/user-attachments/assets/4f73f468-6b5d-40bc-822f-23b969e25e84">    |    <img width="813" alt="image" src="https://github.com/user-attachments/assets/296dd6d8-b898-45f4-8d3f-b3e2ff6ab63f">   |

Dashed divider like figma

---

.changeset/chilly-chefs-matter.md
packages/spor-react/src/theme/components/alert-expandable.ts
packages/spor-react/src/theme/components/alert-service.ts

expandable alerts and service alerts had stying that had to be updated
changed styling on each state to match the styling in figma. 
Screenshots show the alerts with focus and hover state activated before and after changes
|<img width="435" alt="image" src="https://github.com/user-attachments/assets/a60ce8ea-e31e-4bc1-8bd5-cc19074885c8">|<img width="513" alt="image" src="https://github.com/user-attachments/assets/70b36734-e57f-44e9-a55a-ed4dc3759f9e">|

Update states for expandable Alerts and service alerts

---

.changeset/green-suns-exercise.md
packages/spor-react/src/loader/Skeleton.tsx

Skeletons component, even if it is handle as not focusable element, had not aria attributes to  introduce the component to screen readers
It may looks overkill since the component is not focusable but to ensure all screenreader avoid consider this element adding these attributes will help
Run application locally and check http://localhost:3000/components/skeletons

Add aria attributes to introduce the skeleotons component

---

.changeset/khaki-falcons-drum.md
packages/spor-react/src/button/Button.tsx
packages/spor-react/src/modal/FullScreenDrawer.tsx

One primary reason is that styles defined via SpaceProps were not being applied to the Button component, leading to confusion and unexpected behavior for developers using the component.
The Button component has been updated to remove SpaceProps from its ButtonProps interface. This change eliminates direct support for spacing-related properties (e.g., margin, padding).
try to add `margin` or `padding` on Button component. Make sure space props does not appear and is not supported.

Remove SpaceProps from ButtonProps

---

.circleci/config.yml
.github/workflows/release.yml

During a release, we are publishing the new version of spor to npm. While this is happening the circleci pipeline is trying to pull this version from npm. If the github action has not yet published to npm the circleci pipeline will fail
Alter the github action to trigger our circleci pipeline after publishing to npm

Alter github action to trigger circleci after publishing to npm

---

.github/workflows/release.yml

github action was unable to find circleci project
follow circleci guide and add target_slug to github action

Add target slug to github action so circleci can identify the project

---

apps/docs/app/root/layout/SiteSettings.tsx

The settings modal of the documentation website had problems in minor size screen (see video below)
Add a fixed width to modal element 
run application locally and reduce the size of the screen to a mobile size then test the settings menu item
before 
https://github.com/user-attachments/assets/aeaefec0-8714-4d26-8a9f-d7d02bef2b8a
after
https://github.com/user-attachments/assets/beec1ccd-71f2-4583-81f5-fdc9f9da1f97

Fix resizing in small screen for site settings menu

---

.changeset/lemon-scissors-return.md
package-lock.json
packages/spor-react/src/input/CardSelect.tsx
packages/spor-react/src/theme/components/card-select.ts
packages/spor-react/src/theme/utils/ghost-utils.ts

The design of cardSelect was updated and needed adjustment to be compliant
Fix the code that render the components with new design
Run application locally and check the cardSelect http://localhost:3000/components/card-select
Previous design
Figma design
Updated design

Adapt component CardSelect to new design

---

.github/dependabot.yml

Every two weeks did not work. Changing to monthly, as weekly will be way too often.

Change dependabot to monthly

---

.changeset/nasty-apples-search.md
packages/spor-react/src/input/ChoiceChip.tsx
packages/spor-react/src/layout/RadioCard.tsx

(Ref: https://nsb-utvikling.slack.com/archives/C069ZRN84JY/p1730723548773359)
Setting `isDisabled=false` on RadioCard sets the RadioCard state to disabled. 
Fixed isDisabled behaviour in RadioCard.
Also fixed a similar issue in ChoiceChip as I noticed it didn't have correct style when using isDisabled.
Check that using `isDisabled` and `disabled` works correctly for RadioCard and ChoiceChip.
| ![Screenshot 2024-12-12 at 12 31 19](https://github.com/user-attachments/assets/5f6f3f9c-09dd-48ff-b5a1-b5d72f310363) | ![Screenshot 2024-12-12 at 12 30 37](https://github.com/user-attachments/assets/4eefe18f-0a27-44ba-93fd-4b03f1dfd0b7) |

Fix isDisabled in RadioCard and ChoiceChip

---

apps/studio/sanity.config.ts

In order to update the chakra 3 version documentation and keep the previous version at the same time we needed to split workspaces in two
Use the second available dataset copy the content from the production to the new one and add a new workspace to handle the new dataset content

Fix double workspaces for chackra 3 og 2 med spor 1 og 2

---

.changeset/stupid-sloths-clap.md
packages/spor-react/src/alert/ClosableAlert.tsx

ClosableAlert has BoxProps in its props, but they were not used.
Sent the boxProps to the BaseAlert the same way ExpandableAlert did.
Add some boxProps to a ClosableAlert. Should now be applied to the component.
|    <img width="972" alt="image" src="https://github.com/user-attachments/assets/fcb94820-9b87-4922-ad08-7e227db5f087" />    |    <img width="986" alt="image" src="https://github.com/user-attachments/assets/341a5563-8376-4feb-a4a9-1fb091b51bc1" />   |

Add box props to ClosableAlert

---

.changeset/loud-plants-protect.md
packages/spor-react/src/util/externals.tsx

To support SSR, we should avoid using `useMediaQuery`, as the server cannot detect the user's screen size. A better alternative is to rely solely on CSS.
Add a deprecated doc comment.

deprecate useMediaQuery

---

.changeset/kind-impalas-hammer.md
package-lock.json
packages/spor-react/src/theme/components/alert-service.ts

There was a need to make the two variants of the ServiceAlert component have identical colors, so that the color does not suddenly change when changing view for cases where the views have different ServiceAlert variants
Change the colors of the "global-deviation" to be equal the "service" variant
Start the application manually, then check the last variant of the component showcased under: http://localhost:3000/components/alert 
|<img width="1028" alt="image" src="https://github.com/user-attachments/assets/5f71c46f-97b4-4769-9881-449f1d0ef0d7" />|<img width="1028" alt="image" src="https://github.com/user-attachments/assets/0491aabb-70bc-4641-99bb-69e48fd64681" />|

Change color of ServiceAlert global-deviation variant

---

.changeset/gentle-hats-complain.md
apps/docs/app/features/portable-text/code-block/CodeBlock.tsx
package-lock.json
packages/spor-react/src/button/Button.tsx

We removed support for spacing props, but seems to be a little too early. 
I've put props back. We will look closer at it in Spor 12.

Button: Update to support more props

---

.changeset/poor-dingos-shop.md
packages/spor-react/src/input/CountryCodeSelect.tsx
packages/spor-react/src/input/PhoneNumberInput.tsx

We notice that we have some issues with `optimize deps` in our main-frontend repository, and it seems to be linked to this component:
```
The file does not exist at "/root/project/node_modules/.vite/deps/chunk-3GG4VEIX.js?v=6513bab6" which is in the optimize deps directory. The dependency might be incompatible with the dep optimizer. Try adding it to `optimizeDeps.exclude`.
```
In a server-rendered environment, this is not needed since we're code-splitting indirectly, as we're already splitting up the bundle and sending the JavaScript that is needed, and nothing more.
Removed the use of React.lazy
If no packages, only docs have been changed:
Go here: …

remove suspense from phonenumber input, due to issues in SSR enviorment

---

apps/docs/app/routes/_base.resources.illustration-library/route.tsx
apps/docs/package.json

/guides/introduction does not work currently due to a mistake made when migrating over to singel fetch
Resolved the error
Run it locally, and access http://localhost:3000/guides/introduction

fix illustration page

---

package-lock.json
packages/spor-react/src/typography/Badge.tsx

Not much to fix here
Updated Sanity to show colorPalette instead of colorScheme
|<img width="514" alt="image" src="https://github.com/user-attachments/assets/ccc4b1f1-6f7f-4252-8fc0-73b5a427961f" />|<img width="518" alt="image" src="https://github.com/user-attachments/assets/7af10859-9acb-4c9f-bb2a-f0d6942bc69e" />|

update documentation - Badge

---

.changeset/dull-pears-sort.md
apps/docs/app/root/layout/SiteHeader.tsx
apps/docs/app/root/layout/SiteSettings.tsx
packages/spor-react/src/color-mode/color-mode.tsx
packages/spor-react/src/input/Textarea.tsx
packages/spor-react/src/theme/recipes/input.ts
packages/spor-react/src/theme/recipes/textarea.ts
packages/spor-react/src/theme/slot-recipes/anatomy.ts
packages/spor-react/src/theme/slot-recipes/field.ts

Textarea updated with same styles as input. 
Textarea recieves the same style as Input. Also added the same syntax with Field, which makes it possible to add errorText, helperText and label with the component.
(Also added a temporary solution for dark/light mode in the header)
| <img width="564" alt="image" src="https://github.com/user-attachments/assets/4acbd188-f4a7-4a60-8add-830210947da5" /> | <img …

Chakra 3: Update Textarea

---

.changeset/yellow-rabbits-care.md
packages/spor-react/src/input/Input.tsx

The form label was dancing around before the page got javascript
Added css to set it to the correct position
|        |       |

Fixed hydration error that caused the label to 'dance' around

---

.changeset/empty-rabbits-shout.md
packages/spor-design-tokens/tokens/color/vy-digital.json

Color for disabled text is different on [spor.vy.no](http://spor.vy.no/) (40% black) than on figma (30% black). Figma is correct. 
te disabled color value in vy-digital.json to 30% black
- [x ] It is possible to use the keyboard to reach your changes
- [ x] It is possible to enlarge the text 400% without losing functionality
- [ x] It works on both mobile and desktop
- [ x] It works in both Chrome, Safari and Firefox
- [ x] It works with VoiceOver
- [ x] There are no errors in aXe / SiteImprove-plugins / Wave
- [ x] Sanity documentation has been / will be updated (if neccessary)

Fix: Update disabled color value in vy-digital.json

---

.changeset/selfish-buckets-fail.md
packages/spor-react/src/loader/Skeleton.tsx
packages/spor-react/src/theme/recipes/skeleton.ts

Upgrading to chakra 3 breaks default styling applied, so created a recipe.

Chore: Upgrade Skeleton to Chakra v3

---

.changeset/popular-berries-suffer.md
apps/docs/app/features/brand-switcher/BrandSwitcher.tsx
package-lock.json
packages/spor-react/package.json
packages/spor-react/src/provider/SporProvider.tsx
packages/spor-react/src/theme/brand.ts
packages/spor-react/src/theme/index.ts
packages/spor-react/src/theme/semantic-tokens/index.ts
packages/spor-react/src/theme/slot-recipes/anatomy.ts

Previous implementation of switching between themes breaks with chakra 3. 
Use of deepmerge with theme does not work anymore.
Create multiple systems to toggle between.

Fix: Switching themes with Chakra 3

---

.changeset/pretty-kings-drive.md
packages/spor-react/src/typography/Heading.tsx

setting manual id on Heading didn't work, even with autoId=false. This turned out to be because the logic for setting the id was wrong.
Fixed the logic
See that you can set the id and it is used, instead of the auto-generated one.

ExternalId is always ignored

---

.github/workflows/slack-notify.yml

The old one was using a free trial of zapper and would stop working soon. 
Use slack webhooks and github actions to create a new one.

Feature: New release Slackbot with webhooks and github actions

---

packages/spor-react/src/toast/toast.tsx

Was set to 200 000 ms for testing purposes
Set to 6000. Which is correct

Fix(Toast): correct duration

---

.changeset/smooth-dolls-turn.md
packages/spor-react/src/alert/ServiceAlert.tsx

A minor variation of design in service message was asked to remove the icon if there were more than one message 
Add a condition to remove the icon if notifications were more than 1
run documentation locally and check http://localhost:3000/components/alert at the bottom of the page there is the service alert try to pass notification prop to 1 or higher

Remove icon service alert if more than one message

---

packages/spor-react/src/theme/recipes/button.ts
packages/spor-react/src/theme/recipes/input.ts
packages/spor-react/src/theme/recipes/pressable-card.ts
packages/spor-react/src/theme/slot-recipes/accordion.ts
packages/spor-react/src/theme/slot-recipes/breadcrumb.ts
packages/spor-react/src/theme/slot-recipes/pagination.ts
packages/spor-react/src/theme/slot-recipes/radio-card.ts
packages/spor-react/src/theme/utils/input-utils.ts

...coreBackground("active") gave the wrong color and affected many components
Changed to backgroundColor: "core.surface.active",

Fixed backgroundColor on several components

---

.changeset/spicy-ears-explode.md
packages/spor-react/src/input/PhoneNumberInput.tsx

Not being able to set specific `name`-attributes for the country-code and national-number inputs is a bit problematic when using [Conform](https://conform.guide/).
Conform expects a certain naming convention (e.g. `phoneNumber.countryCode`) which is currently not possible to achieve as the PhoneNumberInput adds a suffix to the name, i.e. `${name}-country-code` and `${name}-phone-number`.
This results in relying on hidden inputs and other hacky solutions when using PhoneNumberInput with Conform.
Updated the name prop to
```
name?:
| string
| { countryCode: string; nationalNumber: string; };
```
If given a string it works the same way as previously, if given an object no `-country-code`/`-phone-number` suffix is added.
Check that the PhoneNumberInput works as expected when given a string or …

Update PhoneNumberInput name prop

---

.changeset/eight-dingos-sit.md
packages/spor-react/src/theme/slot-recipes/card-select.ts

Minor fix for a missing bold text in label of ghost variant and correct padding for the card
Made the changes on the style recipe, the missing function onClose of button is changed on sanity documentation
run application locally and check http://localhost:3000/components/card-select

Fix for bold in ghost and padding

---

apps/docs/app/routes/_base.resources.icon-library/SearchBar.tsx
apps/docs/app/routes/_base.resources.icon-library/SearchResults.tsx
apps/docs/app/routes/_base.resources.icon-library/route.tsx
apps/docs/app/routes/_base.resources.illustration-library/route.tsx
apps/docs/package.json
packages/spor-react/src/button/Button.tsx
packages/spor-react/src/button/IconButton.tsx
packages/spor-react/src/input/NativeSelect.tsx
pnpm-lock.yaml

The route for download the icon library does not work properly
Fix necessary components and enable the download
run application locally and check http://localhost:3000/resources/icon-library

Fix icon library and illustration library route

---

apps/docs/package.json
pnpm-lock.yaml

We missed spor-icon package for the docs remix app, this lead to a fail when user tried to download icons or all icons zip
add missin library

Add missing spor-icon package

---

.changeset/brown-buckets-hug.md
packages/spor-react/src/theme/recipes/button.ts

we missed outline stroke width for focus state
add styling

Fix outline width for button in primary and tertiary

---

.changeset/tender-balloons-sin.md
packages/spor-react/src/theme/slot-recipes/floating-action-button.ts

Stoke outilne problem with the FloatinActionButton
Add necessary style

Fix floating button stroke

---

.changeset/eight-ads-flash.md
packages/spor-react/src/linjetag/LineIcon.tsx

LineIcon missed aria-label and since it communicate significant information it is important to give this information to VO
Add a required label prop to compoennt
run application locally and check http://localhost:3000

Fix linetag

---

.changeset/nervous-pots-wave.md
packages/spor-react/src/layout/RadioCard.tsx

The value attribute isn't specified for the hidden `<input type="radio">` in `<RadioCard>` which results in the inputs defaulting to "on" for the value. This is problematic when trying to send the selected `<RadioCard>` value in a form (especially when using Conform).
Updated RadioCard input to include value attribute.
Example of submitted formData when "Buss" is selected (see console log):
| --- | --- |
| ![Screenshot 2025-04-22 at 12 36 40](https://github.com/user-attachments/assets/9a8196a2-fb37-4c50-bed2-23e157a25beb) | ![Screenshot 2025-04-22 at 12 36 54](https://github.com/user-attachments/assets/1e2babb6-c06e-4104-a4c3-b448ff6d24d7) |

Update RadioCard to include input value

---

packages/spor-react/src/loader/ColorSpinner.tsx

Colorspinner showed twice as loader in iconButton and probably in all places where used
Remove double writing of component
run application locally and check http://localhost:3000/components/icon-button the loader should show once

Fix double colorspinner loader

---

apps/docs/app/root.tsx
apps/docs/app/root/layout/SiteHeader.tsx

The previous version, Spor 11, needed also the chance to navigate to the main version
Add the select drop down to choose between the version in documentation
Run application locally and check http://localhost:3000

Add domain handling and version selection to navigation components

---

.changeset/stupid-snails-call.md
packages/spor-icon-react/bin/componentTemplate.ts
packages/spor-icon-react/bin/generate.ts

Remix gives
useContext returned `undefined`. Seems you forgot to wrap component within <ChakraProvider />
Wrap icons with <ClientOnly>

fix(Icons): Error when rendering with remix 

---

.changeset/afraid-carrots-smoke.md
apps/docs/app/root.tsx
package.json
packages/eslint-config/index.mjs
packages/spor-design-tokens/package.json
packages/spor-react/package.json
packages/spor-react/src/provider/SporProvider.tsx
packages/spor-react/src/theme/index.ts
pnpm-lock.yaml

- Removed unused `patch-package` from `spor-design-tokens`.
- Refactored theme setup in `spor-react` for type support and extending theme support.
- Updated `eslint-config` to better support React 17+ adding jsx runtime rules.

build: Refactored theme setup in `spor-react` for type support and extending theme support + update eslint 

---

apps/docs/app/routes/_base.resources.icon-library.all-icons[.zip]/route.tsx
apps/docs/app/routes/_base.resources.icon-library/route.tsx

The all-icons.zip was. not found on server
The name of the file exported was not matching the file was downloaded

Change name for downlodable zip file

---

.changeset/few-buttons-compete.md
packages/spor-react/src/button/Button.tsx
packages/spor-react/src/link/TextLink.tsx
packages/spor-react/src/theme/recipes/button.ts

Components did not support asChild attribute, because they either used react fragment between children and element, or because they rendered multiple children
clone element and some react magic

fix: asChild support for `Button` and `TextLink`

---

.changeset/twenty-tools-return.md
packages/spor-react/src/button/Button.tsx

Set a fixed maxsize (maxwidth 8)

fix(Button): Scaling of loading indicator

---

.changeset/happy-coats-allow.md
apps/docs/app/root/layout/SearchDocs/SearchDocsInput.tsx
packages/spor-react/src/alert/AlertIcon.tsx
packages/spor-react/src/button/CloseButton.tsx
packages/spor-react/src/button/IconButton.tsx
packages/spor-react/src/datepicker/CalendarTriggerButton.tsx
packages/spor-react/src/input/Combobox.tsx
packages/spor-react/src/input/ListBox.tsx
packages/spor-react/src/input/NumericStepper.tsx
packages/spor-react/src/input/Switch.tsx
packages/spor-react/src/linjetag/LineIcon.tsx
packages/spor-react/src/loader/ProgressLoader.tsx
packages/spor-react/src/progress-indicator/ProgressIndicator.tsx

Checked all uses of forwardref and fixed ref. 
Removed forwardref for combobox and listbox, as they take input ref as prop which is passed.

fix(spor-react): Issues with unused ref in forwardref functions

---

.changeset/many-apples-tie.md
packages/spor-react/src/input/PhoneNumberInput.tsx

An error occured from a previous merge. PhoneNumberInput was "split in half"
Wrapped CountryCodeSelect and Input in Box and added Flex values. It was not possible to put the flex values directly on CountryCodeSelect and Input. 
http://localhost:3000/components/phone-number-input
|![image](https://github.com/user-attachments/assets/74b75b62-507c-4db0-881f-c1e13cfc0680)|![image](https://github.com/user-attachments/assets/f65e3148-21d6-4b75-9410-c3849353ecf3)|

Fix phoneNumberInput

---

.changeset/two-ants-invent.md
package.json
pnpm-lock.yaml

The package `lottie-web` does not work properly with SSR on newer versions of node (node > 20). This is because node has made changes in their navigator api so it is now available on the server as well. This causes a check `lottie-web` has to determine what context it is in to not work as intended, leading to a `document is undefined` error. 
Link to relevant github issue: https://github.com/airbnb/lottie-web/issues/2739
Create a patch version of the `lottie-web` package with `pnpm patch`. In the patched version we update the check to see if the document is present instead of the navigator.

Patch lottie-web to work with newer versions of node

---

.changeset/perfect-nails-rule.md
packages/spor-react/src/input/CountryCodeSelect.tsx
packages/spor-react/src/input/PhoneNumberInput.tsx
packages/spor-react/src/theme/slot-recipes/select.ts

1.  onValueChange did not work and returned |Object object]
2. focus was set on select content when using tab to navigate. Therefore select item was not reachable. 
1. moved {...props} higher up in the code under Input
2. added the necessary styling
Go to http://localhost:3000/components/phone-number-input and check the example code
| 1. Before | 1. After |
|<img width="363" alt="image" src="https://github.com/user-attachments/assets/4c78945d-e814-4ce1-8aea-0c53967366e2" />|<img width="381" alt="image" src="https://github.com/user-attachments/assets/739b187c-c5d3-4745-9385-073547ebf1b3" />|
| 2. Before | 2. After |
|<img …

fix [object object], and UU problem

---

packages/spor-react/src/theme/slot-recipes/listbox.ts

Tere was no outline when tabbing down the list
added an outline on focus
|<img width="1029" height="383" alt="image" src="https://github.com/user-attachments/assets/2cbaa788-9aa3-4184-9f2a-f9b321a8d526" />|<img width="1062" height="427" alt="image" src="https://github.com/user-attachments/assets/3d3b5231-659a-4ad6-bb55-1f8994603b30" />|

fix outline on focus

---

.changeset/famous-cherries-guess.md
packages/spor-react/src/typography/Text.tsx

Previously, the <Text /> component in spor-react defaulted to the sm textStyle unless a variant was provided. This made it difficult for users to override only fontSize or lineHeight without unintentionally resetting both to the default.
Refactored the prop resolution logic for <Text /> to allow users to specify fontSize and/or lineHeight independently. The component now only applies the sm default when neither is provided, and respects user-supplied values otherwise.
Closes #1763

feat(Text): add fontSize and lineHeight support for <Text/>

---

.changeset/yellow-tables-jam.md
packages/spor-react/src/dialog/Drawer.tsx

Attempt at closing #1812
I have used react-swipeable like in Spor v1. Made the swipe duration a bit shorter though. 
I have tested locally in one of our apps and the functionality seems to be like in v1 - swiping works with touch and not with mouse
https://github.com/user-attachments/assets/c8195ac0-a034-4959-9242-8721311a8f4a

Add swiping to close drawer

---

.changeset/slick-peaches-itch.md
packages/spor-react/src/linjetag/TravelTag.tsx

Was not working. Not sure when it broke.
Add it back
---
|     <img width="384" height="147" alt="image" src="https://github.com/user-attachments/assets/ff6c048d-9a6a-4790-9bfc-f1363469c66c" />   |   <img width="384" height="147" alt="image" src="https://github.com/user-attachments/assets/25532de6-9459-4b5d-ae0d-9dccf368c367" />    |

feat(spor-react): add backgroundColor prop to TravelTag component

---

.changeset/tricky-squids-tickle.md
packages/spor-react/src/dialog/Drawer.tsx
packages/spor-react/src/dialog/types.ts

Previously, title was string. Makes more sense that is is children. Consistent with Modal etc.
Change type from string to child of DrawerFullScreenHeader component
---
---

fix(Drawer): change title prop to children in DrawerFullScreenHeader

---

.changeset/cold-chairs-flash.md
packages/spor-react/src/theme/slot-recipes/datepicker.ts

Happend when datepicker is forced above input field with withPortal =false
Add min-height: fit-content 

fix(Datepicker): set min height to ensure calendar popover fits content

---

.changeset/calm-numbers-relax.md
packages/spor-react/src/datepicker/DatePicker.tsx
packages/spor-react/src/datepicker/StyledField.tsx
packages/spor-react/src/theme/slot-recipes/datepicker.ts

Vi trenger en måte å bruke datepicker litt annerledes i lavpriskalenderen. Så det må være mulig å hindre kalendermodalen og å styre om den skal ha fokusringen.
- La til isActive prop, slik at den kan styres eksternt.
- La til noCalendar prop, slik at vi kan forhindre kalenderen fra å poppe opp

feat(datepicker): Added isActive and noCalendar prop to datePicker

---

.changeset/modern-jeans-refuse.md
packages/spor-icon-react-native/bin/generate.ts

The React Native icons need support for dark mode. Therefore the default value should be a semantic color token.
Changed to a semantic color token. 
---
---
Will behave as the icon next to "Utviklerverktøy":
https://github.com/user-attachments/assets/1875507a-9f95-4b9b-9946-9c71e3176440

Semantic color token for icons

---

.changeset/chatty-drinks-prove.md
packages/spor-react/src/datepicker/DatePicker.tsx
packages/spor-react/src/datepicker/StyledField.tsx
packages/spor-react/src/theme/slot-recipes/datepicker.ts

We need a way to set onClick for the new lowfare calendar
Also, changed the hover outline color to be the focus color when hovering in isActive mode (to make it clear that you actually "toggeled" if enabled by click

chore(datepicker): exposed onClick & changed hover style to be focus color when isActive=true

---

.changeset/beige-ears-deny.md
packages/spor-react/src/theme/slot-recipes/dialog.ts

Closes #1919
---
|    <img width="714" height="466" alt="image" src="https://github.com/user-attachments/assets/fc71b5ae-78f5-4f68-ada9-634a11bb8d64" />    |    <img width="714" height="466" alt="image" src="https://github.com/user-attachments/assets/7b6b7360-0c47-4f8d-9d5a-9b291de8854a" />   |

fix(dialog): Adjust height for modal cover for better scroll handling

---

.changeset/every-walls-serve.md
packages/spor-react/src/alert/ServiceAlert.tsx
packages/spor-react/src/datepicker/CalendarHeader.tsx
packages/spor-react/src/datepicker/DateField.tsx
packages/spor-react/src/input/Field.tsx
packages/spor-react/src/input/ListBox.tsx
packages/spor-react/src/stepper/StepperStep.tsx
packages/spor-react/src/theme/slot-recipes/accordion.ts
packages/spor-react/src/theme/slot-recipes/alert-service.ts
packages/spor-react/src/theme/slot-recipes/choice-chip.ts
packages/spor-react/src/theme/slot-recipes/datepicker.ts

Closes #1929
|     <img width="238" height="103" alt="image" src="https://github.com/user-attachments/assets/7c474335-6e10-42ba-a20b-b2cdc85ca281" />   |    <img width="272" height="181" alt="image" src="https://github.com/user-attachments/assets/fd5a23e1-950c-4ade-a7df-51a6b5a92185" />   |

fix(UI): Correct padding and overflow issue with ServiceAlert on phone screens. Also adjust some stylings that are inconsistent with figma. 

---

.changeset/twenty-sites-swim.md
packages/spor-react/src/button/ResponsiveButton.tsx
packages/spor-react/src/dialog/Drawer.tsx
packages/spor-react/src/theme/slot-recipes/drawer.ts

Closes #1935
Rewrite layout logic. Make buttons responsive, so only icons on mobile. As in Figma.
---
|   <img width="396" height="698" alt="image" src="https://github.com/user-attachments/assets/e7f7fcc7-bb94-4efc-b2ac-c208de33c467" />     |      <img width="396" height="698" alt="image" src="https://github.com/user-attachments/assets/8cd94e74-2b98-4331-86ee-5d20727149de" /> |

fix(FullScreenDrawer): Button placements and overflow in header

---

.changeset/light-melons-strive.md
packages/spor-react/src/input/Switch.tsx

Closes #1927
Conditionally render label
---
|      <img width="371" height="77" alt="image" src="https://github.com/user-attachments/assets/fd228f0c-0541-4f01-8944-d92cec2a837c" />  | <img width="266" height="77" alt="image" src="https://github.com/user-attachments/assets/a2f28aef-3014-401b-9447-8b08861d1e1e" /> |

fix(Switch): Prevent empty space when switch has no label
