internal/plop-templates/react-native/README.md.hbs
internal/plop-templates/react/README.md.hbs
internal/plop-templates/typescript/README.md.hbs
internal/plopfile.mjs
packages/config/README.md
packages/spor-button-react/README.md
packages/spor-i18n-react/README.md
packages/spor-i18n-react/src/index.tsx
packages/spor-input-react/README.md
packages/spor-logo-react/README.md
packages/spor-react/README.md
packages/spor-theme-react/README.md
packages/tsconfig/README.md

This request documents all components added so far, as well as adds a neat template for new packages
- Add basic readme template to all new packages
- Add a basic readme to the spor-react package
- Add readmes to all packages so far

Add proper readmes

---

.gitignore
apps/docs/pages/test.tsx
internal/plop-templates/react-native/tsconfig.json.hbs
internal/plop-templates/react/package.json.hbs
internal/plop-templates/react/tsconfig.json.hbs
internal/plop-templates/typescript/tsconfig.json.hbs
internal/plopfile.mjs
package-lock.json
packages/spor-button-react/package.json
packages/spor-button-react/src/ButtonGroup.tsx
packages/spor-button-react/src/ButtonSpinner.tsx
packages/spor-button-react/src/IconButton.tsx
packages/spor-button-react/tsconfig.json
packages/spor-i18n-react/package.json
packages/spor-i18n-react/tsconfig.json
packages/spor-input-react/package.json
packages/spor-input-react/src/FormControl.tsx
packages/spor-input-react/src/InputElement.tsx
packages/spor-input-react/src/PasswordInput.tsx
packages/spor-input-react/tsconfig.json
packages/spor-logo-react/package.json
packages/spor-logo-react/tsconfig.json
packages/spor-react/package.json
packages/spor-react/tsconfig.json
packages/spor-theme-react/package.json
packages/spor-theme-react/tsconfig.json
packages/tsconfig/react-library.json
packages/tsconfig/react-native-library.json

This pull request adds a build and dev scripts that are supposed to be published at some point.
With this in place, we can start preparing for creating beta releases for people to try out!
- Add basic tsconfig file for all templates
- Add basic tsconfig to all existing packages
- Ignore dist folders
- Add basic react native tsconfig
- Add React as a specified import in all packages
- Set @leile/lobo-t as a hard dependency for spor-i18n-react
- Set module resolution to 'node'
- Add build step to a single package
- Add the rootDir option to all tsconfigs
- Add build scripts to all packages
- Update template files for react build step

Add build step

---

.changeset/little-rice-float.md
apps/docs/package.json
packages/spor-theme-react/package.json
packages/spor-theme-react/src/components/form.ts

This pull request fixes a bug with a missing dependency, and a bug with the input field implementation, giving it the wrong height.

Fixing onboarding bugs

---

apps/docs/next.config.js
apps/docs/package.json
package-lock.json

This PR makes the docs app work with transpiled code.

Remove transpilation step, as its no longer needed

---

.changeset/shiny-flowers-enjoy.md

Forgot to add it in the last PR

Add changeset for the password input change

---

.changeset/poor-elephants-scream.md
internal/plop-templates/react-native/package.json.hbs
internal/plop-templates/react/package.json.hbs
internal/plop-templates/typescript/package.json.hbs
packages/spor-button-react/package.json
packages/spor-i18n-react/package.json
packages/spor-input-react/package.json
packages/spor-logo-react/package.json
packages/spor-react/package.json
packages/spor-theme-react/package.json

- Add home page and repository info to all plop templates
- Add repository and homepage metadata to all existing package.jsons

add metadata to package jsons

---

.changeset/smooth-plums-confess.md
packages/spor-input-react/src/Checkbox.tsx
packages/spor-input-react/src/CheckboxGroup.tsx
packages/spor-input-react/src/index.tsx
packages/spor-theme-react/src/components/checkbox.ts
packages/spor-theme-react/src/components/index.ts
packages/spor-theme-react/src/components/input.ts
packages/spor-theme-react/src/components/textarea.ts

This PR adds a Checkbox component 🙌🏻

Add checkboxes

---

.changeset/fluffy-dragons-brake.md
packages/spor-input-react/README.md
packages/spor-input-react/src/CheckboxGroup.tsx
packages/spor-input-react/src/Radio.tsx
packages/spor-input-react/src/RadioGroup.tsx
packages/spor-input-react/src/index.tsx
packages/spor-theme-react/src/components/index.ts
packages/spor-theme-react/src/components/radio.ts

- Add radio component
- Add stack to CheckboxGroup
- Add docs for Checkbox components as well

add radiobuttons

---

.changeset/twenty-cups-call.md
packages/spor-input-react/README.md
packages/spor-input-react/src/FormLabel.tsx
packages/spor-input-react/src/Switch.tsx
packages/spor-input-react/src/index.tsx
packages/spor-theme-react/src/components/index.ts
packages/spor-theme-react/src/components/switch.ts

- Add FormLabel component
- Add Switch component
- Add new components to the top of the list

Add Switch and FormLabel components

---

.changeset/smooth-plums-confess.md
packages/spor-input-react/src/Switch.tsx

- Downgrade theme change to a patch
- Make the outline variant work as expected

fix goof up

---

.changeset/empty-bobcats-swim.md
apps/docs/pages/test.tsx
packages/spor-input-react/README.md
packages/spor-input-react/src/ChoiceChip.tsx
packages/spor-input-react/src/index.tsx
packages/spor-theme-react/src/components/choice-chip.ts
packages/spor-theme-react/src/components/index.ts

add choice chips

---

.changeset/calm-phones-swim.md
packages/spor-input-react/README.md
packages/spor-input-react/src/Select.tsx
packages/spor-input-react/src/index.tsx
packages/spor-theme-react/src/components/form.ts
packages/spor-theme-react/src/components/index.ts
packages/spor-theme-react/src/components/select.ts

simple dropdown

---

.changeset/dull-singers-smell.md
packages/config/eslint-preset.js
packages/spor-layout-react/README.md
packages/spor-layout-react/package.json
packages/spor-layout-react/src/index.tsx
packages/spor-layout-react/tsconfig.json
packages/spor-react/package.json
packages/spor-react/src/index.tsx

We're not adding anything to Chakra's defaults here, just re-exporting a supported subset

Add a basic layout package

---

.changeset/big-berries-sniff.md
internal/plop-templates/react/package.json.hbs
package-lock.json
packages/config/eslint-preset.js
packages/spor-react/src/index.tsx
packages/spor-typography-react/README.md
packages/spor-typography-react/package.json
packages/spor-typography-react/src/index.tsx
packages/spor-typography-react/tsconfig.json

- Fix bug in react plop template
- Add typography package

add typography package

---

.changeset/real-rules-shave.md
.changeset/red-emus-help.md
package-lock.json
packages/spor-button-react/src/Button.tsx
packages/spor-theme-react/src/components/button.ts

- Update package lock file
- Forward refs to buttons
- Fix focus styling on safari

Add some button fixes

---

.changeset/selfish-clouds-tease.md
packages/spor-layout-react/README.md
packages/spor-layout-react/src/index.tsx

In this PR I've added the following layout components from charka UI:
* HStack
* VStack,
* Spacer
* GridItem

Added more layout components

---

.changeset/spicy-seas-sparkle.md
package-lock.json
packages/spor-react/package.json
packages/spor-react/src/index.tsx

This PR exposes `tokens` from the `@vygruppen/spor-react` package.

Expose tokens

---

.changeset/silver-dryers-sleep.md
packages/spor-theme-react/src/foundations/index.ts
packages/spor-theme-react/src/foundations/shadows.ts

This adds our box shadows to the Chakra UI theme.

Add shadows as usable theme tokens

---

apps/docs/app/features/routes/index/ActionLinks.tsx
apps/docs/app/features/routes/index/Footer.tsx
apps/docs/app/features/routes/index/HeroSection.tsx

Did some pair programming with Ella, and ended up changing a few bits and bobs
- Removed unneccessary props
- Remove unused aria-hidden prop
- Add a few tiny tweaks to the footer

changing the landing page

---

.changeset/violet-mugs-swim.md
apps/docs/app/features/routes/index/ActionLinks.tsx
package-lock.json
packages/spor-theme-react/src/components/card.ts

- Fix broken design
- Update package-lock
- Implement interactivity for elevated mode
- Add interactive cards of outlined and filled
- Implement interactive states on filled and outlined cards as well
- Add support for disabled styling

Add support for interactive cards

---

.changeset/friendly-melons-laugh.md
package-lock.json
packages/config/eslint-preset.js
packages/spor-modal-react/README.md
packages/spor-modal-react/package.json
packages/spor-modal-react/src/Modal.tsx
packages/spor-modal-react/src/ModalHeader.tsx
packages/spor-modal-react/src/index.tsx
packages/spor-modal-react/tsconfig.json
packages/spor-react/package.json
packages/spor-react/src/index.tsx
packages/spor-theme-react/package.json
packages/spor-theme-react/src/components/index.ts
packages/spor-theme-react/src/components/modal.ts
packages/spor-theme-react/src/foundations/colors.ts

- Add boilerplate for new modal package
- Add modal package

Add modal package

---

apps/docs/.env.example
apps/docs/README.md
apps/docs/app/features/user-preferences/UserPreferencesContext.tsx
apps/docs/app/root.tsx
apps/docs/app/routes/actions/user-preferences.tsx
apps/docs/app/utils/userPreferences.server.ts
apps/docs/package.json
package-lock.json

This pull request implements the user preferences pane, which are saved to a cookie.
These changes adds an additional step to the development setup, so make sure to read the README and follow the new instructions after this is merged.

Add user preferences with persistence

---

.changeset/wise-ads-cheer.md
apps/docs/app/features/routes/index/ActionLinks.tsx
apps/docs/app/features/routes/index/Footer.tsx
apps/docs/app/features/routes/index/HeroSection.tsx
apps/docs/app/features/site-header/UserPreferenceSwitcher.tsx
packages/spor-icon-react/bin/componentTemplate.ts
packages/spor-icon-react/bin/generate.ts

- Fix an issue where icons had their viewBox removed
- Migrate to new way of using icons

more icons fixes

---

.changeset/curvy-beans-reflect.md
.changeset/hungry-hornets-thank.md
apps/docs/app/routes/ressurser.tsx
packages/spor-theme-react/src/components/badge.ts
packages/spor-theme-react/src/components/code.ts
packages/spor-typography-react/src/Badge.tsx
packages/spor-typography-react/src/Code.tsx

- Add support for all color schemes and sizes for badges and code
- Update the way we use badges in the docs

implement sizes for badges

---

apps/docs/app/features/error-boundary/RootErrorBoundary.tsx
apps/docs/app/features/routes/ressurser/design-tokens/ColorTokens.tsx
apps/docs/package.json
package-lock.json

This pull request adds documentation for color tokens.

color tokens

---

apps/docs/app/features/routes/ressurser/design-tokens/BreakpointTokens.tsx
apps/docs/app/features/routes/ressurser/design-tokens/ZIndexTokens.tsx

Lagt til nye endringer i breakpoints også refaktoring av kode om array map i zIndex.

Breakpoint tokens

---

.changeset/spicy-pants-boil.md
apps/docs/app/features/routes/ressurser/design-tokens/BreakpointTokens.tsx
package-lock.json
packages/spor-theme-react/src/components/table.ts

Fix a screw up I did while trying to fix @EllaKrossen 's working code 😬 😄 
Also, found a bug with tables not rendering correctly with the new border tokens.

Fix breakpoint tokens

---

package.json
turbo.json

Upgrade turborepo

---

apps/docs/app/features/content-menu/ContentMenu.tsx
apps/docs/app/features/content-menu/MenuItem.tsx
apps/docs/app/features/content-menu/SearchResults.tsx

This pull request makes the content menu open to the correct submenu whenever we navigate.

Make the content menu location aware

---

.changeset/spotty-cougars-perform.md
apps/docs/app/features/component-playground/EditableProp.tsx
apps/docs/app/features/content-menu/menuStructure.ts
apps/docs/app/routes/kom-i-gang/index.tsx
apps/docs/app/routes/komponenter/lenker.tsx
apps/docs/package.json
package-lock.json
packages/config/eslint-preset.js
packages/spor-link-react/README.md
packages/spor-link-react/package.json
packages/spor-link-react/src/Link.tsx
packages/spor-link-react/src/index.tsx
packages/spor-link-react/tsconfig.json
packages/spor-react/package.json
packages/spor-react/src/index.tsx
packages/spor-theme-react/src/components/index.ts
packages/spor-theme-react/src/components/link.ts

This PR adds a neat new `<Link />` component.
Also, PR # 100! Yaaaas 
- Add spor-link-react package
- Add link docs
- Tweak how choice chips are rendered
- Upgrade framer-motion to remove annoying warning
- Change the link to the link docs
- Use the Spor divider, not the Chakra one

add link package

---

apps/docs/app/features/interactive-code/LivePreview.tsx

- Center components in the playground

Center components in the playground

---

apps/docs/app/features/routes/ressurser/ikoner/SearchFilterContext.tsx
apps/docs/app/features/routes/ressurser/ikoner/SearchResults.tsx
package-lock.json

- Always include icons that are not fill or outline
- Refactor the search for clarity
- Optimize the icon filtering
- Tweak the colors of each card

Tweak the icons page

---

.changeset/strong-zebras-wink.md
apps/docs/app/routes/komponenter/stepper.tsx
packages/spor-popover-react/src/SimplePopover.tsx
packages/spor-stepper-react/package.json
packages/spor-stepper-react/src/Stepper.tsx
packages/spor-stepper-react/src/StepperStep.tsx
packages/spor-theme-react/src/components/stepper.ts

Add a mobile way to show all steps

---

.changeset/purple-spies-yell.md
apps/docs/app/features/content-menu/menuStructure.ts
apps/docs/app/routes/komponenter/fab.tsx
package-lock.json
packages/spor-button-react/src/FloatingActionButton.tsx
packages/spor-button-react/src/index.tsx
packages/spor-theme-react/src/components/fab.ts
packages/spor-theme-react/src/components/index.ts

- Add floating action styles
- Improve the docs for FABs
- Change the API slightly

Add floating action button component

---

.changeset/big-maps-begin.md
packages/spor-design-tokens/config.json

This pull request fixes an issue where the react native design tokens weren't turned into the correct format

Add missing plugin

---

apps/docs/app/features/content-menu/menuStructure.ts
apps/docs/app/routes/komponenter/oversikt.tsx
apps/docs/package-lock.json
apps/studio/config/resolveProductionUrl.ts

This fix makes Sanity's live preview mode work as intended.
Also, it fixes a tiny bug in the way we show components

Fix live preview

---

.changeset/silver-walls-refuse.md
apps/docs/app/features/content-menu/ContentMenu.tsx
apps/docs/app/features/content-menu/MenuItem.tsx
apps/docs/app/features/content-menu/SearchInput.tsx
apps/docs/app/features/content-menu/SearchResults.tsx
apps/docs/app/features/content-menu/SearchableContentMenu.tsx
packages/spor-logo-react/src/VyLogo.tsx

This PR makes it possible to navigate the sidebar menu with arrow keys
- Change the Vy logo slightly
- Improve the menu navigation

go to single item in search

---

apps/docs/app/features/routes/index/ActionLinks.tsx
apps/docs/app/features/routes/ressurser/ikoner/SearchResults.tsx
packages/spor-theme-react/src/components/button.ts

- Endre farge på sirkel for "Tokens" på landingssiden.
- Fikse states på download og copy knapp i ikonbiblioteket

Fix states in icon 

---

apps/docs/app/features/content-menu/MenuItem.tsx
apps/docs/app/features/content-menu/menuStructure.ts
apps/docs/app/features/routes/index/ActionLinks.tsx
apps/docs/app/features/site-header/SiteHeader.tsx
apps/docs/app/features/site-header/SiteNavigation.tsx

This PR links the profile page to Snøhetta's Vy profile page

Link the profile page to our actual profile page

---

.changeset/breezy-news-teach.md
packages/spor-tab-react/src/Tabs.tsx
packages/spor-tab-react/src/index.tsx

This pull request adds the correct types to the Tabs component

Set the correct Tabs types

---

.changeset/spotty-ties-thank.md
packages/spor-tab-react/src/Tabs.tsx

- Make variant and size optional props
- Add some code hints

make some props optional

---

apps/docs/app/features/content-menu/menuStructure.ts
apps/docs/app/features/routes/index/HeroSection.tsx

This pull request adds the contribute page to available pages, and corrects the section it was placed under.
The content itself is in Sanity.

Publish the bidra section

---

README.md
apps/docs/app/routes/studio.tsx
apps/studio/README.md

This PR deploys the Sanity Studio to the cloud

To the cloud

---

.changeset/dull-knives-invite.md
apps/docs/app/features/content-menu/GlobalSearchInput.tsx
apps/docs/app/features/content-menu/SearchInput.tsx
apps/docs/app/features/content-menu/SearchableContentMenu.tsx
package-lock.json
packages/spor-input-react/src/SearchInput.tsx
packages/spor-input-react/src/index.tsx

Legge til mulighet for å bruke kryss på høyre side for å slette innholdet du allerede har lagt inn i søkefelt

Add search input component

---

apps/docs/app/features/content-menu/MenuItem.tsx
apps/docs/app/features/linkable-heading/LinkableHeading.tsx
apps/docs/app/features/portable-text/PortableText.tsx
apps/docs/app/features/routes/ressurser/ikoner/SearchResults.tsx
apps/docs/app/features/table-of-contents/TableOfContents.tsx
apps/docs/app/routes/ressurser/design-tokens.tsx

Did a bit of tuning with Per Øyvind to make things look good!

Tune spacing of portable text components

---

.changeset/blue-windows-repair.md
apps/docs/app/features/portable-text/PortableText.tsx
packages/spor-link-react/src/TextLink.tsx

- Make links forward references
- Make tel: and mailto: links (among others) work as they should in Sanity

add support for phone and mail links

---

.changeset/three-panthers-hear.md
packages/config/eslint-preset.js
packages/spor-provider-react/README.md
packages/spor-provider-react/package.json
packages/spor-provider-react/src/SporProvider.tsx
packages/spor-provider-react/src/index.tsx
packages/spor-provider-react/tsconfig.json
packages/spor-react/package.json
packages/spor-react/src/index.tsx

Also, make the language prop of the SporProvider optional

Move SporProvider to its own package

---

apps/docs/app/features/portable-text/PortableText.tsx

Setting the aspect ratio helps with stuff moving around the page

Calculate the aspect ratio

---

.changeset/wet-ghosts-talk.md
apps/SporRnDemo/package-lock.json
package-lock.json
packages/spor-theme-react-native/src/foundations/colors.tsx

This change makes all palette colors available as autocompletable values for React Native.

Make palette colors available in typescript types as well

---

.changeset/fuzzy-ligers-kneel.md
packages/spor-theme-react/src/components/textarea.ts

Ref issue https://github.com/nsbno/spor/issues/231 for description.

Issue 231 Textarea box-shadow fix

---

README.md

Legge til mer info om det å lage en ny pakke

---

.changeset/calm-starfishes-march.md
.changeset/dull-files-rest.md
packages/spor-card-react/src/Card.tsx
packages/spor-theme-react-native/src/components/card.tsx
packages/spor-theme-react/src/components/card.ts
packages/spor-theme-react/src/utils/box-shadow-utils.ts

Legg til colored variant
Bytte ut farger på focus, hover og active

Add colored variant

---

apps/docs/app/features/routes/index/ActionLinks.tsx
apps/docs/app/features/routes/ressurser/design-tokens/ColorTokens.tsx
apps/docs/app/features/routes/ressurser/ikoner/SearchResults.tsx
package-lock.json

- Upgrade all usages of cards
- Update package-lock to upgrade all packages

use new cards internally

---

packages/spor-icon-react/README.md

Rettet importeringen til 'Fill' ikke 'Filled', og satt størrelsen til en mer relevant størrelse. La også til hvordan ikonet brukes, men dette er kanskje overflødig. :)

Rettet importeringen

---

.changeset/weak-dancers-compete.md
package-lock.json
packages/spor-accordion-react-native/src/Expandable.tsx
packages/spor-theme-react-native/src/components/expandable.tsx

Fikser mangler for styling for Expandable komponenten. 
https://user-images.githubusercontent.com/24417944/179207795-50445939-6a0f-48a6-b4d5-481e3043b0a9.mp4

💄 Fix margin accordion

---

packages/spor-message-box-react-native/README.md

📝  oppdatert README.md til MessageBox

---

packages/spor-message-box-react-native/src/MessageBox.tsx

|Før|Etter|
|--|--|
|<img width="489" alt="Screenshot 2022-07-21 at 13 34 59" src="https://user-images.githubusercontent.com/44139426/180204796-53e47573-5e07-4374-86e0-d53d8ae866e2.png">|<img width="489" alt="Screenshot 2022-07-21 at 13 35 09" src="https://user-images.githubusercontent.com/44139426/180204860-703575c4-53fc-4906-9540-d60e482ffbf4.png">|

🐛 Fikser bug som gjorde at tekst la seg over lukkeknapp i MessageBox

---

.changeset/shaggy-tigers-remember.md
apps/rn-demo/app/App.tsx
package-lock.json
packages/spor-card-react-native/src/Card.tsx

Endret `Card` slik at det har riktig bredde også når det er flere kort horisontalt.
`Card` er også refaktorert slik at vi unngår duplisert kode.

Forbedringer Card

---

.changeset/spotty-scissors-wonder.md
apps/rn-demo/app/App.tsx
packages/spor-card-react-native/src/Card.tsx

Endre kort slik at de fungerer som forventet i både `Box`,`ScrollView` og `Box flexDirection="Row"`

Tweak card layout oppførsel

---

.changeset/nasty-tips-flash.md
packages/spor-card-react-native/src/Card.tsx

Når en card er pressable ønsker vi å sende med en accessibilityLabel 
legger til en prop som sendes in til pressable komponenten.

Legge til accessibilityLabel som prop i Card

---

.changeset/pretty-plums-look.md
packages/spor-layout-react-native/src/Box.tsx

Legger til ViewProp i Box komponenten for react native slik at man kan sende in style: StyleProp<ViewStyle>

Legge til viewProp

---

.changeset/grumpy-cheetahs-walk.md
package-lock.json
packages/spor-card-react-native/src/Card.tsx

Bruke BoxProps fra @vygruppen/spor-layout-react-native isteden for fra restyle.

Ta i bruk BoxProps fra spor layout 

---

.changeset/fast-cobras-protect.md
packages/spor-theme-react-native/src/components/card.tsx
packages/spor-theme-react/src/components/card.ts

Det var noen forskjeller i fargene mellom React og React Native versjonene av kort.

Tweak the border colors of cards

---

.changeset/wicked-forks-design.md
packages/spor-card-react-native/src/Card.tsx
packages/spor-message-box-react-native/src/MessageBox.tsx

| før | etter |
|----|------|
| <img width="492" alt="Screen Shot 2022-08-02 at 10 51 29" src="https://user-images.githubusercontent.com/42439472/182334217-1459dc20-b8fb-459f-8582-f6bb5970861a.png">|<img width="536" alt="Screen Shot 2022-08-02 at 10 50 41" src="https://user-images.githubusercontent.com/42439472/182334241-9759668f-8baf-4c02-9a51-64c391a97e44.png">|

center button with text

---

.changeset/little-carrots-wash.md
packages/spor-accordion-react-native/src/Expandable.tsx
packages/spor-accordion-react-native/src/ExpandableItem.tsx
packages/spor-accordion-react-native/src/utils.tsx

https://user-images.githubusercontent.com/7909864/182585126-bd2a6b61-f0f5-4a03-806f-a96c1334cfca.mp4

♻️ Legger til animasjon for når Expandable expandes.

---

.changeset/tall-feet-sparkle.md
packages/spor-theme-react-native/src/components/card.tsx
packages/spor-theme-react/src/components/card.ts

Denne endringen endrer bakgrunnsfargen fra steel til platinum på disablede kort

Endre bakgrunnsfarge på disablede kort

---

.changeset/funny-knives-shout.md
packages/spor-card-react-native/src/Card.tsx

legge til disabled som en props til Card

Legge til Disabled prop i card

---

.changeset/silver-coins-protect.md
package-lock.json
packages/spor-icon-react-native/package.json

Salgsappen fungerer ikke med Spor versjon 0.3.20
feilmelding i appen er : 
Endre fra å ha react-native-svg som dependency til devDependency.

Endre slik at react-native-svg blir en devDependency isteden for dependency. 

---

package-lock.json
packages/spor-button-react-native/package-lock.json

Oppdatere package-lock.json slik at det ikke er merge conflict.

oppdatere package-lock.json i button og i spor

---

.changeset/sixty-apes-brush.md
packages/spor-react-native/src/index.tsx

Endrer path for linjetag så de får samme format som alle de andre exportene

Change export path

---

.changeset/odd-hairs-care.md
packages/spor-theme-react-native/src/components/card.tsx

Endre borderRadius for Card  når size er liten så den får 12 i borderRadius.

💄Border radius for sm card skal sm

---

.changeset/eighty-toys-laugh.md
apps/docs/remix.config.js
packages/spor-theme-react-native/package.json

- Remove unnecessary config
- Mark the theme package as side-effecty

Småfikser etter treeshaking

---

apps/rn-demo/app/App.tsx

fjerne kort og legge tilbake text i demo appen

---

.changeset/two-gifts-smile.md
package-lock.json
packages/spor-loader-react/package.json
packages/spor-loader-react/src/Lottie.tsx

Usikker på hvor dette problemet kom fra, men det ser ut til at react-lottie har hatt en breaking change i en patch eller så.
Denne fiksen får loaderne våre til å funke igjen!

Lottie-problem

---

.changeset/wet-vans-yell.md
package-lock.json
packages/spor-theme-react/src/components/travel-tag.ts

Fix a bug where linjetags would break on small screens

---

.changeset/curvy-worms-flow.md
packages/spor-theme-react/src/components/line-icon.ts

Endre border-radius på LineIcon og InfoTag

---

.changeset/afraid-houses-tan.md
.changeset/chatty-stingrays-happen.md
package-lock.json
packages/spor-button-react/src/Button.tsx

Oppdatert nye versjon av spor pakke og fikse paddingTop i isLoading knappen.

Fikse lasteanimasjon som ikke er sentrert i visning

---

README.md
packages/spor-react/README.md

Give some outdated readmes some love!

Improve the readmes somewhat

---

apps/docs/app/routes/__base/ressurser/illustrasjoner.tsx

Denne PRen introduserer en enkelt implementert illustrasjonsside. Den lenkes ikke til noe sted enda, så lar den bare merges med en gang – men gi meg gjerne tilbakemeldinger på implementasjonen!

Lag en enkel illustrasjonsside

---

apps/studio/sanity.config.ts

Denne endringen fikser en bug der man ikke får opprettet nye artikler.

Fiks Sanity bug

---

.changeset/afraid-onions-fetch.md
package-lock.json
packages/spor-theme-react/src/components/skeleton.ts

Denne endringen fikser en bug i skeletons som dukket opp etter rewriten til Chakra 2.

Fiks bug med skeletons

---

apps/docs/app/routes/__base/ressurser/ikoner/$category/$fileName.ts
apps/docs/app/utils/icons.server.ts

Denne endringen fikser en bug der nedlastning av ikoner ikke funket i prod.

Fiks nedlastning av ikoner

---

apps/docs/app/features/routes/ressurser/design-tokens/ColorTokens.tsx

Ingen vits i å ha noe ingen bruker.

Fjern "kopier fargekode"-knapp

---

internal/plop-templates/react/package.json.hbs
package-lock.json
packages/config/vitest.config.ts
packages/config/vitest.setup.ts
packages/spor-accordion-react/package.json
packages/spor-accordion-react/src/Accordion.test.tsx
packages/spor-accordion-react/tsconfig.json

Denne pull requesten setter opp [vitest](https://vitest.dev/) for testing av koden vår.
Vitest er en litt bedre versjon av Jest, og er et anerkjent måte å teste kode på. Jeg la også til vitest-axe, som lar oss automatisere noen enkle UU-tester.

Setup vitest

---

apps/docs/app/features/content-menu/ContentMenu.tsx
apps/docs/app/features/interactive-code/LiveError.tsx
apps/docs/app/features/linkable-heading/LinkableHeading.tsx
apps/docs/app/features/portable-text/PortableText.tsx
apps/studio/schemas/objects/imageWithCaption.tsx

Denne endringen gjør noen små, men viktige, endringer for hvordan artikler på dokumentasjonssiden burde se ut.

docs: Tweake design av artikkelsider

---

apps/studio/package.json
apps/studio/sanity.config.ts
package-lock.json

Nedsiden med å leve i beta-land er at ting endrer seg ofte. Derfor er det fint å oppgradere til nyeste versjon ofte!
Denne endringen oppgraderer til nyeste versjon, som fikser en god del bugs, og som flytter oss fra beta til release candidate.

Oppgradere Sanity Studio til nyeste versjon

---

.changeset/empty-trains-tap.md
.gitignore
packages/spor-theme-react/src/components/datepicker.ts

https://github.com/nsbno/spor/issues/514

Change hover state styling for datecell (react only)

---

.changeset/serious-buses-rule.md
apps/docs/app/features/routes/ressurser/design-tokens/ColorTokens.tsx
packages/spor-theme-react/src/components/accordion.ts
packages/spor-theme-react/src/components/button.ts
packages/spor-theme-react/src/components/datepicker.ts
packages/spor-theme-react/src/components/input.ts
packages/spor-theme-react/src/components/switch.ts
packages/spor-theme-react/src/components/tabs.ts

Fixes #515 
Inkluderer ikke tidsvelger. Finnes ikke ennå, ref #451 ?

Fix outline color for datepicker, accordion, switch, input and tabs

---

.changeset/tough-gorillas-look.md
packages/spor-button-react/src/Button.tsx
packages/spor-datepicker-react/src/CalendarGrid.tsx
packages/spor-datepicker-react/src/CalendarHeader.tsx
packages/spor-datepicker-react/src/CalendarTriggerButton.tsx
packages/spor-datepicker-react/src/utils.ts
packages/spor-i18n-react/README.md
packages/spor-i18n-react/src/index.tsx
packages/spor-input-react/src/PasswordInput.tsx
packages/spor-input-react/src/SearchInput.tsx
packages/spor-link-react/src/TextLink.tsx
packages/spor-media-controller-react/src/JumpButton.tsx
packages/spor-media-controller-react/src/PlayPauseButton.tsx
packages/spor-media-controller-react/src/SkipButton.tsx
packages/spor-popover-react/src/PopoverWizardBody.tsx
packages/spor-stepper-react/src/Stepper.tsx

Denne endringen legger til to ting:
- Støtte for nynorsk
- En ny utility for å få typesikre tekster – `createTexts`.

Forbedre i18n

---

apps/studio/package.json
apps/studio/sanity.config.ts
package-lock.json

Endelig er Sanity 3 ute av beta - hurra for brukeropplevelsen til redaktørene våre!

Oppdater Sanity til v3 (general availability)

---

.changeset/beige-deers-end.md
.changeset/strong-houses-admire.md
package-lock.json
packages/spor-datepicker-react/package.json
packages/spor-datepicker-react/src/DateField.tsx
packages/spor-datepicker-react/src/DatePicker.tsx
packages/spor-datepicker-react/src/DateRangePicker.tsx
packages/spor-datepicker-react/src/DateTimeSegment.tsx
packages/spor-datepicker-react/src/StyledField.tsx
packages/spor-datepicker-react/src/TimeField.tsx
packages/spor-datepicker-react/src/TimePicker.test.tsx
packages/spor-datepicker-react/src/TimePicker.tsx
packages/spor-datepicker-react/src/index.tsx
packages/spor-datepicker-react/src/utils.ts
packages/spor-theme-react/src/components/button.ts
packages/spor-theme-react/src/components/datepicker.ts

Denne pull requesten legger til en TimePicker komponent for React.
APIet er ganske rett frem:
```tsx
<TimePicker 
value={time}
defaultValue={defaultTime}
onChange={setTime}
label="Avreise"
stepGranularity={30}
name="avreise
isDisabled={true}
/>
```
Alle props er optional. Den er også basert på `useTimeField` fra react-aria, slik at alt skal fungere godt med skjermlesere.
Her er en demo av docs-siden:
Fixes #451

Timepicker!

---

.changeset/fuzzy-items-boil.md
packages/spor-theme-react/src/components/media-controller-button.ts

Endre fargene på media-controllers

---

.changeset/thick-queens-suffer.md
packages/spor-theme-react/src/components/skeleton.ts

Denne endringen tweaker litt på fargene på skeletons slik at de fungerer bedre – både på lys og mørk bakgrunn.
Closes #564

Endre fargene for skeletons

---

apps/docs/app/features/content-menu/GlobalSearchInput.tsx
apps/docs/app/features/content-menu/SearchResults.tsx
apps/docs/app/features/content-menu/SearchableContentMenu.tsx
apps/docs/app/features/interactive-code/InteractiveCode.tsx
apps/docs/app/features/interactive-code/LiveEditor.tsx
apps/docs/app/features/layouts/docs-layout/footer/Footer.tsx
apps/docs/app/features/site-header/SiteNavigation.tsx

Selv om vi kanskje er "feilfrie" i forhold til kravene til universell utforming, betyr ikke det at det ikke finnes forbedringsrom.
Jeg fant en rekke smågreier som kunne forbedres ved relativt lite kode, blant annet å merke alle navigasjonsmenyer med riktige roller, sette riktig aria-live på noen regioner og lage noen bedre aria-labels her og der.

Forbedre voice-over opplevelsen

---

.changeset/tasty-mice-smile.md
packages/spor-input-react/src/CardSelect.tsx
packages/spor-theme-react/src/components/card-select.ts

Denne PRen legger til noen manglende states på card selects.

Legg til states på card selects

---

apps/docs/app/features/routes/ressurser/design-tokens/ColorTokens.tsx

Outline-fargene i dokumentasjonen var utdatert. Denne endringen oppdaterer dem!

Endre outline farger

---

.changeset/tame-pots-mix.md
package-lock.json
packages/spor-input-react/src/CheckboxGroup.tsx

Denne PRen fikser en bug der horisontale checkbox groups fikk litt feil marginer.
Fixes #622

Fiks checkbox marginer

---

apps/docs/package.json
package-lock.json
packages/spor-datepicker-react/package.json
packages/spor-input-react/package.json
packages/spor-input-react/src/FormErrorMessage.tsx
packages/spor-loader-react/package.json

Oppgraderer react-aria til 3.23.0 i de pakkene som bruker dette
Skal visst muliggjøre bruk av `DatePicker` og `CardSelect` i React strict mode

Oppgrader react-aria

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
README.md

Denne PRen:
- legger til code owners
- legger til en PR template
- forbedrer issue templatene våre
- legger til en ny CodeSandbox lenke i bug report templaten og i READMEen.

Tweak GitHub greier

---

.changeset/twenty-adults-lay.md
packages/spor-loader/src/index.ts

Henger sammen med denne PRensom legger til en ny loader med lysere farger:
* https://github.com/nsbno/spor/pull/676
Vi må legge til den nye loaderen som en export i `index.ts`.

Legg til ny loader i index.ts

---

.changeset/lemon-avocados-rest.md
packages/spor-react/src/index.tsx
packages/spor-react/src/transition/index.ts

Trengte å kunne kollapse noe uten å bruke en accordion
Eksporter alle transition-komponentene til Chakra. [Les mer om dem her](https://chakra-ui.com/docs/components/transitions/usage)

Re-export some useful transition components

---

.changeset/flat-geckos-speak.md
packages/spor-react/src/theme/components/tabs.ts

Tabs wrappet
Nå tabs ikke wrappe.

Fix issue with tabs wrapping

---

.changeset/fuzzy-donuts-poke.md

Vi manglet et changeset på en endring.
Legg til nevnte changeset.

Legg til changeset

---

.changeset/odd-waves-shake.md
packages/spor-react/src/theme/components/datepicker.ts

- period color change from osloGrey -> dimGrey

Changed color to meet contrast minimum requriement

---

packages/spor-react/src/loader/SkeletonText.tsx

Legg til mulighet for å endre høyden til SkeletonText-komponent
Legg til skeletonHeight i SkeletonTextProps

Legg til skeletonHeight

---

packages/spor-icon-elm/generate.js

Need to be able to pass attributes (such as Aria, etc.) 
Changed IconConfig

Change IconConfig to take in attributes list

---

packages/spor-react/src/alert/ExpandableAlert.tsx

Main har sluttet å bygge - ser ut til at en liten komma har sneket seg inn å gjort litt ugagn

remove trailing comma

---

.changeset/three-weeks-tease.md
packages/spor-react/src/button/IconButton.tsx

Variant "floating" mangler fra IconButton komponenten. 
Lagt til alternativ "floating" for feltet variant i IconButton.

Add floating variant to IconButton.tsx

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

We want to use English as a standard language for Spor (at least here on GitHub).
Translate all templates to English.

Translate the github templates

---

.changeset/flat-avocados-notice.md
apps/studio/sanity.config.ts
packages/spor-react/src/breadcrumb/Breadcrumb.tsx
packages/spor-react/src/breadcrumb/index.tsx
packages/spor-react/src/index.tsx
packages/spor-react/src/theme/components/breadcrumb.ts
packages/spor-react/src/theme/components/index.ts

We didn't have breadcrumbs implemented, and we now had two teams implementing them in parallel.
Basically just tweak a bit on the built in components from Chakra UI, and add some tiny styling tweaks. Here's how the documentation will look.

Add breadcrumbs

---

.changeset/swift-carrots-reflect.md
packages/spor-react/src/theme/components/accordion.ts
packages/spor-react/src/theme/components/index.ts
packages/spor-react/src/theme/components/list.ts

Missed font family style
Fixed

Add font family to list and accordion button

---

.changeset/short-dryers-sleep.md
packages/spor-react/src/theme/components/breadcrumb.ts

Needed to update colors for lightmode and darkmode
Trengte å oppdatere farger for steg 2,3,4
Oppdatert farger i følge figma for både lightmode og darkmode.

Darkmode breadcrubs

---

.changeset/silver-jars-perform.md
packages/spor-react/src/theme/components/breadcrumb.ts

bug in focus
fixed bug for focus

Fix breadcrumbs focus

---

packages/spor-icon-elm/generate.js
packages/spor-icon-elm/package-lock.json

TLDR; We want better UU on our website, and discovered Icons with missing "text labels" / aria label. 
When using Icons and sending attributes with Icon.withAttributes such as [Aria.hidden True], we discovered that the Icons had missing text labels (with the use of the Accessibility check in FireFox). This resolves in bad UU for our users. 
The function withAttributes was made, and attributes was set in IconConfig, but this was never used in the generate function. The solution was to actually use attributes in the function `generateBasicCase`, by appending this list to lists in Fill and Stroke.

🐛 Actually use the attributes variable from iconConfig

---

apps/docs/app/root/layout/Footer.tsx
apps/docs/app/root/layout/RootLayout.tsx
apps/docs/app/root/layout/SkipToContent.tsx
apps/docs/package.json

dUUgnad.no – a great grass roots effort to help create a more inclusive society – has sent us a few embarassing a11y issues on our website. 
Please see #880 , #881 , #882 
Fix each of these issues. Thanks a ton [https://www.duugnad.no](https://duugnad.no)!

Fix a11y issues – thanks duugnad.no! 🎉

---

.changeset/kind-taxis-cough.md
packages/spor-react/src/tab/Tabs.tsx
packages/spor-react/src/theme/components/tabs.ts

needed to update name of tab
changed from default to base

Change default to base for tabs

---

.changeset/silver-items-train.md
packages/spor-react/src/theme/components/card.ts

card does not have dark mode support
added dark mode support to card

dark mode: card

---

.changeset/wise-worms-complain.md
packages/spor-react/src/button/FloatingActionButton.tsx
packages/spor-react/src/theme/components/fab.ts

fab needed to be viable for dark mode.
changed all variation to be dark mode viable.
light -> base
green -> accent
dark -> brand

Darkmode fab

---

.changeset/famous-foxes-wash.md
packages/spor-react/src/modal/Drawer.tsx
packages/spor-react/src/theme/components/close-button.ts
packages/spor-react/src/theme/components/drawer.ts
packages/spor-react/src/theme/components/modal.ts

drawer did not have dark mode support
added dark mode support, but removed gradient styling in the component, not sure if that is ok

Darkmode drawer

---

.changeset/eight-queens-wave.md
packages/spor-react/src/datepicker/DatePicker.tsx
packages/spor-react/src/datepicker/DateRangePicker.tsx
packages/spor-react/src/theme/components/datepicker.ts

We had forgotten to add some of the main new styles to datepickers.
Add them :)

Fix some visual regressions for the datepicker

---

.changeset/wicked-goats-bake.md
packages/spor-react/src/theme/components/list.ts

There were some issues with the fonts on the lists.
Add the correct list styling
Fixes #910

Improve list styling

---

.github/CODEOWNERS

The codeowners file didn't work as expected
Fix the formatting and add @ithen15

Make codeowners work again

---

.changeset/fuzzy-clocks-begin.md
packages/spor-react/src/button/Button.tsx
packages/spor-react/src/theme/components/button.ts

buttons where not updated with the newest changes for colors
updated with the new colors from figma

Button darkmode update

---

apps/docs/package.json

needed new version
Updated package.json version

Push new version of doc app

---

.changeset/funny-singers-pay.md
packages/spor-react/src/index.tsx
packages/spor-react/src/util/externals.tsx

There were some methods and utility components that were useful for our applications.
Expose a few new components.
Fixes #948

Expose some chakra methods

---

.changeset/tasty-owls-flow.md
packages/spor-react/src/theme/components/listbox.ts

The color of the listbox should be white and not mint. 
Changed color.

change color of listbox

---

.changeset/cold-knives-sparkle.md
apps/docs/app/features/portable-text/PortableText.tsx
apps/studio/schemas/objects/bestPracticePanel.tsx
packages/spor-react/src/input/InfoSelect.tsx
packages/spor-react/src/provider/SporProvider.tsx
packages/spor-react/src/stepper/StepperStep.tsx
packages/spor-react/src/theme/components/info-select.ts
packages/spor-react/src/theme/components/listbox.ts
packages/spor-react/src/theme/index.ts
packages/spor-react/src/theme/utils/background-utils.ts
packages/spor-react/src/theme/utils/border-utils.ts
packages/spor-react/src/theme/utils/types.ts

Because the other one was closed while I was working on some changes to address feedback in #896  🙈 
Not sure if this addresses the feedback in it's entirety. I'm adding it here, so its visible.

Further refinements info select

---

.changeset/cyan-tables-kick.md
packages/spor-react/src/index.tsx
packages/spor-react/src/progress-indicator/ProgressDot.tsx
packages/spor-react/src/progress-indicator/ProgressIndicator.tsx
packages/spor-react/src/progress-indicator/index.tsx
packages/spor-react/src/theme/components/index.ts
packages/spor-react/src/theme/components/progress-indicator.ts

Fordi vi skal ha ny komponent 🖌️  Jeg er litt usikker på om jeg er helt i mål.
🪄 
Jeg foreslår å spinne opp lokalt og lime denne inn i lekegrinden:
```typescript
<Card w="400px" h="400px" display="flex" flexDirection="column" justifyContent="center" alignItems="center" gap={2} m={2}>
<Text as="h1" variant="2xl">Velkommen til ny Hjemskjerm</Text>
<Text variant="md">En dynamisk og tilpasset hjemskjerm i appen som gir deg øyeblikkelig tilgang til dine mest brukte funksjoner, personlig tilpasset informasjon, og smarte forslag for å gjøre hverdagen din enklere og mer organisert.</Text>
<Flex justifyContent="center" alignItems="center" gap={1}>
<Button
variant="secondary"
size="md"
>
Lukk
</Button>
<ProgressIndicator numberOfSteps={3} activeStep={2} />
<Button variant="primary" size="md">
Les …
```

ProgressIndicator: New component

---

.changeset/brave-teachers-dance.md
packages/spor-react/src/theme/components/card-select.ts

was an bug with background color
fixed it for darkmode

cardselect:darkmode quickfix

---

.changeset/flat-owls-breathe.md
packages/spor-react/src/theme/components/card-select.ts

removed some code by mistake last merge
added it back in

cardselect restored lost code

---

.changeset/itchy-cycles-nail.md
packages/spor-react/src/theme/components/button.ts
packages/spor-react/src/theme/components/fab.ts

Change disabled styles for icons

---

.changeset/shaggy-schools-serve.md
apps/studio/sanity.config.ts
packages/spor-react/src/input/ChoiceChip.tsx
packages/spor-react/src/theme/components/choice-chip.ts
packages/spor-react/src/theme/utils/background-utils.ts
packages/spor-react/src/theme/utils/border-utils.ts
packages/spor-react/src/theme/utils/text-utils.ts

The Choice Chips has the old design and styling and needs to be updated
need to update and new utils for completing this task.
Also had to change the use of variation, because it was used in an outdated way.

962 update design and styling of choice chips

---

.changeset/polite-moose-doubt.md
packages/spor-react/src/theme/components/accordion.ts
packages/spor-react/src/theme/utils/background-utils.ts

Wrong styling of hover state of the Floating version og Accordions, and missing outline on the dark-mode.
Wrong variation names.
implemented utility functions
updated variation names

927 accordion bug with floating state

---

.changeset/warm-planes-brake.md
packages/spor-react/src/theme/components/checkbox.ts
packages/spor-react/src/theme/components/radio.ts
packages/spor-react/src/theme/utils/background-utils.ts

Update styles of Checkbox and RadioButtons.
Implement dark mode as it somehow wasn't implemented before.
Closes: #959 
https://github.com/nsbno/spor/assets/3692249/c78b06d8-7fe8-47d0-afcc-ec1a248cb32c
https://github.com/nsbno/spor/assets/3692249/35430d8c-ad2d-4424-95e0-ff7207229ee7

feat: Update Checkbox and RadioButton styles, and add dark mode

---

package-lock.json
package.json

Necessary update for windows.
Update prebuild based on issue:
https://github.com/nsbno/spor/issues/1051

Update Rimraf and prebuild script to be able to run on Windows #1051

---

.changeset/breezy-kangaroos-heal.md
.changeset/wild-seas-doubt.md
apps/docs/app/features/brand-switcher/BrandSwitcher.tsx
apps/docs/app/root/layout/Footer.tsx
apps/docs/app/root/layout/SiteHeader.tsx
apps/docs/app/root/layout/SiteSettings.tsx
apps/docs/app/routes/_index/HeroSection.tsx
apps/docs/app/routes/_index/route.tsx
apps/docs/package.json
packages/spor-design-tokens/tokens/color/cargonet.json
packages/spor-design-tokens/tokens/color/vy-digital.json
packages/spor-react/src/input/CardSelect.tsx
packages/spor-react/src/theme/components/card-select.ts
packages/spor-react/src/theme/components/card.ts
packages/spor-react/src/theme/components/link.ts
packages/spor-react/src/theme/index.ts

This PR has a bunch of minor changes, see the PR review for details

Color tweaks and design geeks

---

.github/CODEOWNERS

Team Kanaler is the team in charge of Spor changes
Add the `@nsbno/team-kanaler` team to the CODEOWNERS file.

Add team kanaler to the CODEOWNERS file

---

.changeset/stupid-beers-drive.md
packages/spor-design-tokens/CHANGELOG.md
packages/spor-design-tokens/tokens/color/vy-digital.json

Change of color because of dark mode.
Change whiteAlpha from 400 to 300.

Update outline value

---

.changeset/fast-toys-begin.md
packages/spor-design-tokens/tokens/color/cargonet.json
packages/spor-design-tokens/tokens/color/vy-digital.json

Added "highlight" to themes in design tokens.
Issue: https://github.com/nsbno/spor/issues/1086

Add text highlight

---

.changeset/calm-wolves-invite.md
packages/spor-react/CHANGELOG.md
packages/spor-react/package.json

Revert "Version Packages"

---

apps/docs/package.json

bump to new version

---

apps/docs/package.json

change version back to 22

---

.changeset/hip-walls-tan.md
apps/docs/package.json
packages/spor-react/src/layout/PressableCard.tsx
packages/spor-react/src/layout/RadioCard.tsx
packages/spor-react/src/layout/RadioCardGroup.tsx

Some properties were lacking the proper documentation. This is now updated.
Also bumped the version for the docs.

Update property docs for cards and bump version

---

.changeset/heavy-horses-sparkle.md
packages/spor-react/src/layout/RadioCard.tsx
packages/spor-react/src/layout/RadioCardGroup.tsx

Wrapping RadioCard in other elements inside RadioCardGroup made the functionality of the radio group not work. 
Now the RadioCardGroup will "ignore" other elements inside the function.

Buypass any element that is not RadioCard in RadioCardGroup

---

.changeset/small-chicken-matter.md
packages/spor-react/src/alert/AlertIcon.tsx
packages/spor-react/src/alert/BaseAlert.tsx
packages/spor-react/src/alert/ClosableAlert.tsx
packages/spor-react/src/alert/ExpandableAlert.tsx
packages/spor-react/src/alert/StaticAlert.tsx
packages/spor-react/src/theme/components/alert.ts

Solves desktop for https://github.com/nsbno/spor/issues/999
Adds possibility for title on StaticAlert and ClosableAlert.
Some minor bugfixes with color on darkmode.

Add title to Alert (StaticAlert and ClosableAlert)

---

.changeset/shy-worms-look.md
apps/docs/package.json
packages/spor-react/src/theme/components/pressable-card.ts
packages/spor-react/src/theme/utils/base-utils.ts

Some values were not correct for pressable card
https://github.com/nsbno/spor/assets/42611957/75be84d7-2697-44de-b274-e056af0d2d38

Fix bugs on PressableCard

---

.changeset/beige-dolphins-float.md
package-lock.json
packages/spor-react/src/layout/RadioCard.tsx
packages/spor-react/src/layout/RadioCardGroup.tsx

onChange is added and error on focus with arrows is fixed

RadioCard: add onChange and fix bug

---

.changeset/orange-coats-taste.md
apps/docs/package.json
packages/spor-react/src/layout/RadioCard.tsx
packages/spor-react/src/layout/RadioCardGroup.tsx
packages/spor-react/src/theme/components/radio-card.ts

RadioCard needed an upgrade for accessibility.
Now supports arrows, space for choice and tabbing in and out of the radiogroup.

Radio card accessibility

---

.changeset/lovely-candles-float.md
packages/spor-react/src/layout/RadioCard.tsx
packages/spor-react/src/layout/RadioCardGroup.tsx

Added documentation for props for RadioCard and RadioCardGroup.

RadioCardGroup & RadioCard: Add documentation for props

---

.github/pull_request_template.md
package-lock.json

Add new template for pull requests.

New PR template with UU-checks

---

.changeset/thirty-phones-fix.md
apps/docs/package.json
packages/spor-design-tokens/tokens/color/cargonet.json
packages/spor-design-tokens/tokens/color/vy-digital.json

Some tokens are being updated to support more components for Cargonet.

Cargonet tokens

---

.changeset/funny-terms-know.md
apps/docs/package.json
package-lock.json
packages/spor-design-tokens/tokens/color/cargonet.json

Updated accent tokens for Cargonet

Update Cargonet tokens

---

.changeset/curly-balloons-pull.md
packages/spor-react/src/alert/ExpandableAlert.tsx

Console was complaining about kebab-case in console

Alert: Fix kebabcase on inline CSS

---

.changeset/mighty-sheep-rest.md
apps/docs/app/features/portable-text/ImageWithCaption.tsx
package-lock.json
packages/spor-react/src/alert/ServiceAlert.tsx
packages/spor-react/src/theme/components/alert-service.ts

Small bug with extra border on ServiceAlert.
Updated Accordion variant, some minor changes to the styling as well.
| <img width="339" alt="image" src="https://github.com/user-attachments/assets/5ac0fa63-93ab-4192-aeed-d2f5593f5279"> | <img width="370" alt="image" src="https://github.com/user-attachments/assets/e102903c-02f3-405b-8834-01768aec28fa"> |

Service message bug

---

apps/docs/app/entry.server.tsx

Currently we do not have any CDN wrapping spor. And we have not set any cache header. The first step here is to add a cache header
Added a cache header as default

added 30 minute cache as default

---

apps/docs/app/root/layout/SiteHeader.tsx
package-lock.json
packages/spor-react/src/input/SearchInput.tsx

CI is breaking, and there is various type issues across the project.
Fixed issues

fixed issues that caused issues for CI deployment

---

.changeset/friendly-dragons-pay.md
packages/spor-react/src/linjetag/TravelTag.tsx
packages/spor-react/src/theme/components/line-icon.ts
packages/spor-react/src/theme/components/travel-tag.ts

Disabled line-tag had wrong styling
Changed styling
|![image](https://github.com/user-attachments/assets/95e4f72f-82ef-4ca2-a7d3-eaaeda5faca6)|![image](https://github.com/user-attachments/assets/0362f190-cadc-4ae3-bce3-708f87bf953f)|

Fixed styling for disabled line-tag

---

.github/workflows/release.yml

Still can't find project
use public circleci action

Use public circleci action instead

---

.github/dependabot.yml
package-lock.json

Add dependabot

---

.changeset/purple-bears-stare.md
packages/spor-react/src/list/index.tsx
packages/spor-react/src/theme/components/index.ts
packages/spor-react/src/theme/components/list.ts
packages/spor-react/src/theme/theme.ts

Lists is updated. UnorderedList and OrderedList is deprecated.

Chakra 3: Update Lists

---

packages/spor-react/src/button/CloseButton.tsx
packages/spor-react/src/button/IconButton.tsx
packages/spor-react/src/theme/components/close-button.ts

Two components in this feature branch iconButton and closeButton
Added necessary update by following the guides from Chakra 3.0
The following checks are unfortunately not possible to perform since all the components needs to be updated before the application runs locally
It is not possible to run the application locally due to fail from others components
|        |       |

Update iconButton and closeButton to checkra 3

---

.changeset/red-dots-tickle.md
package-lock.json
packages/spor-react/src/layout/PressableCard.tsx
packages/spor-react/src/theme/components/index.ts
packages/spor-react/src/theme/components/pressable-card.ts
packages/spor-react/src/theme/theme.ts

Chakra 3: PressableCard

---

.changeset/green-beans-check.md
.changeset/lovely-drinks-compete.md
packages/spor-react/src/input/Textarea.tsx
packages/spor-react/src/theme/components/index.ts
packages/spor-react/src/theme/components/textarea.ts
packages/spor-react/src/theme/index.ts
packages/spor-react/src/theme/theme.ts

chakra 3: Textarea

---

.changeset/green-beans-check.md
packages/spor-react/src/nudge/Nudge.tsx
packages/spor-react/src/popover/index.tsx
packages/spor-react/src/theme/components/popover.ts
packages/spor-react/src/tooltip/Tooltip.tsx

Update tooltip and nudge. Added popover as it's own component.

Chakra 3 - Tooltip

---

packages/spor-react/src/input/ChoiceChip.tsx
packages/spor-react/src/theme/components/choice-chip.ts

Chakra 3 - ChoiceChip

---

packages/spor-react/src/input/AttachedInputs.tsx
packages/spor-react/src/input/CountryCodeSelect.tsx
packages/spor-react/src/input/Select.tsx

Chakra 3 - AttachedInputs and CountryCodeSelect

---

packages/spor-react/src/loader/ProgressLoader.tsx

chakra 3: ProgressLoader

---

apps/docs/package.json
package-lock.json
packages/spor-react/src/input/Input.tsx
packages/spor-react/src/theme/components/input.ts

During updating to Chakra3 this component needed to be updated
Add necessary update according to migration documentation
Necessary check need to be done when is possible to deploy all components without fails

Update input form chakra3

---

packages/spor-react/src/input/Input.tsx
packages/spor-react/src/input/PasswordInput.tsx
packages/spor-react/src/input/SearchInput.tsx

Needed a clean-up of unnecessary import in input components
Remove code
No test available

Clean a fail import in input component

---

.changeset/warm-beans-dance.md
packages/spor-react/src/alert/ServiceAlert.tsx

Needed to add text for multiple notifications for nb and nn.
Added text
|<img width="846" alt="Skjermbilde 2024-12-18 kl  14 13 13" src="https://github.com/user-attachments/assets/d04fcc72-4dd6-45ef-aab5-82c0e5d537c8" />|<img width="906" alt="Skjermbilde 2024-12-18 kl  14 11 48" src="https://github.com/user-attachments/assets/38bc6daf-2391-4ade-b522-b9fb71161b0f" />|

Add text for multiple notifications

---

apps/docs/app/utils/sanity/config.ts
apps/studio/sanity.config.ts

Adds multiple workspaces to Sanity. Switches to the v2 workspace for new updates.

Add sanity workspaces

---

packages/spor-react/src/typography/Text.tsx

Check for Text component and update to Chakra 3
This was in line with the previous version just added a description for the variants values
run spor locally and check http://localhost:3000/components/text

Add extra description for variant in Text component

---

.changeset/funny-hotels-scream.md
packages/spor-design-tokens/tokens/color/cargonet.json
packages/spor-design-tokens/tokens/color/vy-digital.json

Correct wrong values for color tokens

---

.github/pull_request_template.md

Added extra fields to template for updating Spor to Chakra 3

Add checklist to pr template

---

packages/spor-design-tokens/tokens/color/cargonet.json
packages/spor-design-tokens/tokens/color/vy-digital.json

Some values changed since last check

Update alert color tokens and fix typo

---

.changeset/rich-deers-chew.md
packages/spor-react/src/progress-indicator/ProgressDot.tsx
packages/spor-react/src/progress-indicator/ProgressIndicator.tsx
packages/spor-react/src/theme/slot-recipes/progress-indicator.ts

Chakra has been updated
made necessary changes

Update progress indicator

---

.changeset/rude-hats-allow.md
packages/spor-react/src/button/Button.tsx

Disabled and loading variant was wrong
made the necessary changes

fixed disabled and loading state in button

---

packages/spor-design-tokens/tokens/color/vy-digital.json

Some colors are wrong or outdated

Fix: Update color tokens from figma

---

.circleci/config.yml
.deployment/config.yaml
apps/docs/terraform/template/main.tf
apps/docs/terraform/template/variables.tf
apps/docs/terraform/test/.envrc
apps/docs/terraform/test/main.tf

We need to deploy test environment to a new specific sub-domain
Made necessary update to config files

Update workflow to deploy update-chakra to test

---

apps/docs/terraform/service/main.tf

Add test account

---

.changeset/curvy-carpets-sniff.md
packages/spor-react/src/breadcrumb/Breadcrumb.tsx
packages/spor-react/src/theme/slot-recipes/anatomy.ts
packages/spor-react/src/theme/slot-recipes/breadcrumb.ts

- Cleaned up code
- Fixed missing variants in documentation
- Fixed border style on hover

Fix(Breadcrumbs): Improve code and fix styling mistakes

---

.changeset/eleven-seas-doubt.md
packages/spor-react/src/theme/slot-recipes/field.ts

Helpertext was hard to see in darkmode
Changed color token on helpertext

Fix helpertext

---

.changeset/gorgeous-pillows-applaud.md
packages/spor-react/src/theme/recipes/separator.ts

Separator did not use color token, so darkmode was wrong
Changed from hex code to token

Fix separator darkmode

---

packages/spor-react/src/theme/slot-recipes/list.ts

Unordered list was not proper styled since the distance between the disc and the item was too large
clean up the css and remove what was causing the issue

Fix list unordered

---

.changeset/brown-dogs-thank.md
packages/spor-react/src/theme/slot-recipes/table.ts

The tables on mobile size were not properly display and needed an horizontal scroll 
Add properties on recipe
run application locally

feat: Add properties to table slot recipe for better responsiveness

---

.changeset/rare-yaks-bathe.md
apps/docs/app/routes/_base.resources.design-tokens/utils/useDesignTokens.ts
apps/studio/components/style-overrides.css
packages/spor-design-tokens/package.json

Fixes error where json files of tokens were not exported from tokens package.

fix: Tokens exports

---

.changeset/loud-laws-talk.md
packages/spor-react/src/input/index.ts

Field was left out of index.ts and did not work

add field to index.ts

---

apps/studio/package.json
pnpm-lock.yaml

We need to upgrade to the latest version to use the new sanity dashboard
Upgraded sanity npm packages to the latest version

upgraded sanity studio to the latest version

---

.changeset/small-suns-enjoy.md
packages/spor-react/src/theme/slot-recipes/accordion.ts

Some wrong styling in accordion
Fixed styling to match Figma
Go to http://localhost:3000/components/accordion and compare to figma files (https://www.figma.com/design/Tmr2URVX2vNkyRLqKhNRQA/Vy_komponentbibliotek?node-id=26506-2246&m=dev)
|![image](https://github.com/user-attachments/assets/1504b866-0ec9-4cd8-8d54-4bc46121cc75)|![image](https://github.com/user-attachments/assets/a193377c-c08a-44e4-a6c9-8fa6d04ba049)|

fix some styling on accordion

---

.changeset/gorgeous-boxes-tan.md
packages/spor-react/src/theme/tokens/breakpoints.ts

Array syntax did not work, as you should not specify base breakpoint. 
Se docs for chakra
https://chakra-ui.com/docs/theming/customization/breakpoints

fix(breakpoints): remove base breakpoint value for correct array syntax

---

.changeset/eighty-boxes-battle.md
packages/spor-react/src/input/Combobox.tsx

lefticon did not work
Changed it to leftIcon and added it to Input
Also added an example of this in the Spor documentation

Fix bug with leftIcon on combobox

---

.changeset/tricky-comics-wait.md
packages/spor-react/src/index.tsx
packages/spor-react/src/theme/slot-recipes/index.ts
packages/spor-react/src/theme/slot-recipes/popover.ts
packages/spor-react/src/tooltip.tsx

Popover does not work on hover, which is often needed 
Closes #1766

feat(Tooltip): add new Tooltip component and update slot recipes

---

.changeset/giant-planets-judge.md
packages/spor-react/src/theme/slot-recipes/choice-chip.ts

fix(ChoiceChip): Add gap between icon and text in ChoiceChip

---

.changeset/vast-shoes-train.md
apps/designmanual-frontend/eslint.config.mjs
packages/spor-react/src/datepicker/TimeField.tsx
packages/spor-react/src/datepicker/TimePicker.tsx
packages/spor-react/src/layout/RadioCard.tsx

feat(spor-react): correct TimePicker label and fix RadioCard screen reader value

---

.changeset/config.json
.changeset/happy-rivers-greet.md
apps/design-studio/package.json
packages/spor-react/src/dialog/Drawer.tsx
packages/spor-react/src/dialog/types.ts
packages/spor-react/src/input/AttachedInputs.tsx
packages/spor-react/src/input/PhoneNumberInput.tsx
packages/spor-react/src/input/Textarea.tsx
pnpm-lock.yaml

- Fix errorLabel in attached-input to properly overlap other elements
- Prevent missing props warning in textarea
- Ensure start and end drawers have full height
Closes #1886

fix(spor-react):  Some issues

---

.changeset/real-tools-turn.md
packages/spor-design-tokens/tokens/color/vy-digital.json

https://trello.com/c/77HbUZO7/6185-endre-fargetokens-for-dark-mode-bg-tertiary

fix(tokens): update bg.tertiary.dark color from darkTeal to jungle

---

.github/workflows/deploy.yaml

Closes # 
---
---
- [ ] I have verified the design aligns with the latest Figma sketches.
---
|        |       |

Add working dir to github action
